/* Autogenerated by asm/validation/gen_bip32_vectors.py -- do not edit. */
/* BIP32 full-path derivation + xprv/xpub extended-key vectors    */
/* (oracle: independent `bip32` package, pure-Python base58check)  */

static const struct bip32_vec { const char* path; unsigned n;
    unsigned idx[6];
    const char *k, *c, *pub, *fp;
    unsigned depth; const char *parent_fp; unsigned child;
    const char *xprv, *xpub, *addr;
} BIP32VEC[] = {
    { "m/0'/1/2'/2/1000000000", 5, {0x80000000, 0x00000001, 0x80000002, 0x00000002, 0x3b9aca00},
      "471b76e389e528d6de6d816857e012c5455051cad6660850e58372a6c3e6e7c8", "c783e67b921d2beb8f6b389cc646d7263b4145701dadd2161548a8b078e65e9e", "022a471424da5e657499d1ff51cb43c47481a03b1e77f951fe64cec9f5a48f7011", "d69aa102",
      5, "d880d7d8", 0x3b9aca00,
      "xprvA41z7zogVVwxVSgdKUHDy1SKmdb533PjDz7J6N6mV6uS3ze1ai8FHa8kmHScGpWmj4WggLyQjgPie1rFSruoUihUZREPSL39UNdE3BBDu76", "xpub6H1LXWLaKsWFhvm6RVpEL9P4KfRZSW7abD2ttkWP3SSQvnyA8FSVqNTEcYFgJS2UaFcxupHiYkro49S8yGasTvXEYBVPamhGW6cFJodrTHy", "1LZiqrop2HGR4qrH1ULZPyBpU6AUP49Uam" },
    { "m/44'/0'/0'/0/0", 5, {0x8000002c, 0x80000000, 0x80000000, 0x00000000, 0x00000000},
      "57f2e082f2519681836307626e2d0e8524db0b9e98e69bbc09add2ab3f92bc02", "a5539f9f88cc575c530c49c724c8f3a908f94e5bd695be56b3eb6d2e3a93f413", "0239b4b3a27cd1dd8993038d5eb6449220b350c32ae62fec0833b93db8a49031c5", "eadbac7f",
      5, "eba2e8e8", 0x00000000,
      "xprvA4A9CuBXhdBtCaLxwrw64Jaran4n1rgzeS5mjH47Ds8V67uZS8tTkG8jV3BZi83QqYXPcN4v8EjK2Aof4YcEeqLt688mV57gF4j6QZWdP9U", "xpub6H9VcQiRXzkBR4RS3tU6RSXb8ouGRKQr1f1NXfTinCfTxvEhygCiJ4TDLHz1dyQ6d2Vz8Ne7eezkrViwaPo2ZMsNjVtFwvzsQXCDV6HJ3cV", "1NQpH6Nf8QtR2HphLRcvuVqfhXBXsiWn8r" },
    { "m/84'/0'/0'/0/0", 5, {0x80000054, 0x80000000, 0x80000000, 0x00000000, 0x00000000},
      "8d98d2f794f9935b7fb57e18dfe8d9ae34149a58835c299f219ac5fa0bac739a", "e8d6883d6096d495713279594c716913cdf70bdd0ada4d4841647246c841a110", "02ce3088b423b443a7dd03ffc917961c43df41b50a5627e1af31a2fd65c57be50a", "0f0d117a",
      5, "b1cc03eb", 0x00000000,
      "xprvA3jV4sszWisSTUNCYp5g2N7gxaqg4bLBYpAiVGicqdnFBcEKvpYq6Q7kcaPXqtQq2eAwnUmSiMkYVRxtRyJKwgSBjC48eL1kTjxnKJEQG2q", "xpub6GiqUPQtM6RjfxSfeqcgPW4RWcgAU442v36KHf8EPyKE4QZUUMs5eCSETqukDZiCsmZvrmeMQ8gWmk2AiHoq5eZQMEuw3esVpf1VV2bkoom", "12NanssrThfNFiKJeqdvtVTEaAm5eXhXdc" },
};

#define BIP32VEC_LEN (sizeof(BIP32VEC)/sizeof(BIP32VEC[0]))

