/* GENERATED by validation/gen_bip324_fs_vectors.py -- do not edit.
 * Source: Core src/test/crypto_tests.cpp. */
#ifndef BIP324_FS_VECTORS_H
#define BIP324_FS_VECTORS_H

typedef struct { const char* plain; const char* key; unsigned interval;
                 const char* cipher_after_rotation; } fs20_vec_t;

static const fs20_vec_t FS20_VEC[] = {
  { "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", "0000000000000000000000000000000000000000000000000000000000000000", 256, "a93df4ef03011f3db95f60d996e1785df5de38fc39bfcb663a47bb5561928349" },
  { "01", "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f", 5, "ea" },
  { "e93fdb5c762804b9a706816aca31e35b11d2aa3080108ef46a5b1f1508819c0a", "8ec4c3ccdaea336bdeb245636970be01266509b33f3d2642504eaf412206207a", 4096, "8bfaa4eacff308fdb4a94a5ff25bd9d0c1f84b77f81239f67ff39d6e1ac280c9" },
};
#define FS20_NVEC ((int)(sizeof(FS20_VEC)/sizeof(FS20_VEC[0])))

typedef struct { const char* plain; const char* aad; const char* key;
                 unsigned long long msg_idx; const char* cipher; } fsaead_vec_t;

static const fsaead_vec_t FSAEAD_VEC[] = {
  { "d6a4cb04ef0f7c09c1866ed29dc24d820e75b0491032a51b4c3366f9ca35c19ea3047ec6be9d45f9637b63e1cf9eb4c2523a5aab7b851ebeba87199db0e839cf0d5c25e50168306377aedbe9089fd2463ded88b83211cf51b73b150608cc7a600d0f11b9a742948482e1b109d8faf15b450aa7322e892fa2208c6691e3fecf4c711191b14d75a72147",
    "786cb9b6ebf44288974cf0",
    "5c9e1c3951a74fba66708bf9d2c217571684556b6a6a3573bff2847d38612654", 500ULL,
    "9dcebbd3281ea3dd8e9a1ef7d55a97abd6743e56ebc0c190cb2c4e14160b385e0bf508dddf754bd02c7c208447c131ce23e47a4a14dfaf5dd8bc601323950f754e05d46e9232f83fc5120fbbef6f5347a826ec79a93820718d4ec7a2b7cfaaa44b21e16d726448b62f803811aff4f6d827ed78e738ce8a507b81a8ae131311928039213de18a5120dc9b7370baca878f50ff254418de3da50c" },
  { "8349b7a2690b63d01204800c288ff1138a1d473c832c90ea8b3fc102d0bb3adc44261b247c7c3d6760bfbe979d061c305f46d94c0582ac3099f0bf249f8cb234",
    "",
    "3bd2093fcbcb0d034d8c569583c5425c1a53171ea299f8cc3bbf9ae3530adfce", 60000ULL,
    "30a6757ff8439b975363f166a0fa0e36722ab35936abd704297948f45083f4d499433137ce931f7fca28a0acd3bc30f57b550acbc21cbd45bbef0739d9caf30c14b94829deb27f0b1923a2af704ae5d6" },
};
#define FSAEAD_NVEC ((int)(sizeof(FSAEAD_VEC)/sizeof(FSAEAD_VEC[0])))

#endif
