/* AUTO-GENERATED by validation/gen_script_flags_vectors.py -- DO NOT EDIT.
 * Test vectors for script_flags_for_block, re-derived independently from
 * Core chainparams.cpp (not from the .inc the implementation itself reads,
 * so this is not just checking the generator against itself). FV_HASH is
 * Core DISPLAY-order hex; the C test reverses it to this codebase's raw
 * block_hash byte order before calling. */
#ifndef FLAGS_VEC_H
#define FLAGS_VEC_H

static const char* FV_NAME[] = {
  "dersig-before",
  "dersig-at",
  "cltv-before",
  "cltv-at",
  "csv-before",
  "csv-at",
  "segwit-before",
  "segwit-at",
  "height-0-none-active",
  "height-600000-all-active",
  "bip16-exception-hash-overrides-early",
  "taproot-exception-hash-overrides-late",
  "near-miss-hash-does-not-match-exception",
};

static const unsigned long long FV_HEIGHT[] = {
  363724, 363725, 388380, 388381, 419327, 419328, 481823, 481824, 0, 600000, 200000, 700000, 200000
};

static const char* FV_HASH[] = {
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "1111111111111111111111111111111111111111111111111111111111111111",
  "00000000000002dc756eebf4f49723ed8d30cc28a5f108eb94b1ba88ac4f9c22",
  "0000000000000000000f14c35b2d841e986ab5441de8c585d5ffe55ea1e395ad",
  "00000000000002dc756eebf4f49723ed8d30cc28a5f108eb94b1ba88ac4f9c20",
};

static const unsigned long long FV_EXPECT[] = {
  133121, 133125, 133125, 133637, 133637, 134661, 134661, 134677, 133121, 134677, 0, 3605, 133121
};

static const unsigned FV_COUNT = 13;

#endif
