/* tests/i2p_vec.h -- a REAL I2P destination and its .b32.i2p, generated by
 * the i2pd router on this box (SAM "DEST GENERATE SIGNATURE_TYPE=7") on
 * 2026-08-28. The router is the authority for both the base64 alphabet and
 * the base32(sha256(dest)) name, so the client is checked against it rather
 * than against our own arithmetic. */
#ifndef BMC_I2P_VEC_H
#define BMC_I2P_VEC_H
#define REAL_DEST_B64 "1SXzMXuSQoVhKyTxqDeX-K8qbej5JrcNTBQp5aBQTa7VJfMxe5JChWErJPGoN5f4rypt6Pkmtw1MFCnloFBNrtUl8zF7kkKFYSsk8ag3l~ivKm3o-Sa3DUwUKeWgUE2u1SXzMXuSQoVhKyTxqDeX-K8qbej5JrcNTBQp5aBQTa7VJfMxe5JChWErJPGoN5f4rypt6Pkmtw1MFCnloFBNrtUl8zF7kkKFYSsk8ag3l~ivKm3o-Sa3DUwUKeWgUE2u1SXzMXuSQoVhKyTxqDeX-K8qbej5JrcNTBQp5aBQTa7VJfMxe5JChWErJPGoN5f4rypt6Pkmtw1MFCnloFBNrtUl8zF7kkKFYSsk8ag3l~ivKm3o-Sa3DUwUKeWgUE2u1SXzMXuSQoVhKyTxqDeX-K8qbej5JrcNTBQp5aBQTa7VJfMxe5JChWErJPGoN5f4rypt6Pkmtw1MFCnloFBNrqrn70-V16IALWHaW0PZJg1XS27YGn~asebNfIFIIdCfBQAEAAcAAA=="
#define REAL_B32      "wuauccdbzcz7tquzig46dg7l5nbla6gvdpvrcbpssj2z4owf5mvq.b32.i2p"
#endif
