/* GENERATED by validation/gen_signet_custom_vectors.py -- do not edit.
 *
 * A CUSTOM signet: a P2WSH challenge over a 1-of-1 CHECKMULTISIG,
 * signed for real. The default signet challenge is a bare
 * CHECKMULTISIG, so no real block ever reaches the witness branch, and
 * the OP_TRUE fixtures that cover its wiring cannot tell whether the
 * verification flags are applied -- OP_TRUE succeeds under any flags.
 *
 * SC_SOL_GOOD and SC_SOL_DUMMY1 differ only in the CHECKMULTISIG
 * dummy element -- empty, versus one byte -- and the signature is
 * identical and correct in both. So NULLDUMMY is the only rule that
 * can separate them: a verifier that drops the flags accepts both.
 * SC_SOL_BADSIG has one bit flipped inside the DER signature. */
#ifndef SIGNET_CUSTOM_VECTORS_H
#define SIGNET_CUSTOM_VECTORS_H

#define SC_NVERSION 536870912
#define SC_NTIME    1700000000u
static const char* SC_PREV       = "00000000e1b2c3d4e5f60718293a4b5c6d7e8f90a1b2c3d4e5f60718293a4b5c";
static const char* SC_MERKLE     = "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b";
static const char* SC_CHALLENGE  = "0020c90e9d39a5af409147455be0138d337563f7671727ef7ef2bd48e3dde6b900be";
static const char* SC_WSCRIPT    = "5121027e9e724ef0627e218fe7c3718e236eb877ceabeb66dda0750c2c831f466b7e6251ae";
static const char* SC_SOL_GOOD   = "000300483045022100a201a20f775bae349359575c87548318e3b1857a8145c307e2e876ca77142b2202204c770a938a7ba0acc62383b900d96b44219a7d472714e7ecfdf915928487948e01255121027e9e724ef0627e218fe7c3718e236eb877ceabeb66dda0750c2c831f466b7e6251ae";
static const char* SC_SOL_DUMMY1 = "00030101483045022100a201a20f775bae349359575c87548318e3b1857a8145c307e2e876ca77142b2202204c770a938a7ba0acc62383b900d96b44219a7d472714e7ecfdf915928487948e01255121027e9e724ef0627e218fe7c3718e236eb877ceabeb66dda0750c2c831f466b7e6251ae";
static const char* SC_SOL_BADSIG = "000300483045022100a201a20f775bae349359575c87548318e3b1857a8145c307e2e876ca77142b2202204c770a938a7ba0acc62383b900d96b44219a7d472714e7ecf5f915928487948e01255121027e9e724ef0627e218fe7c3718e236eb877ceabeb66dda0750c2c831f466b7e6251ae";

/* The LEGACY arm: a bare CHECKMULTISIG challenge, the shape the
 * default signet uses. SC_LSOL_GOOD and SC_LSOL_DUMMY1 carry the
 * SAME correct signature and differ only in the scriptSig dummy
 * (OP_0 versus a one-byte push), so NULLDUMMY alone separates them
 * -- which is what proves the flags reach the legacy verifier. */
static const char* SC_LCHALLENGE  = "5121027e9e724ef0627e218fe7c3718e236eb877ceabeb66dda0750c2c831f466b7e6251ae";
static const char* SC_LSOL_GOOD   = "490047304402200a9bec87e9a105726e246ba90cd523278235673914ea0fb28a10f996ed98346502205e8b721e78a5001dce4d16ee365d2f6ce87547665a75d0750760f200d6656df70100";
static const char* SC_LSOL_DUMMY1 = "4a010147304402200a9bec87e9a105726e246ba90cd523278235673914ea0fb28a10f996ed98346502205e8b721e78a5001dce4d16ee365d2f6ce87547665a75d0750760f200d6656df70100";
static const char* SC_LSOL_BADSIG = "490047304402200a9bec87e9a105726e246ba90cd523278235673914ea0fb28a10f996ed98346502205e8b721e78a5001dce4d16ee365d2f6ce87547665a75d0750f60f200d6656df70100";

#endif
