/* GENERATED by validation/gen_tapscript_stack_vectors.py -- do not hand-edit. */
/* BIP342 initial-stack limit vectors. Synthetic BY NECESSITY (the shape does not
 * occur on mainnet -- 47,578 sampled real script-path inputs max out at a 79-byte
 * initial-stack item), with every expected verdict taken from Bitcoin Core's
 * ExecuteWitnessScript (src/script/interpreter.cpp:1842-1880) and cross-checked
 * against Core's own VerifyScript by validation/diff_tapscript_stack.py.
 *
 * Only the SHAPE is stored: the two 1,000,000-byte-item vectors would be 2 MB of
 * hex each. tests/test_tapscript_scale.c serializes the transaction from these
 * fields (version 2, one input spending outpoint_hex:0 with an empty scriptSig and
 * nSequence 0xffffffff, one 22-byte-P2WPKH output, witness = [filler(item_len),
 * leaf, control], nLockTime 0), with filler[i] = (uint8_t)(i*167+13). */
typedef struct { const char* name; unsigned long item_len; const char* leaf_hex;
                 const char* control_hex; const char* spk_hex; const char* outpoint_hex;
                 unsigned long long value; unsigned long long out_value;
                 int expect; int forked; const char* note; } tss_vec_t;
static const tss_vec_t TSS_VECS[4] = {
  { "init_item_520", 520UL, "827702080287", "c1175e159f728b865a72f99cc6c6fc846de0b93833fd2222ed73fce5b551e5b739", "512079a3293b2932775df9f098845fe6c688bd7a3de005b464820112a7c65173246b", "00eee7d1db4dc43fb5ed271ccbc91988aa9c0b4073a7a3ce1ccaa29129c2572d", 100000ULL, 99000ULL, 1, 0,
    "520-byte initial stack item is exactly at MAX_SCRIPT_ELEMENT_SIZE: Core ACCEPTS. Guards the fix against over-rejecting at the boundary." },
  { "init_item_521", 521UL, "827702090287", "c0d26bd0131b8c12de3dd8fefc136d9f9544ac963d4cbcbaa802ba941ef0b46a19", "5120dec0d378257cfa1432b9001a7e3563e8c1cec5d424bc2fcbabec396a8332c9a0", "3310ae51cb46d013eecf51c1be6e7f955bbaa1a05258979326507da2bad7635d", 100000ULL, 99000ULL, 0, 0,
    "521-byte initial stack item: Core's ExecuteWitnessScript rejects with SCRIPT_ERR_PUSH_SIZE. Before the fix this path had no element-size check at all, so it was a silent FALSE ACCEPT -- a consensus divergence with no memory symptom." },
  { "init_item_3900000", 3900000UL, "7551", "c15690dec1cb79ab9cd6d0cd322a442c261e94d1da1ca34386c23749c130c5c60d", "5120845597b988da70d92a4321c330fead2946142aef9cfd9cdf91b99db5ffa1f798", "28b7205f8afb84e7a705866e891b65b40c4833227fda8c8e8a83ba2d788dac62", 100000ULL, 99000ULL, 0, 1,
    "3,900,000-byte initial stack item (the largest witness item a 4M-weight block can carry is 3,938,182 B, seen at height 774628): Core rejects (SCRIPT_ERR_PUSH_SIZE). Before the fix, stack_push copied all 3.9 MB into ts_main_e's first 528-byte element record -- a ~3.4 MB overrun of a 528,000-byte heap buffer, i.e. remote memory corruption from block relay. Run in a forked child: the assertion is that the child exits CLEANLY." },
  { "opsuccess_3900000", 3900000UL, "bb", "c1202b13ea31ad2abd9635351de09f237b9f86f75ca340a47cedc1f9a325118969", "512093c4bbe9010da1e8c2fa8524e66058f7d9840519e06846f84c8963acf97459f2", "e1388cf5e3ea1e2b5c22e2b096c10371bc28647231bbeb031604863336a0a34c", 100000ULL, 99000ULL, 1, 1,
    "3,900,000-byte initial stack item under an OP_SUCCESS187 leaf: Core ACCEPTS -- its OP_SUCCESSx scan runs BEFORE both the stack-size and element-size limits and 'overrides everything'. So this exact shape is consensus-valid and mineable today. Before the fix it took the same 3.9 MB overrun as init_item_3900000; a NAIVE fix (reject >520 unconditionally) would turn it into a false reject, which is why it is here." },
};
#define TSS_N 4
