/* test_mempool_policy.c -- drive the mempool POLICY layer through the vectors
 * generated by gen_mempool_policy_vectors.py (the independent Python oracle).
 *
 * For every scenario the C harness builds a fresh policy world (pol + state +
 * structural mempool + confirmed UTXO set), preloads the scenario's funded
 * confirmed outputs, and replays the ordered steps:
 *   - "add"     : mpool_policy_add(...)  -> verdict must equal oracle's
 *   - "present" : mpool_get(txid)        -> must equal oracle's (in/out of mp)
 *   - "est"     : mpool_policy_estimate_feerate() -> must equal oracle's EMA
 *
 * The policy module under test is bitcoin_mempool_policy.c (pure C glue over
 * the verified asm mempool + asm utxo). A mismatch with the oracle is a bug.
 */
#include <stdio.h>
#include "../mempool_entry.h"
extern void mpool_policy_set_pending_sigops(unsigned long long);
extern void mpool_policy_set_bytespersigop(unsigned long long);
extern long mpool_policy_test(void*, void*, void*, const unsigned char*, unsigned long,
                              const unsigned char*, void*, unsigned long long*,
                              unsigned long long*);
extern long mpool_policy_entry_info(void*, const unsigned char*, struct mp_entry_info*);
#include <string.h>
#include <stdlib.h>
#include "mempool_policy_vec.h"

/* ---- asm structural mempool ---- */
extern size_t mpool_struct_size(unsigned long slots);
extern void   mpool_init(void* mp, unsigned long slots, void* blob, unsigned long blob_cap);
extern long   mpool_put(void* mp, const unsigned char txid[32],
                        const unsigned char* tx, unsigned long txlen);
extern const unsigned char* mpool_get(void* mp, const unsigned char txid[32],
                                      unsigned long* out_len);
extern long   mpool_count(void* mp);
/* ---- asm UTXO set ---- */
extern size_t utxo_struct_size(unsigned long slots);
extern void   utxo_init(void* u, unsigned long slots, void* blob, unsigned long blob_cap);
extern long   utxo_put(void* u, const unsigned char txid[32], unsigned long index,
                       unsigned long long value, unsigned long height,
                       unsigned long is_coinbase, const unsigned char* script, unsigned long slen);
/* ---- policy module (bitcoin_mempool_policy.c) ---- */
extern size_t mpool_policy_state_size(unsigned n);
extern void   mpool_policy_state_init(void* st, unsigned n);
extern void   mpool_policy_init(void* pol, unsigned long long relay_fee_rate,
                                unsigned max_anc, unsigned max_anc_bytes,
                                unsigned max_desc, unsigned max_desc_bytes,
                                unsigned rbf_enabled);
extern void mpool_policy_set_acceptnonstd(void*, unsigned);
extern void mpool_policy_set_baremultisig(void*, unsigned);
static int test_bare_multisig(void);   /* defined below main */
extern long   mpool_policy_add(void* pol, void* st, void* mp,
                               const unsigned char* tx, unsigned long txlen,
                               const unsigned char txid[32], void* utxo);
extern unsigned long long mpool_policy_estimate_feerate(void* st);
extern const char* mpool_policy_reason(void* pol);
extern long mpool_policy_n_parents(void* st, const unsigned char txid[32]);

/* bitcoin_mempool_policy.c now calls mempool_resolve_confirmed_utxo instead
 * of utxo_get directly (see its own extern's comment) -- this harness still
 * wants the real, single-table bitcoin_utxo.asm behavior, so just pass
 * through unchanged. */
extern long utxo_get(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, unsigned long* height,
                     unsigned long* is_coinbase, const unsigned char** script,
                     unsigned long* slen);
long mempool_resolve_confirmed_utxo(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, const unsigned char** script,
                     unsigned long* slen){
    unsigned long h_unused, cb_unused;
    return utxo_get(u, txid, index, value, &h_unused, &cb_unused, script, slen);
}

static int hex_in(unsigned char* out, const char* h);

static int failures = 0;

/* ---- state buffers must be big enough, and SAY SO when they are not ----
 *
 * These buffers are fixed-size statics and mpool_policy_state_init memsets
 * the whole state, so one that is too small overflows into whatever follows
 * -- silently. This file had been doing exactly that: at n=4096 the state has
 * always needed more than the 1 MB the buffers declared (1,163,360 bytes
 * before the MEM-3/MEM-12 layout work, 1,126,240 after), so ~114 KB was being
 * written past the end on every run. Nothing visible broke until a layout
 * change moved which static landed in the overflow -- and then it was the
 * failure counter itself, which is how a passing suite reported "-1
 * failures".
 *
 * Every state_init in this file goes through this macro, so the next time a
 * layout grows past a buffer the suite fails with the two numbers rather than
 * corrupting itself. */
#define POLICY_STATE_INIT(buf, n) do { \
    size_t _need = mpool_policy_state_size((unsigned)(n)); \
    if (_need > sizeof (buf)) { \
        printf("FAIL: policy state buffer too small for n=%u: need %zu, have %zu\n", \
               (unsigned)(n), _need, sizeof (buf)); \
        failures++; \
    } else mpool_policy_state_init((buf), (unsigned)(n)); \
} while (0)
#define MAXTX 4096

static int run_scenario(int si,
                        unsigned max_anc, unsigned max_anc_bytes,
                        unsigned max_desc, unsigned max_desc_bytes,
                        unsigned rbf,
                        const char* const* utxo_txid, const unsigned* utxo_idx,
                        const unsigned long long* utxo_val, unsigned nutxo,
                        unsigned nsteps,
                        const char* const* step_tx, const char* const* step_txid,
                        const unsigned* step_kind, const unsigned* step_expect,
                        const unsigned long long* step_arg);

int main(void){
    /* ---- scenario 0: core (fee / double-spend / RBF) ---- */
    run_scenario(0, SCEN0_MAXANC, SCEN0_MAXANC_B, SCEN0_MAXDESC, SCEN0_MAXDESC_B,
                 SCEN0_RBF, SCEN0_UTXO_TXID, SCEN0_UTXO_IDX, SCEN0_UTXO_VAL, SCEN0_NUTXO,
                 SCEN0_NSTEPS, SCEN0_STEP_TX, SCEN0_STEP_TXID, SCEN0_STEP_KIND,
                 SCEN0_STEP_EXPECT, SCEN0_STEP_ARG);
    /* ---- scenario 1: ancestor limit ---- */
    run_scenario(1, SCEN1_MAXANC, SCEN1_MAXANC_B, SCEN1_MAXDESC, SCEN1_MAXDESC_B,
                 SCEN1_RBF, SCEN1_UTXO_TXID, SCEN1_UTXO_IDX, SCEN1_UTXO_VAL, SCEN1_NUTXO,
                 SCEN1_NSTEPS, SCEN1_STEP_TX, SCEN1_STEP_TXID, SCEN1_STEP_KIND,
                 SCEN1_STEP_EXPECT, SCEN1_STEP_ARG);
    /* ---- scenario 2: descendant limit ---- */
    run_scenario(2, SCEN2_MAXANC, SCEN2_MAXANC_B, SCEN2_MAXDESC, SCEN2_MAXDESC_B,
                 SCEN2_RBF, SCEN2_UTXO_TXID, SCEN2_UTXO_IDX, SCEN2_UTXO_VAL, SCEN2_NUTXO,
                 SCEN2_NSTEPS, SCEN2_STEP_TX, SCEN2_STEP_TXID, SCEN2_STEP_KIND,
                 SCEN2_STEP_EXPECT, SCEN2_STEP_ARG);
    /* ---- scenario 3: fee estimator ---- */
    run_scenario(3, SCEN3_MAXANC, SCEN3_MAXANC_B, SCEN3_MAXDESC, SCEN3_MAXDESC_B,
                 SCEN3_RBF, SCEN3_UTXO_TXID, SCEN3_UTXO_IDX, SCEN3_UTXO_VAL, SCEN3_NUTXO,
                 SCEN3_NSTEPS, SCEN3_STEP_TX, SCEN3_STEP_TXID, SCEN3_STEP_KIND,
                 SCEN3_STEP_EXPECT, SCEN3_STEP_ARG);

    failures += test_bare_multisig();

/* Evaluates the condition ONCE. It used to appear twice in the body -- once
 * for the label, once for the counter -- so any check whose condition had a
 * side effect ran it twice. A `okv(mpool_policy_add(...) == 1, ...)` then
 * submitted the transaction a second time, the duplicate was refused, and the
 * case reported "ok" while quietly incrementing the failure count. */
#define okv(c, msg) do{ int _okv = (c) ? 1 : 0; \
    printf("  %s %s\n", _okv?"ok ":"FAIL", (msg)); if(!_okv) failures++; }while(0)
    printf("== Core v31 cluster limits (too-large-cluster) ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);  /* anc/desc limits out of the way */
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* 64 INDEPENDENT parents (cluster of 1 each), then one child spending
         * all 64: anc_cnt 64 passes the old limits, the cluster of 65 must not */
        static unsigned char ptxid[64][32];
        unsigned char spk[2] = { 0x51, 0x00 };            /* tiny anyone-can-spend-ish */
        for (int i = 0; i < 64; i++){
            unsigned char prev[32]; memset(prev, 0x60 + (i & 15), 32); prev[0] = (unsigned char)i;
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x21+i, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            memset(ptxid[i], 0x90, 32); ptxid[i][0] = (unsigned char)i;   /* synthetic txid: the pool stores what we pass */
            long r = mpool_policy_add(pol, stbuf, mp, tx, n, ptxid[i], ux);
            if (r != 1){ printf("      parent %d rejected: %s\n", i, mpool_policy_reason(pol)); }
            if (r != 1){ okv(0, "all 64 independent parents accepted"); break; }
            if (i == 63) okv(1, "all 64 independent parents accepted");
        }
        unsigned char ctx[64*41 + 64]; unsigned long n = 0;
        ctx[n++]=2;ctx[n++]=0;ctx[n++]=0;ctx[n++]=0;
        ctx[n++]=64;
        for (int i = 0; i < 64; i++){ memcpy(ctx+n, ptxid[i], 32); n+=32; memset(ctx+n, 0, 4); n+=4; ctx[n++]=0; memset(ctx+n,0xff,4); n+=4; }
        ctx[n++]=1; { unsigned long long v = 64*900000ULL - 100000ULL; for (int b=0;b<8;b++) ctx[n++]=(unsigned char)(v>>(8*b)); }
        ctx[n++]=22; ctx[n++]=0x00; ctx[n++]=0x14; memset(ctx+n, 0x77, 20); n+=20;
        memset(ctx+n, 0, 4); n+=4;
        unsigned char ctid[32]; memset(ctid, 0x9F, 32);
        long r = mpool_policy_add(pol, stbuf, mp, ctx, n, ctid, ux);
        okv(r != 1, "a child joining 64 independent parents is refused");
        okv(r != 1 && strstr(mpool_policy_reason(pol), "too-large-cluster") != NULL, "...as too-large-cluster (anc/desc limits alone would have let it in)");
    }
    /* ================================================================
     * MEM-3 (audit 2026-09-03): the parent list is no longer truncated.
     *
     * MPOL_MAX_PARENTS was 24 and mpol_collect_parents dropped everything
     * past it SILENTLY. parent[] is the only record of the graph --
     * descendants are found by walking it -- so a dropped parent did not
     * exist as far as eviction, expiry and RBF were concerned. The audit's
     * scenario: 30 low-feerate parents and a child spending all 30; the child
     * is stored linked to 24; RBF-replace the 30th (your own coin) and
     * collect_descendant_txids finds no child, so the child stays in the pool
     * spending an output the replacement has conflicted -- and
     * getblocktemplate includes it, because every REGISTERED ancestor is
     * present. An invalid block.
     *
     * 30 parents is the shape that matters: comfortably past the old cap of
     * 24, comfortably inside the 63 that v31's 64-transaction cluster limit
     * allows, so it must be ACCEPTED and fully linked.
     * ================================================================ */
    printf("== MEM-3: a 30-parent child keeps every parent link ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);

        enum { NP = 30 };
        static unsigned char ptxid[NP][32];
        unsigned char spk[2] = { 0x51, 0x00 };
        int all_ok = 1;
        for (int i = 0; i < NP; i++){
            unsigned char prev[32]; memset(prev, 0xC0 + (i & 15), 32); prev[0] = (unsigned char)i;
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0;
            tx[n]=1; tx[n+1]=0; tx[n+2]=0; tx[n+3]=0; n+=4;      /* seq 1: replaceable */
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x41+i, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            memset(ptxid[i], 0xD0, 32); ptxid[i][0] = (unsigned char)i;
            if (mpool_policy_add(pol, stbuf, mp, tx, n, ptxid[i], ux) != 1) all_ok = 0;
        }
        okv(all_ok, "MEM-3 30 independent parents accepted");

        static unsigned char ctx[NP*41 + 64]; unsigned long n = 0;
        ctx[n++]=2;ctx[n++]=0;ctx[n++]=0;ctx[n++]=0;
        ctx[n++]=NP;
        for (int i = 0; i < NP; i++){ memcpy(ctx+n, ptxid[i], 32); n+=32; memset(ctx+n, 0, 4); n+=4; ctx[n++]=0;
            memset(ctx+n,0xff,4); n+=4; }
        ctx[n++]=1; { unsigned long long v = (unsigned long long)NP*900000ULL - 50000ULL;
                      for (int b=0;b<8;b++) ctx[n++]=(unsigned char)(v>>(8*b)); }
        ctx[n++]=22; ctx[n++]=0x00; ctx[n++]=0x14; memset(ctx+n, 0x79, 20); n+=20;
        memset(ctx+n, 0, 4); n+=4;
        unsigned char ctid[32]; memset(ctid, 0xDF, 32);
        { long rC = mpool_policy_add(pol, stbuf, mp, ctx, n, ctid, ux);
          okv(rC == 1, "MEM-3 the 30-parent child is accepted"); }

        /* THE ASSERTION THAT MATTERS. Every parent must be recorded, so the
         * pool must report 30 -- with the old inline cap it reported 24 and
         * the six beyond it were invisible to every descendant walk. */
        { long np = mpool_policy_n_parents(stbuf, ctid);
          printf("      (child reports %ld parents; 30 expected, old cap was 24)\n", np);
          okv(np == NP, "MEM-3 the child records ALL 30 parents, not 24"); }

        /* And the consequence: replacing the LAST parent -- the one the old
         * cap dropped -- must take the child with it. Under the truncation
         * the child survived, spending an output that no longer existed. */
        {
            unsigned char prev[32]; memset(prev, 0xC0 + ((NP-1) & 15), 32); prev[0] = (unsigned char)(NP-1);
            unsigned char rtx[128]; unsigned long m = 0;
            rtx[m++]=2;rtx[m++]=0;rtx[m++]=0;rtx[m++]=0;
            rtx[m++]=1; memcpy(rtx+m, prev, 32); m+=32; memset(rtx+m, 0, 4); m+=4; rtx[m++]=0; memset(rtx+m,0xff,4); m+=4;
            rtx[m++]=1; { unsigned long long v = 500000ULL; for (int b=0;b<8;b++) rtx[m++]=(unsigned char)(v>>(8*b)); }
            rtx[m++]=22; rtx[m++]=0x00; rtx[m++]=0x14; memset(rtx+m, 0x7A, 20); m+=20;
            memset(rtx+m, 0, 4); m+=4;
            unsigned char rtid[32]; memset(rtid, 0xEE, 32);
            long rr = mpool_policy_add(pol, stbuf, mp, rtx, m, rtid, ux);
            printf("      (replacement of parent %d -> %ld %s)\n", NP-1, rr,
                   rr == 1 ? "accepted" : mpool_policy_reason(pol));
            okv(rr == 1, "MEM-3 a replacement of the LAST parent is accepted");
            unsigned long l;
            okv(mpool_get(mp, ptxid[NP-1], &l) == NULL,
                "MEM-3 ...the replaced parent is gone");
            okv(mpool_get(mp, ctid, &l) == NULL,
                "MEM-3 ...and the child went WITH it (the link was recorded)");
        }
    }

    printf("== cluster limit is measured POST-eviction for a replacement ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* 63 independent parents, one child C spending all of them: a
         * cluster of exactly 64, at the limit */
        static unsigned char ptxid[63][32];
        unsigned char spk[2] = { 0x51, 0x00 };
        int all_ok = 1;
        for (int i = 0; i < 63; i++){
            unsigned char prev[32]; memset(prev, 0xA0 + (i & 15), 32); prev[0] = (unsigned char)i;
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x31+i, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            memset(ptxid[i], 0xB0, 32); ptxid[i][0] = (unsigned char)i;
            if (mpool_policy_add(pol, stbuf, mp, tx, n, ptxid[i], ux) != 1) all_ok = 0;
        }
        okv(all_ok, "63 independent parents accepted");
        static unsigned char ctx[63*41 + 64]; unsigned long n = 0;
        ctx[n++]=2;ctx[n++]=0;ctx[n++]=0;ctx[n++]=0;
        ctx[n++]=63;
        for (int i = 0; i < 63; i++){ memcpy(ctx+n, ptxid[i], 32); n+=32; memset(ctx+n, 0, 4); n+=4; ctx[n++]=0;
            ctx[n]=1; ctx[n+1]=0; ctx[n+2]=0; ctx[n+3]=0; n+=4; }        /* sequence 1: BIP125 signaling */
        ctx[n++]=1; { unsigned long long v = 63*900000ULL - 50000ULL; for (int b=0;b<8;b++) ctx[n++]=(unsigned char)(v>>(8*b)); }
        ctx[n++]=22; ctx[n++]=0x00; ctx[n++]=0x14; memset(ctx+n, 0x78, 20); n+=20;
        memset(ctx+n, 0, 4); n+=4;
        unsigned char ctid[32]; memset(ctid, 0xBF, 32);
        { long rC = mpool_policy_add(pol, stbuf, mp, ctx, n, ctid, ux);   /* okv double-evaluates: never call inside it */
          okv(rC == 1, "child C joins them: cluster of exactly 64 accepted"); }
        /* C' double-spends one of C's inputs -> conflicts with C, evicting
         * it. The cluster C' joins is parent[0] ALONE once C is gone; the
         * old walk still counted C and the 62 parents behind it and refused
         * a replacement that was thinning the very cluster it joined. */
        unsigned char rtx[128]; n = 0;
        rtx[n++]=2;rtx[n++]=0;rtx[n++]=0;rtx[n++]=0;
        rtx[n++]=1; memcpy(rtx+n, ptxid[0], 32); n+=32; memset(rtx+n, 0, 4); n+=4; rtx[n++]=0;
        rtx[n]=1; rtx[n+1]=0; rtx[n+2]=0; rtx[n+3]=0; n+=4;
        rtx[n++]=1; { unsigned long long v = 100000ULL; for (int b=0;b<8;b++) rtx[n++]=(unsigned char)(v>>(8*b)); }
        rtx[n++]=22; rtx[n++]=0x00; rtx[n++]=0x14; memset(rtx+n, 0x79, 20); n+=20;
        memset(rtx+n, 0, 4); n+=4;
        unsigned char rtid[32]; memset(rtid, 0xC5, 32);
        long r = mpool_policy_add(pol, stbuf, mp, rtx, n, rtid, ux);
        if (r != 1) printf("      replacement rejected: %s\n", mpool_policy_reason(pol));
        okv(r == 1, "replacement is measured against the POST-eviction cluster");
    }
    printf("== bytespersigop: sigop-dense feerate (Core DEFAULT_BYTES_PER_SIGOP 20) ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);   /* 1 sat/vB floor */
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0x7A, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
        unsigned char tx[128]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
        tx[n++]=1; { unsigned long long v = 1000000ULL - 200ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
        tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x88, 20); n+=20;
        memset(tx+n, 0, 4); n+=4;                                   /* ~60 vB paying 200 sat: 3.3 sat/vB */
        unsigned char tid[32]; memset(tid, 0x7B, 32);
        mpool_policy_set_pending_sigops(80);                        /* 80 x4-units -> eff vsize max(60, 400) = 400 -> 0.5 sat/vB */
        long r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
        okv(r != 1 && strstr(mpool_policy_reason(pol), "min relay fee") != NULL,
           "sigop-dense: fee judged against max(vsize, sigops*5) and refused");
        mpool_policy_set_pending_sigops(0);
        r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
        okv(r == 1, "the same tx without the sigop load is fine at 3.3 sat/vB");

        /* The adjustment is the ENTRY's size, not a number used once at the
         * fee gate: Core's GetTxSize() is the sigop-adjusted vsize, so the
         * chain-limit budgets, replacement arithmetic, eviction and
         * getmempoolentry all see it. Read it back off the accepted entry. */
        {   struct mp_entry_info ei;
            okv(mpool_policy_entry_info(stbuf, tid, &ei) == 1, "entry readable");
            okv(ei.size > 0 && ei.size < 200, "a sigop-free entry keeps its BIP141 vsize");
            unsigned long long plain = ei.size;

            /* same transaction, now carrying sigops and paying enough to get
             * in: its recorded size must be the ADJUSTED one */
            memset(stbuf, 0, sizeof stbuf);
            POLICY_STATE_INIT(stbuf, 256);
            mpool_init(mp, 4096, mblob, sizeof mblob);
            utxo_init(ux, 4096, ublob, sizeof ublob);
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx2[128]; unsigned long n2 = 0;
            tx2[n2++]=2;tx2[n2++]=0;tx2[n2++]=0;tx2[n2++]=0;
            tx2[n2++]=1; memcpy(tx2+n2, prev, 32); n2+=32; memset(tx2+n2,0,4); n2+=4; tx2[n2++]=0; memset(tx2+n2,0xff,4); n2+=4;
            tx2[n2++]=1; { unsigned long long v = 1000000ULL - 5000ULL; for (int b=0;b<8;b++) tx2[n2++]=(unsigned char)(v>>(8*b)); }
            tx2[n2++]=22; tx2[n2++]=0x00; tx2[n2++]=0x14; memset(tx2+n2,0x88,20); n2+=20;
            memset(tx2+n2,0,4); n2+=4;                       /* 5000 sat: clears 400 vB at 1 sat/vB */
            unsigned char tid2[32]; memset(tid2, 0x7C, 32);
            mpool_policy_set_pending_sigops(80);
            okv(mpool_policy_add(pol, stbuf, mp, tx2, n2, tid2, ux) == 1,
               "sigop-dense tx paying the adjusted price is accepted");
            okv(mpool_policy_entry_info(stbuf, tid2, &ei) == 1, "its entry is readable");
            okv(ei.size == 400, "the ENTRY records the sigop-adjusted vsize (80*20/4 = 400)");
            okv(ei.size > plain, "...which is larger than the BIP141 vsize it would have had");
        }
    }

    /* A rejected transaction must not price the next one. The count is parked
     * in a global by the caller before the call; there are rejection paths
     * between the top of mpol_accept and the fee gate, and one of them used to
     * leave the count parked for whatever came next. */
    {   printf("\n== a rejected tx does not leave its sigop count behind ==\n");
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0x9A, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);

        /* (1) a heavy sigop load parked, on a tx that dies EARLY -- it spends
         * an input that does not exist, which is refused well before the fee
         * gate where the count used to be cleared. */
        unsigned char miss[32]; memset(miss, 0xDD, 32);
        unsigned char bad[128]; unsigned long bn = 0;
        bad[bn++]=2;bad[bn++]=0;bad[bn++]=0;bad[bn++]=0;
        bad[bn++]=1; memcpy(bad+bn, miss, 32); bn+=32; memset(bad+bn,0,4); bn+=4; bad[bn++]=0; memset(bad+bn,0xff,4); bn+=4;
        bad[bn++]=1; { unsigned long long v = 1000ULL; for (int b=0;b<8;b++) bad[bn++]=(unsigned char)(v>>(8*b)); }
        bad[bn++]=22; bad[bn++]=0x00; bad[bn++]=0x14; memset(bad+bn,0x77,20); bn+=20;
        memset(bad+bn,0,4); bn+=4;
        unsigned char bid[32]; memset(bid, 0x9B, 32);
        mpool_policy_set_pending_sigops(4000);          /* 4000*20/4 = 20000 vB if it ever applied */
        okv(mpool_policy_add(pol, stbuf, mp, bad, bn, bid, ux) != 1,
           "the sigop-laden tx is rejected before the fee gate");

        /* (2) now an ordinary, sigop-FREE transaction, with nothing parked.
         * It pays 200 sat on ~60 vB, comfortably over the 1 sat/vB floor --
         * unless it inherits the 4000 sigops from the corpse above, which
         * would price it at 20000 vB and refuse it. */
        unsigned char ok2[128]; unsigned long on = 0;
        ok2[on++]=2;ok2[on++]=0;ok2[on++]=0;ok2[on++]=0;
        ok2[on++]=1; memcpy(ok2+on, prev, 32); on+=32; memset(ok2+on,0,4); on+=4; ok2[on++]=0; memset(ok2+on,0xff,4); on+=4;
        ok2[on++]=1; { unsigned long long v = 1000000ULL - 200ULL; for (int b=0;b<8;b++) ok2[on++]=(unsigned char)(v>>(8*b)); }
        ok2[on++]=22; ok2[on++]=0x00; ok2[on++]=0x14; memset(ok2+on,0x66,20); on+=20;
        memset(ok2+on,0,4); on+=4;
        unsigned char oid[32]; memset(oid, 0x9C, 32);
        long rr = mpool_policy_add(pol, stbuf, mp, ok2, on, oid, ux);
        okv(rr == 1, "the NEXT tx is judged on its own sigops, not the dead one's");
        if (rr != 1) printf("     (reason: %s)\n", mpool_policy_reason(pol));
    }

    /* Core takes the max on the WEIGHT scale and rounds once, at the end:
     * ceil(max(weight, sigops*bytespersigop) / 4). Rounding first and taking
     * the max after loses a byte whenever sigops*bytespersigop is not a
     * multiple of 4 -- invisible at the default bytespersigop of 20, which is
     * itself a multiple of 4, so this uses a value that is not. */
    {   printf("\n== the adjustment rounds the way Core rounds ==\n");
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0xB1, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
        unsigned char tx[128]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
        tx[n++]=1; { unsigned long long v = 1000000ULL - 90000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
        tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n,0x55,20); n+=20;
        memset(tx+n,0,4); n+=4;
        unsigned char tid[32]; memset(tid, 0xB2, 32);
        mpool_policy_set_bytespersigop(5);
        mpool_policy_set_pending_sigops(1001);   /* 1001*5 = 5005 weight units */
        okv(mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux) == 1, "accepted");
        {   struct mp_entry_info ei;
            okv(mpool_policy_entry_info(stbuf, tid, &ei) == 1, "entry readable");
            /* ceil(5005/4) = 1252, not 5005/4 = 1251 */
            okv(ei.size == 1252, "ceil(max(weight, sigops*bps)/4) -- 1252, not the truncated 1251");
        }
        mpool_policy_set_bytespersigop(20);      /* back to Core's default */
    }

    /* The package feerate is aggregated by daemon/main.c and tx_relay.c from
     * what the DRY RUN reports, and Core computes it over entry sizes -- which
     * are the sigop-adjusted ones. The structural walker that hands those
     * callers a vsize cannot count sigops (they need the UTXO view), so the
     * adjusted figure has to come back out of the policy layer. This is that
     * contract: mpool_policy_test reports it, and reports it even when the
     * transaction is REJECTED on fee, because a fee-reconsiderable member
     * still contributes its size to the package total. */
    {   printf("\n== the dry run reports the sigop-adjusted vsize ==\n");
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0xC1, 32);
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, (const unsigned char*)"\x51", 1);
        unsigned char tx[128]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
        tx[n++]=1; { unsigned long long v = 1000000ULL - 200ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
        tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n,0x33,20); n+=20;
        memset(tx+n,0,4); n+=4;                     /* ~60 vB paying 200 sat */
        unsigned char tid[32]; memset(tid, 0xC2, 32);

        unsigned long long fee = 0, avs = 0;
        mpool_policy_set_pending_sigops(80);        /* 80*20/4 = 400 vB */
        long rv = mpool_policy_test(pol, stbuf, mp, tx, n, tid, ux, &fee, &avs);
        okv(rv != 1, "200 sat over the adjusted 400 vB is under the 1 sat/vB floor");
        okv(avs == 400, "the dry run still reports the ADJUSTED vsize on a fee rejection");

        /* and on an accept, with enough fee to clear 400 vB */
        unsigned char tx2[128]; unsigned long n2 = 0;
        tx2[n2++]=2;tx2[n2++]=0;tx2[n2++]=0;tx2[n2++]=0;
        tx2[n2++]=1; memcpy(tx2+n2, prev, 32); n2+=32; memset(tx2+n2,0,4); n2+=4; tx2[n2++]=0; memset(tx2+n2,0xff,4); n2+=4;
        tx2[n2++]=1; { unsigned long long v = 1000000ULL - 5000ULL; for (int b=0;b<8;b++) tx2[n2++]=(unsigned char)(v>>(8*b)); }
        tx2[n2++]=22; tx2[n2++]=0x00; tx2[n2++]=0x14; memset(tx2+n2,0x44,20); n2+=20;
        memset(tx2+n2,0,4); n2+=4;
        unsigned char tid2[32]; memset(tid2, 0xC3, 32);
        fee = 0; avs = 0;
        mpool_policy_set_pending_sigops(80);
        long rv2 = mpool_policy_test(pol, stbuf, mp, tx2, n2, tid2, ux, &fee, &avs);
        okv(rv2 == 1, "the better-paying one passes the dry run");
        okv(avs == 400, "...and reports the adjusted vsize too");
        okv(fee == 5000, "...with its fee");

        /* no sigops parked: the plain BIP141 vsize comes back */
        fee = 0; avs = 0;
        long rv3 = mpool_policy_test(pol, stbuf, mp, tx2, n2, tid2, ux, &fee, &avs);
        okv(rv3 == 1, "sigop-free dry run passes");
        okv(avs > 0 && avs < 200, "...and reports the plain vsize when nothing is parked");
    }

    printf("\n%s (%d failures)\n", failures ? "TESTS FAILED" : "ALL TESTS PASSED", failures);
    return failures ? 1 : 0;
}


/* ---- -permitbaremultisig, through the REAL acceptance path ---------------
 * The option was already covered at the config layer and at the setter, but
 * not where it matters: the actual REJECTION. standard_checks() is static
 * behind mpol_add_core, so the only honest way to assert it is to build a
 * transaction with a bare multisig output and push it through
 * mpool_policy_add twice -- once with the option on, once off -- and require
 * the verdict to differ.
 *
 * Note this scenario deliberately does NOT set -acceptnonstdtxn, unlike the
 * fee/graph scenarios above: standardness is precisely what is under test. */
static int test_bare_multisig(void){
    int bad = 0;
    printf("== permitbaremultisig: the rejection itself ==\n");

    /* a 1-of-1 bare multisig: OP_1 <33-byte pubkey> OP_1 OP_CHECKMULTISIG */
    unsigned char spk[37];
    spk[0] = 0x51; spk[1] = 0x21;
    for (int i = 0; i < 33; i++) spk[2+i] = (unsigned char)(0x02 + (i & 1));  /* plausible compressed key */
    spk[35] = 0x51; spk[36] = 0xae;

    unsigned char prev[32]; memset(prev, 0x11, 32);

    /* build the raw tx by hand: 1 input (empty scriptSig), 1 bare-multisig output */
    unsigned char tx[256]; unsigned long n = 0;
    tx[n++]=0x02; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* version 2 */
    tx[n++]=0x01;                                                 /* 1 input   */
    memcpy(tx+n, prev, 32); n += 32;
    tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* vout 0    */
    tx[n++]=0x00;                                                 /* empty scriptSig (push-only) */
    tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff;      /* sequence  */
    tx[n++]=0x01;                                                 /* 1 output  */
    { unsigned long long v = 100000ULL;                           /* well above dust */
      for (int i = 0; i < 8; i++) tx[n++] = (unsigned char)(v >> (8*i)); }
    tx[n++] = (unsigned char)sizeof spk;
    memcpy(tx+n, spk, sizeof spk); n += sizeof spk;
    tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* locktime  */

    unsigned char txid[32]; memset(txid, 0x22, 32);

    for (int permit = 1; permit >= 0; permit--){
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000 /* sat/kvB: 1 sat/vB, as before */, 25, 101000, 25, 101000, 1);
        mpool_policy_set_baremultisig(pol, (unsigned)permit);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* fund it generously so the fee is never the reason for a rejection */
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, (const unsigned char*)"\x51", 1);

        long rv = mpool_policy_add(pol, stbuf, mp, tx, n, txid, ux);
        const char* why = mpool_policy_reason(pol);
        /* this API returns 1 for accepted and 0 for rejected -- NOT a negative
         * errno. Checking rv >= 0 makes both outcomes look like success, which
         * is how the first cut of this test "passed" the accept case while
         * proving nothing. */
        if (permit){
            if (rv == 1){ printf("  ok  permitbaremultisig=1 ACCEPTS a bare multisig output\n"); }
            else { printf("  FAIL permitbaremultisig=1 rejected it: %s\n", why ? why : "?"); bad++; }
        } else {
            if (rv == 0 && why && strcmp(why, "bare-multisig") == 0){
                printf("  ok  permitbaremultisig=0 REJECTS it, with reason \"bare-multisig\"\n");
            } else if (rv == 0){
                printf("  FAIL rejected, but for the wrong reason: %s\n", why ? why : "?"); bad++;
            } else { printf("  FAIL permitbaremultisig=0 still accepted it (rv=%ld)\n", rv); bad++; }
        }
    }
    return bad;
}

/* ---- run one scenario ---- */
static int run_scenario(int si,
                        unsigned max_anc, unsigned max_anc_bytes,
                        unsigned max_desc, unsigned max_desc_bytes,
                        unsigned rbf,
                        const char* const* utxo_txid, const unsigned* utxo_idx,
                        const unsigned long long* utxo_val, unsigned nutxo,
                        unsigned nsteps,
                        const char* const* step_tx, const char* const* step_txid,
                        const unsigned* step_kind, const unsigned* step_expect,
                        const unsigned long long* step_arg){
    /* policy config + state */
    static unsigned char pol[128];
    static unsigned char stbuf[1<<21];
    memset(stbuf, 0, sizeof stbuf);
    mpool_policy_init(pol, 1000 /* sat/kvB: 1 sat/vB, as before */, max_anc, max_anc_bytes, max_desc, max_desc_bytes, rbf);
    /* fixtures are synthetic, deliberately non-standard txs: run under
     * Core's own regtest escape hatch (-acceptnonstdtxn) so this test
     * keeps exercising fee/graph mechanics, not IsStandardTx. */
    mpool_policy_set_acceptnonstd(pol, 1);
    POLICY_STATE_INIT(stbuf, 256);

    /* structural mempool */
    static unsigned char mp[40 + 4096*48 + 8];
    static unsigned char mblob[1<<20];
    mpool_init(mp, 4096, mblob, sizeof mblob);

    /* confirmed UTXO set */
    static unsigned char ux[40 + 4096*48 + 8];
    static unsigned char ublob[1<<16];
    utxo_init(ux, 4096, ublob, sizeof ublob);
    for (unsigned i=0;i<nutxo;i++){
        unsigned char t[32];
        hex_in(t, utxo_txid[i]);
        utxo_put(ux, t, utxo_idx[i], utxo_val[i], 0, 0, (const unsigned char*)"\x51", 1);
    }

    printf("== scenario %d: %u steps ==\n", si, nsteps);
    unsigned ok=0, bad=0;
    for (unsigned i=0;i<nsteps;i++){
        switch (step_kind[i]){
        case 0: { /* add */
            unsigned char txbuf[MAXTX]; unsigned char txid[32];
            int n = hex_in(txbuf, step_tx[i]);
            hex_in(txid, step_txid[i]);
            long rv = mpool_policy_add(pol, stbuf, mp, txbuf, (unsigned long)n,
                                       txid, ux);
            int expect = (int)step_expect[i];
            if (rv == expect){ printf("  ok  : [%u] add  verdict=%ld (exp %d)\n",
                                      i, rv, expect); ok++;}
            else{ printf("  FAIL: [%u] add  verdict=%ld (exp %d) reason=%s\n",
                         i, rv, expect, mpool_policy_reason(pol)); bad++; failures++; }
            break;
        }
        case 1: { /* present */
            unsigned char txid[32];
            hex_in(txid, step_txid[i]);
            unsigned long len=0;
            const unsigned char* p = mpool_get(mp, txid, &len);
            int present = p!=NULL ? 1 : 0;
            int expect = (int)step_expect[i];
            if (present == expect){ printf("  ok  : [%u] mempool present=%d (exp %d)\n", i, present, expect); ok++;}
            else{ printf("  FAIL: [%u] mempool present=%d (exp %d)\n", i, present, expect); bad++; failures++; }
            break;
        }
        case 2: { /* est */
            unsigned long long got = mpool_policy_estimate_feerate(stbuf);
            unsigned long long expect = step_arg[i];
            /* allow EMA division differences of at most 1 sat/kB */
            long diff = (long)got - (long)expect; if (diff<0) diff=-diff;
            if (diff <= 1){ printf("  ok  : [%u] est feerate=%llu (exp %llu)\n", i, got, expect); ok++;}
            else{ printf("  FAIL: [%u] est feerate=%llu (exp %llu)\n", i, got, expect); bad++; failures++; }
            break;
        }
        default:
            printf("  FAIL: [%u] unknown kind %u\n", i, step_kind[i]); failures++;
        }
    }
    printf("  scenario %d: %u ok, %u bad\n", si, ok, bad);
    return bad?1:0;
}

static int hex_in(unsigned char* out, const char* h){
    int n = (int)strlen(h)/2;
    for (int i=0;i<n;i++){ unsigned v; sscanf(h+2*i,"%2x",&v); out[i]=(unsigned char)v; }
    return n;
}
