/* Real mainnet segwit-v0 spends through the actual block-connection dispatch
 * (tx_verify_block_connect): P2SH-P2WPKH, P2SH-P2WSH and native P2WSH across
 * m-of-n CHECKMULTISIG and HTLC-style (CLTV/CSV/OP_IF/HASH160/SHA256)
 * witnessScripts. Fixtures generated by validation/fetch_segwit_real.py from
 * the Core oracle -- every one is a tx Core accepted on mainnet, so each must
 * verify == 1 through the real dispatch. This is the coverage the synthetic
 * vectors lacked: nested/general witness scripts only reached this code after
 * the archive was re-fetched with witnesses (incident #10/#11, 2026-08-22). */
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#define _GNU_SOURCE
#include <string.h>
#include "segwit_real_vec.h"
typedef unsigned char u8; typedef unsigned long u64;
struct lsm_state {
    long log_fd, idx_fd;
    u64 log_len, ckpt_log_off, ckpt_n;
    u64 op_count, op_threshold, fill_threshold;
    void* tomb_buf; u64 tomb_cap, tomb_n, total_live, next_gen;
    void* manifest_buf; u64 manifest_cap, manifest_n;
    void* scratch_buf; u64 scratch_cap;
    u64 next_run_no;
    void* tomb_hash_buf; u64 tomb_hash_mask;
    int  bulk_mode; u64 pad2[16];
};
extern long utxo_struct_size(unsigned long);
extern void utxo_init(void*, unsigned long, void*, unsigned long);
extern long utxo_lsm_init(struct lsm_state*);
extern long utxo_lsm_put(struct lsm_state*, void*, const u8 txid[32], uint32_t index,
                         u64 value, u64 height, u64 is_coinbase, const u8* script, uint32_t slen);
extern int  tx_verify_block_connect(const u8* tx, u64 txlen, long height, const u8 bh[32],
                                    void* lst, void* u, const char** reason);
#define BLOOM_MAX_BYTES (4*1024*1024)
#define SCRIPT_MAX_BYTES 65536
/* link-only stubs (real defs live in daemon/utxo_live.c, not linked here). */
long bidx_get(void* bx, uint32_t caller_tx_index, const u8 txid[32], uint32_t index,
              u64* value, u64* height, u64* is_coinbase, const u8** script, unsigned long* slen){
  (void)bx;(void)caller_tx_index;(void)txid;(void)index;(void)value;(void)height;(void)is_coinbase;(void)script;(void)slen; return 0; }
long mempool_resolve_confirmed_utxo(void* u, const u8 txid[32], unsigned long index,
              unsigned long long* value, const u8** script, unsigned long* slen){
  (void)u;(void)txid;(void)index;(void)value;(void)script;(void)slen; return 0; }
static int hx(const char* h, u8* o){ int n=0; for(;h[0]&&h[1];h+=2,n++){unsigned v;sscanf(h,"%2x",&v);o[n]=(u8)v;} return n; }
static int fails=0, checks=0;
static void ck(const char* n,int c){ checks++; printf("%s %s\n",c?"  ok ":"  FAIL",n); if(!c)fails++; }
static struct lsm_state g_lst; static void* g_tab;
static void seed(void){
  unsigned long slots=1UL<<12; long us=utxo_struct_size(slots);
  g_tab=malloc((size_t)us); void* blob=malloc(4UL<<20); utxo_init(g_tab,slots,blob,4UL<<20);
  memset(&g_lst,0,sizeof g_lst);
  u64 op=slots*2, fill=slots*3/4, tomb=op, desc=slots*3, scr=desc*128+BLOOM_MAX_BYTES+SCRIPT_MAX_BYTES;
  g_lst.op_threshold=op; g_lst.fill_threshold=fill;
  g_lst.tomb_buf=malloc(tomb*36); g_lst.tomb_cap=tomb;
  g_lst.manifest_buf=malloc(256*16); g_lst.manifest_cap=256;
  g_lst.scratch_buf=malloc(scr); g_lst.scratch_cap=scr;
  if(utxo_lsm_init(&g_lst)!=1){fprintf(stderr,"lsm_init\n");exit(1);}
}
int main(void){
  char tmpl[]="/tmp/segrealXXXXXX"; char* d=mkdtemp(tmpl); if(!d||chdir(d)){perror("dir");return 1;}
  seed();
  static u8 tx[1<<20], spk[128];
  /* seed every prevout of every fixture */
  for(unsigned f=0; f<SR_N; f++){ const sr_fixture_t* F=&SR_FIXTURES[f];
    for(unsigned k=0;k<F->n_in;k++){ u8 tid[32],rev[32]; hx(F->prev[k].txid_hex,tid);
      for(int b=0;b<32;b++) rev[b]=tid[31-b];   /* RPC display order -> wire order (outpoint byte order) */
      memcpy(tid,rev,32);
      int sl=hx(F->prev[k].spk_hex,spk);
      if(utxo_lsm_put(&g_lst,g_tab,tid,F->prev[k].index,F->prev[k].value,0,0,spk,(uint32_t)sl)!=1){fprintf(stderr,"put\n");return 1;} } }
  u8 bh[32]={0}; char nm[160];
  for(unsigned f=0; f<SR_N; f++){ const sr_fixture_t* F=&SR_FIXTURES[f];
    int txlen=hx(F->tx_hex,tx); const char* reason="?";
    int r=tx_verify_block_connect(tx,(u64)txlen,F->height,bh,&g_lst,g_tab,&reason);
    snprintf(nm,sizeof nm,"h=%ld %s (%s)",F->height,F->name,F->note);
    ck(nm, r==1);
    if(r!=1) printf("       REASON: %s\n",reason);
  }

  /* ---- negatives: mutate the P2SH-P2WPKH fixture (index 0) ---- */
  {
    const sr_fixture_t* F=&SR_FIXTURES[0];   /* p2sh_p2wpkh_481825 */
    int txlen=hx(F->tx_hex,tx);
    u8 bh0[32]={0}; const char* rs="?";
    /* (a) flip a witness signature byte -> reject */
    /* locate target input's witness sig (wit[0]) inside tx by searching for its bytes */
    static u8 sig0[256]; int sl0=hx(F->wit_hex[0],sig0);
    u8* q=(u8*)memmem(tx,txlen,sig0,sl0);
    if(q){ q[10]^=0x01;
      ck("P2SH-P2WPKH with a corrupted witness signature is REJECTED",
         tx_verify_block_connect(tx,(u64)txlen,F->height,bh0,&g_lst,g_tab,&rs)==0);
      q[10]^=0x01; }
    /* (b) corrupt the P2SH redeemScript push in scriptSig so hash160 != program.
     * scriptSig of a P2SH-P2WPKH input is  16 00 14 <20>. Find "160014" and flip
     * a program byte -> the redeem no longer hashes to the P2SH -> reject. */
    static const u8 pat[3]={0x16,0x00,0x14};
    u8* r=(u8*)memmem(tx,txlen,pat,3);
    if(r){ r[5]^=0x01;   /* a byte of the 20-byte program */
      ck("P2SH-P2WPKH redeemScript hash mismatch is REJECTED",
         tx_verify_block_connect(tx,(u64)txlen,F->height,bh0,&g_lst,g_tab,&rs)==0);
      r[5]^=0x01; }
  }
  /* ---- negative: multisig with one bad signature (3-of-4 fixture) ---- */
  {
    const sr_fixture_t* F=&SR_FIXTURES[5];   /* p2sh_p2wsh_3of4_622000 */
    int txlen=hx(F->tx_hex,tx);
    static u8 sig0[256]; int sl0=hx(F->wit_hex[1],sig0);   /* wit[0]=dummy, wit[1]=first sig */
    u8* q=(u8*)memmem(tx,txlen,sig0,sl0);
    u8 bh0[32]={0}; const char* rs="?";
    if(q){ q[8]^=0x01;
      ck("P2SH-P2WSH 3-of-4 with one bad signature is REJECTED",
         tx_verify_block_connect(tx,(u64)txlen,F->height,bh0,&g_lst,g_tab,&rs)==0);
      q[8]^=0x01; }
  }

  printf("\n%s (%d/%d)\n", fails?"TESTS FAILED":"ALL PASS", checks-fails, checks);
  return fails?1:0;
}
