/* test_mempool_policy.c -- drive the mempool POLICY layer through the vectors
 * generated by gen_mempool_policy_vectors.py (the independent Python oracle).
 *
 * For every scenario the C harness builds a fresh policy world (pol + state +
 * structural mempool + confirmed UTXO set), preloads the scenario's funded
 * confirmed outputs, and replays the ordered steps:
 *   - "add"     : mpool_policy_add(...)  -> verdict must equal oracle's
 *   - "present" : mpool_get(txid)        -> must equal oracle's (in/out of mp)
 *   - "est"     : mpool_policy_estimate_feerate() -> must equal oracle's EMA
 *
 * The policy module under test is bitcoin_mempool_policy.c (pure C glue over
 * the verified asm mempool + asm utxo). A mismatch with the oracle is a bug.
 */
#include <stdio.h>
#include "../mempool_entry.h"
extern void mpool_policy_set_pending_sigops(unsigned long long);
extern void mpool_policy_set_bytespersigop(unsigned long long);
extern long mpool_policy_test(void*, void*, void*, const unsigned char*, unsigned long,
                              const unsigned char*, void*, unsigned long long*,
                              unsigned long long*);
extern long mpool_policy_entry_info(void*, const unsigned char*, struct mp_entry_info*);
#include <string.h>
#include <stdlib.h>
#include "mempool_policy_vec.h"

/* ---- asm structural mempool ---- */
extern size_t mpool_struct_size(unsigned long slots);
extern void   mpool_init(void* mp, unsigned long slots, void* blob, unsigned long blob_cap);
extern long   mpool_put(void* mp, const unsigned char txid[32],
                        const unsigned char* tx, unsigned long txlen);
extern const unsigned char* mpool_get(void* mp, const unsigned char txid[32],
                                      unsigned long* out_len);
extern long   mpool_count(void* mp);
/* ---- asm UTXO set ---- */
extern size_t utxo_struct_size(unsigned long slots);
extern void   utxo_init(void* u, unsigned long slots, void* blob, unsigned long blob_cap);
extern long   utxo_put(void* u, const unsigned char txid[32], unsigned long index,
                       unsigned long long value, unsigned long height,
                       unsigned long is_coinbase, const unsigned char* script, unsigned long slen);
/* ---- policy module (bitcoin_mempool_policy.c) ---- */
extern size_t mpool_policy_state_size(unsigned n);
extern void   mpool_policy_state_init(void* st, unsigned n);
extern void   mpool_policy_init(void* pol, unsigned long long relay_fee_rate,
                                unsigned max_anc, unsigned max_anc_bytes,
                                unsigned max_desc, unsigned max_desc_bytes,
                                unsigned rbf_enabled);
extern void mpool_policy_set_acceptnonstd(void*, unsigned);
extern void mpool_policy_set_cluster_limits(void*, unsigned count, unsigned vbytes);   /* -limitclustercount / -limitclustersize (2026-10-01) */
extern void mpool_policy_set_baremultisig(void*, unsigned);
static int test_bare_multisig(void);   /* defined below main */
static void test_cluster_walk_differential(void);   /* defined below main */
static void test_descendant_walk_differential(void);   /* defined below main */
extern long   mpool_policy_add(void* pol, void* st, void* mp,
                               const unsigned char* tx, unsigned long txlen,
                               const unsigned char txid[32], void* utxo);
extern unsigned long long mpool_policy_estimate_feerate(void* st);
extern const char* mpool_policy_reason(void* pol);
extern long mpool_policy_n_parents(void* st, const unsigned char txid[32]);

/* bitcoin_mempool_policy.c now calls mempool_resolve_confirmed_utxo instead
 * of utxo_get directly (see its own extern's comment) -- this harness still
 * wants the real, single-table bitcoin_utxo.asm behavior, so just pass
 * through unchanged. */
extern long utxo_get(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, unsigned long* height,
                     unsigned long* is_coinbase, const unsigned char** script,
                     unsigned long* slen);
long mempool_resolve_confirmed_utxo(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, const unsigned char** script,
                     unsigned long* slen){
    unsigned long h_unused, cb_unused;
    return utxo_get(u, txid, index, value, &h_unused, &cb_unused, script, slen);
}

static int hex_in(unsigned char* out, const char* h);

static int failures = 0;

/* ---- state buffers must be big enough, and SAY SO when they are not ----
 *
 * These buffers are fixed-size statics and mpool_policy_state_init memsets
 * the whole state, so one that is too small overflows into whatever follows
 * -- silently. This file had been doing exactly that: at n=4096 the state has
 * always needed more than the 1 MB the buffers declared (1,163,360 bytes
 * before the MEM-3/MEM-12 layout work, 1,126,240 after), so ~114 KB was being
 * written past the end on every run. Nothing visible broke until a layout
 * change moved which static landed in the overflow -- and then it was the
 * failure counter itself, which is how a passing suite reported "-1
 * failures".
 *
 * Every state_init in this file goes through this macro, so the next time a
 * layout grows past a buffer the suite fails with the two numbers rather than
 * corrupting itself. */
#define POLICY_STATE_INIT(buf, n) do { \
    size_t _need = mpool_policy_state_size((unsigned)(n)); \
    if (_need > sizeof (buf)) { \
        printf("FAIL: policy state buffer too small for n=%u: need %zu, have %zu\n", \
               (unsigned)(n), _need, sizeof (buf)); \
        failures++; \
    } else mpool_policy_state_init((buf), (unsigned)(n)); \
} while (0)
#define MAXTX 4096

static int run_scenario(int si,
                        unsigned max_anc, unsigned max_anc_bytes,
                        unsigned max_desc, unsigned max_desc_bytes,
                        unsigned rbf,
                        const char* const* utxo_txid, const unsigned* utxo_idx,
                        const unsigned long long* utxo_val, unsigned nutxo,
                        unsigned nsteps,
                        const char* const* step_tx, const char* const* step_txid,
                        const unsigned* step_kind, const unsigned* step_expect,
                        const unsigned long long* step_arg);

int main(void){
    /* ---- scenario 0: core (fee / double-spend / RBF) ---- */
    run_scenario(0, SCEN0_MAXANC, SCEN0_MAXANC_B, SCEN0_MAXDESC, SCEN0_MAXDESC_B,
                 SCEN0_RBF, SCEN0_UTXO_TXID, SCEN0_UTXO_IDX, SCEN0_UTXO_VAL, SCEN0_NUTXO,
                 SCEN0_NSTEPS, SCEN0_STEP_TX, SCEN0_STEP_TXID, SCEN0_STEP_KIND,
                 SCEN0_STEP_EXPECT, SCEN0_STEP_ARG);
    /* ---- scenario 1: ancestor limit ---- */
    run_scenario(1, SCEN1_MAXANC, SCEN1_MAXANC_B, SCEN1_MAXDESC, SCEN1_MAXDESC_B,
                 SCEN1_RBF, SCEN1_UTXO_TXID, SCEN1_UTXO_IDX, SCEN1_UTXO_VAL, SCEN1_NUTXO,
                 SCEN1_NSTEPS, SCEN1_STEP_TX, SCEN1_STEP_TXID, SCEN1_STEP_KIND,
                 SCEN1_STEP_EXPECT, SCEN1_STEP_ARG);
    /* ---- scenario 2: descendant limit ---- */
    run_scenario(2, SCEN2_MAXANC, SCEN2_MAXANC_B, SCEN2_MAXDESC, SCEN2_MAXDESC_B,
                 SCEN2_RBF, SCEN2_UTXO_TXID, SCEN2_UTXO_IDX, SCEN2_UTXO_VAL, SCEN2_NUTXO,
                 SCEN2_NSTEPS, SCEN2_STEP_TX, SCEN2_STEP_TXID, SCEN2_STEP_KIND,
                 SCEN2_STEP_EXPECT, SCEN2_STEP_ARG);
    /* ---- scenario 3: fee estimator ---- */
    run_scenario(3, SCEN3_MAXANC, SCEN3_MAXANC_B, SCEN3_MAXDESC, SCEN3_MAXDESC_B,
                 SCEN3_RBF, SCEN3_UTXO_TXID, SCEN3_UTXO_IDX, SCEN3_UTXO_VAL, SCEN3_NUTXO,
                 SCEN3_NSTEPS, SCEN3_STEP_TX, SCEN3_STEP_TXID, SCEN3_STEP_KIND,
                 SCEN3_STEP_EXPECT, SCEN3_STEP_ARG);

    failures += test_bare_multisig();

/* Evaluates the condition ONCE. It used to appear twice in the body -- once
 * for the label, once for the counter -- so any check whose condition had a
 * side effect ran it twice. A `okv(mpool_policy_add(...) == 1, ...)` then
 * submitted the transaction a second time, the duplicate was refused, and the
 * case reported "ok" while quietly incrementing the failure count. */
#define okv(c, msg) do{ int _okv = (c) ? 1 : 0; \
    printf("  %s %s\n", _okv?"ok ":"FAIL", (msg)); if(!_okv) failures++; }while(0)
    /* ---- MEM-23: the size floor binds in the PRODUCTION shape --------------
     * The harness below turns the 65-non-witness-byte floor off so its ~60-byte
     * synthetic fixtures still work. That escape hatch needs its own guard, or
     * "the floor is unconditional" would be a claim nothing checks.
     *
     * Here: -acceptnonstdtxn ON, the test knob UNTOUCHED (its default), which
     * is exactly what a node running with -acceptnonstdtxn looks like. A
     * sub-65-byte transaction must still be refused. Before this change,
     * accept_nonstd returned before the floor was ever consulted, so this
     * would have been ACCEPTED -- Core rejects it, because the floor mitigates
     * CVE-2017-12842 rather than expressing a standardness preference. */
    printf("== MEM-23: the 65-byte floor is not switched off by -acceptnonstdtxn ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);
        mpool_policy_set_acceptnonstd(pol, 1);      /* and NOT set_min_size(0) */
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        mpool_init(ux, 4096, ublob, sizeof ublob);

        /* the smallest well-formed 1-in/1-out transaction: 60 non-witness
         * bytes, i.e. under Core's floor */
        unsigned char tiny[64]; int t = 0;
        tiny[t++]=2;tiny[t++]=0;tiny[t++]=0;tiny[t++]=0;
        tiny[t++]=1; memset(tiny+t, 0x33, 32); t += 32;
        tiny[t++]=0;tiny[t++]=0;tiny[t++]=0;tiny[t++]=0;
        tiny[t++]=0;
        tiny[t++]=0xff;tiny[t++]=0xff;tiny[t++]=0xff;tiny[t++]=0xff;
        tiny[t++]=1; memset(tiny+t, 0, 8); t += 8;
        tiny[t++]=0;
        tiny[t++]=0;tiny[t++]=0;tiny[t++]=0;tiny[t++]=0;
        okv(t < 65, "MEM-23 fixture is under the 65-byte floor");

        unsigned char tid[32]; memset(tid, 0x44, 32);
        long r = mpool_policy_add(pol, stbuf, mp, tiny, (unsigned long)t, tid, ux);
        /* NOTE: `r != 1` alone does NOT discriminate -- this synthetic tx is
         * refused with the floor removed too, for an unrelated reason (its
         * prevout is not in the injected UTXO set). Verified by reverting.
         * The REASON is the assertion that matters, and it is the one that
         * fails without the fix. Keeping the weaker check as a sanity guard,
         * labelled so nobody reads it as evidence. */
        okv(r != 1, "MEM-23: refused (does not discriminate on its own -- see below)");
        okv(strstr(mpool_policy_reason(pol), "tx-size-small") != NULL,
            "MEM-23: ...and the reason is tx-size-small (THIS is the discriminating check)");
        if (strstr(mpool_policy_reason(pol), "tx-size-small") == NULL)
            printf("      reason was \"%s\" -- the floor was skipped\n", mpool_policy_reason(pol));
    }

    printf("== Core v31 cluster limits (too-large-cluster) ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);  /* anc/desc limits out of the way */
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* 64 INDEPENDENT parents (cluster of 1 each), then one child spending
         * all 64: anc_cnt 64 passes the old limits, the cluster of 65 must not */
        static unsigned char ptxid[64][32];
        unsigned char spk[2] = { 0x51, 0x00 };            /* tiny anyone-can-spend-ish */
        for (int i = 0; i < 64; i++){
            unsigned char prev[32]; memset(prev, 0x60 + (i & 15), 32); prev[0] = (unsigned char)i;
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x21+i, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            memset(ptxid[i], 0x90, 32); ptxid[i][0] = (unsigned char)i;   /* synthetic txid: the pool stores what we pass */
            long r = mpool_policy_add(pol, stbuf, mp, tx, n, ptxid[i], ux);
            if (r != 1){ printf("      parent %d rejected: %s\n", i, mpool_policy_reason(pol)); }
            if (r != 1){ okv(0, "all 64 independent parents accepted"); break; }
            if (i == 63) okv(1, "all 64 independent parents accepted");
        }
        unsigned char ctx[64*41 + 64]; unsigned long n = 0;
        ctx[n++]=2;ctx[n++]=0;ctx[n++]=0;ctx[n++]=0;
        ctx[n++]=64;
        for (int i = 0; i < 64; i++){ memcpy(ctx+n, ptxid[i], 32); n+=32; memset(ctx+n, 0, 4); n+=4; ctx[n++]=0; memset(ctx+n,0xff,4); n+=4; }
        ctx[n++]=1; { unsigned long long v = 64*900000ULL - 100000ULL; for (int b=0;b<8;b++) ctx[n++]=(unsigned char)(v>>(8*b)); }
        ctx[n++]=22; ctx[n++]=0x00; ctx[n++]=0x14; memset(ctx+n, 0x77, 20); n+=20;
        memset(ctx+n, 0, 4); n+=4;
        unsigned char ctid[32]; memset(ctid, 0x9F, 32);
        long r = mpool_policy_add(pol, stbuf, mp, ctx, n, ctid, ux);
        okv(r != 1, "a child joining 64 independent parents is refused");
        okv(r != 1 && strstr(mpool_policy_reason(pol), "too-large-cluster") != NULL, "...as too-large-cluster (anc/desc limits alone would have let it in)");
    }

    /* ================================================================
     * v31.1 accepts by CLUSTER only (2026-10-01). Its validation has no
     * "too-long-mempool-chain"; -limitancestorcount/-limitdescendantcount are
     * "deprecated ... replaced by cluster limits ... and only used by wallet
     * for coin selection", and the ancestor/descendant SIZE limits are gone.
     * This node refused the 26th transaction of a chain v31.1 accepts: 15 of
     * 35 children Core held and this node lacked were refused for exactly
     * that (BlockYard's differential, 2026-10-01). Every case below runs at
     * the OLD Core defaults (25 / 101 kvB) to show they no longer bind.
     * ================================================================ */
    printf("== v31.1: ancestor/descendant limits do not bind acceptance; cluster limits do ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        /* one input, `nout` outputs of `each` sat, 22-byte witness-v0 scripts */
        #define V31_TX(buf, n, prev, pidx, nout, each, tag) do{ \
            n = 0; buf[n++]=2;buf[n++]=0;buf[n++]=0;buf[n++]=0; \
            buf[n++]=1; memcpy(buf+n, prev, 32); n+=32; \
            for (int _b=0;_b<4;_b++) buf[n++]=(unsigned char)((unsigned)(pidx)>>(8*_b)); \
            buf[n++]=0; memset(buf+n,0xff,4); n+=4; \
            buf[n++]=(unsigned char)(nout); \
            for (int _o=0;_o<(nout);_o++){ unsigned long long _v=(each); \
                for (int _b=0;_b<8;_b++) buf[n++]=(unsigned char)(_v>>(8*_b)); \
                buf[n++]=22; buf[n++]=0x00; buf[n++]=0x14; memset(buf+n, (tag)+_o, 20); n+=20; } \
            memset(buf+n, 0, 4); n+=4; }while(0)
        unsigned char spk[2] = { 0x51, 0x00 };
        unsigned char tx[64*31 + 64]; unsigned long n;
        static unsigned char id[70][32];

        /* 1. a 64-transaction chain at the old 25/101kvB defaults: all in; the 65th is too-large-cluster */
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        { unsigned char coin[32]; memset(coin, 0xC1, 32);
          utxo_put(ux, coin, 0, 10000000ULL, 0, 0, spk, 1);
          int accepted = 0; const char* why = "";
          for (int i = 0; i < 65; i++){
              const unsigned char* prev = i ? id[i-1] : coin;
              V31_TX(tx, n, prev, 0, 1, 10000000ULL - 1000ULL*(i+1), 0x30);
              memset(id[i], 0xA0, 32); id[i][0] = (unsigned char)i; id[i][1] = 0x31;
              long r = mpool_policy_add(pol, stbuf, mp, tx, n, id[i], ux);
              if (r == 1) accepted++; else { why = mpool_policy_reason(pol); break; }
          }
          okv(accepted >= 26, "a 26-transaction chain is accepted at limitancestorcount=25 (v31.1 accepts it)");
          okv(accepted == 64, "...the whole 64-transaction chain is accepted (the cluster limit is the bound)");
          if (accepted != 64) printf("      accepted %d; stopped with \"%s\"\n", accepted, why);
          okv(accepted == 64 && strstr(why, "too-large-cluster") != NULL, "...and the 65th is refused as too-large-cluster, not too-long-mempool-chain"); }

        /* 2. one parent, 30 children: descendant count 31 > the old 25 */
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        { unsigned char coin[32]; memset(coin, 0xC2, 32);
          utxo_put(ux, coin, 0, 31000000ULL, 0, 0, spk, 1);
          V31_TX(tx, n, coin, 0, 30, 1000000ULL, 0x40);
          memset(id[0], 0xB0, 32);
          long r = mpool_policy_add(pol, stbuf, mp, tx, n, id[0], ux);
          int kids = 0; const char* why = "";
          for (int k = 0; r == 1 && k < 30; k++){
              V31_TX(tx, n, id[0], k, 1, 990000ULL, 0x60);
              memset(id[1+k], 0xB1, 32); id[1+k][0] = (unsigned char)k;
              if (mpool_policy_add(pol, stbuf, mp, tx, n, id[1+k], ux) == 1) kids++; else { why = mpool_policy_reason(pol); break; }
          }
          okv(r == 1 && kids == 30, "30 children of one parent are accepted at limitdescendantcount=25");
          if (kids != 30) printf("      parent %ld, children %d; stopped with \"%s\"\n", r, kids, why); }

        /* 3. -limitclustercount binds at the configured value */
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        mpool_policy_set_cluster_limits(pol, 10, 101000);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        { unsigned char coin[32]; memset(coin, 0xC3, 32);
          utxo_put(ux, coin, 0, 10000000ULL, 0, 0, spk, 1);
          int accepted = 0; const char* why = "";
          for (int i = 0; i < 11; i++){
              const unsigned char* prev = i ? id[i-1] : coin;
              V31_TX(tx, n, prev, 0, 1, 10000000ULL - 1000ULL*(i+1), 0x50);
              memset(id[i], 0xD0, 32); id[i][0] = (unsigned char)i;
              if (mpool_policy_add(pol, stbuf, mp, tx, n, id[i], ux) == 1) accepted++; else { why = mpool_policy_reason(pol); break; }
          }
          okv(accepted == 10 && strstr(why, "too-large-cluster") != NULL, "limitclustercount=10: a 10-chain is accepted, the 11th is too-large-cluster");
          if (accepted != 10) printf("      accepted %d; stopped with \"%s\"\n", accepted, why); }

        /* 4. -limitclustersize binds at the configured vsize (two ~82 vB transactions vs 150) */
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        mpool_policy_set_cluster_limits(pol, 64, 150);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        { unsigned char coin[32]; memset(coin, 0xC4, 32);
          utxo_put(ux, coin, 0, 10000000ULL, 0, 0, spk, 1);
          V31_TX(tx, n, coin, 0, 1, 9990000ULL, 0x70);
          memset(id[0], 0xE0, 32);
          long r1 = mpool_policy_add(pol, stbuf, mp, tx, n, id[0], ux);
          V31_TX(tx, n, id[0], 0, 1, 9980000ULL, 0x71);
          memset(id[1], 0xE1, 32);
          long r2 = mpool_policy_add(pol, stbuf, mp, tx, n, id[1], ux);
          okv(r1 == 1 && r2 != 1 && strstr(mpool_policy_reason(pol), "too-large-cluster") != NULL,
              "limitclustersize=150 vB: the second transaction of a chain is too-large-cluster");
          if (!(r1 == 1 && r2 != 1)) printf("      r1=%ld r2=%ld reason \"%s\"\n", r1, r2, mpool_policy_reason(pol)); }
        #undef V31_TX
    }

    /* ================================================================
     * v31.1 replacement rules (2026-10-01): rule 5 (100 candidates), rules
     * 3+4 (PaysForRBF), and the FEERATE-DIAGRAM check (ImprovesFeerateDiagram,
     * "replacement-failed"). No per-conflict feerate rule: that was Core's
     * PaysMoreThanConflicts, removed in v31. BlockYard's differential found 14
     * of 35 children Core held refused here as "insufficient fee" -- the shape
     * below: the replaced transaction is a high-feerate CHILD of a cheap
     * parent, so its own feerate (30) is above the replacement's (28) while
     * its CHUNK (with the parent, 15.5) is below the replacement's chunk
     * (18.2). Core compares chunks; the old rule compared the two transactions.
     * Fixtures are non-witness, so vsize == size: 1-in/1-out is 82 vB,
     * 1-in/3-out 144 vB; the relay and incremental rates are 1 sat/vB.
     * ================================================================ */
    printf("== v31.1 replacement: the feerate diagram decides, not the conflict's own feerate ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        #define RB_TX(buf, n, prev, pidx, nout, each, tag) do{ \
            n = 0; buf[n++]=2;buf[n++]=0;buf[n++]=0;buf[n++]=0; \
            buf[n++]=1; memcpy(buf+n, prev, 32); n+=32; \
            for (int _b=0;_b<4;_b++) buf[n++]=(unsigned char)((unsigned)(pidx)>>(8*_b)); \
            buf[n++]=0; memset(buf+n,0xff,4); n+=4; \
            buf[n++]=(unsigned char)(nout); \
            for (int _o=0;_o<(nout);_o++){ unsigned long long _v=(each); \
                for (int _b=0;_b<8;_b++) buf[n++]=(unsigned char)(_v>>(8*_b)); \
                buf[n++]=22; buf[n++]=0x00; buf[n++]=0x14; memset(buf+n, (tag)+_o, 20); n+=20; } \
            memset(buf+n, 0, 4); n+=4; }while(0)
        unsigned char spk[2] = { 0x51, 0x00 };
        unsigned char tx[256]; unsigned long n;
        unsigned char coin[32], idA[32], idO[32], idR[32];

        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        memset(coin, 0xF1, 32); utxo_put(ux, coin, 0, 100000ULL, 0, 0, spk, 1);
        RB_TX(tx, n, coin, 0, 1, 100000ULL - 82, 0x10);          /* A: 82 vB, 82 sat (1 sat/vB) */
        memset(idA, 0xA1, 32);
        long rA = mpool_policy_add(pol, stbuf, mp, tx, n, idA, ux);
        RB_TX(tx, n, idA, 0, 1, 99918ULL - 2460, 0x20);          /* O: 82 vB, 2460 sat (30 sat/vB) */
        memset(idO, 0xA2, 32);
        long rO = mpool_policy_add(pol, stbuf, mp, tx, n, idO, ux);
        okv(rA == 1 && rO == 1, "cheap parent A (1 sat/vB) and its 30 sat/vB child O are in");
        RB_TX(tx, n, idA, 0, 3, 31962ULL, 0x30);                 /* R: 144 vB, 4032 sat (28 sat/vB), spends A:0 like O */
        memset(idR, 0xA3, 32);
        long rR = mpool_policy_add(pol, stbuf, mp, tx, n, idR, ux);
        okv(rR == 1, "R (28 sat/vB, chunk 18.2) replaces O (30 sat/vB, chunk 15.5): the diagram improves, so v31.1 accepts it");
        if (rR != 1) printf("      refused as: %s\n", mpool_policy_reason(pol));
        unsigned long l = 0;
        okv(rR == 1 && mpool_get(mp, idO, &l) == NULL && mpool_get(mp, idR, &l) != NULL, "...O is evicted and R is in the pool");

        /* the diagram also REFUSES: a replacement at a higher own feerate that
         * pulls in a cheap unrelated parent P, worsening the top of the diagram */
        unsigned char coin2[32], coin3[32], idO2[32], idP[32], idR2[32];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        memset(coin2, 0xF2, 32); utxo_put(ux, coin2, 0, 100000ULL, 0, 0, spk, 1);
        memset(coin3, 0xF3, 32); utxo_put(ux, coin3, 0, 100000ULL, 0, 0, spk, 1);
        RB_TX(tx, n, coin2, 0, 1, 100000ULL - 820, 0x40);        /* O2: 82 vB, 820 sat (10 sat/vB) */
        memset(idO2, 0xB1, 32);
        long r1 = mpool_policy_add(pol, stbuf, mp, tx, n, idO2, ux);
        RB_TX(tx, n, coin3, 0, 1, 100000ULL - 82, 0x50);          /* P: 82 vB, 82 sat (1 sat/vB), unrelated */
        memset(idP, 0xB2, 32);
        long r2 = mpool_policy_add(pol, stbuf, mp, tx, n, idP, ux);
        okv(r1 == 1 && r2 == 1, "O2 (10 sat/vB) and an unrelated cheap P (1 sat/vB) are in");
        /* R2 conflicts with O2 (spends coin2) and spends P:0: two inputs */
        { n = 0; tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0; tx[n++]=2;
          memcpy(tx+n, coin2, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
          memcpy(tx+n, idP, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
          tx[n++]=1; { unsigned long long v = 100000ULL + 99918ULL - 1600ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
          tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x60, 20); n+=20; memset(tx+n,0,4); n+=4; }
        memset(idR2, 0xB3, 32);
        long r3 = mpool_policy_add(pol, stbuf, mp, tx, n, idR2, ux);   /* R2: 123 vB, 1600 sat (13 sat/vB) */
        okv(r3 != 1, "R2 (13 sat/vB) replacing O2 but joining cheap P is refused (its chunk with P is 8.2 sat/vB, under O2's 10)");
        okv(r3 != 1 && strstr(mpool_policy_reason(pol), "replacement-failed") != NULL, "...as replacement-failed (rules 3+4 pass)");
        if (r3 == 1 || !strstr(mpool_policy_reason(pol), "replacement-failed")) printf("      r3=%ld reason \"%s\"\n", r3, mpool_policy_reason(pol));
        okv(mpool_get(mp, idO2, &l) != NULL, "...and O2 stays in the pool");
        #undef RB_TX
    }

    /* ================================================================
     * Eviction's cluster walk (2026-10-01). worst_chunk_excl threaded every
     * parent's child list through ONE child_next slot per node, so a child
     * with two parents (C: parents A and B) was relinked into B's list and
     * A's earlier children (D) fell out of A's walk. The cluster {A,B,C,D}
     * was then scored as {A,B,C} -- without D, the CPFP child that lifts A --
     * and eviction took A and C (and D with them) instead of the genuinely
     * worst chunk X.
     *   A 113 vB  113 sat (1/vB)  two outputs, for D and C
     *   B  82 vB 1640 sat (20/vB)
     *   D  82 vB 4100 sat (50/vB) spends A:0   (inserted BEFORE C)
     *   C 123 vB 2460 sat (20/vB) spends A:1 and B:0
     *   X  82 vB 1230 sat (15/vB) unrelated
     * Correct chunks: {A,D} 21.6, B 20, C 20, X 15 -> X is the worst.
     * Without D: B 20, {A,C} 10.9 -> {A,C} looked worst.
     * The blob holds the five (482 raw bytes) and not a sixth; Y (82 vB,
     * 50/vB) must evict exactly X to fit.
     * ================================================================ */
    printf("== eviction scores the WHOLE cluster: a two-parent child does not hide a sibling ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 64*80 + 8];
        static unsigned char mblob[500];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        #define EV_TX1(buf, n, prev, pidx, nout, each, tag) do{ \
            n = 0; buf[n++]=2;buf[n++]=0;buf[n++]=0;buf[n++]=0; \
            buf[n++]=1; memcpy(buf+n, prev, 32); n+=32; \
            for (int _b=0;_b<4;_b++) buf[n++]=(unsigned char)((unsigned)(pidx)>>(8*_b)); \
            buf[n++]=0; memset(buf+n,0xff,4); n+=4; \
            buf[n++]=(unsigned char)(nout); \
            for (int _o=0;_o<(nout);_o++){ unsigned long long _v=(each); \
                for (int _b=0;_b<8;_b++) buf[n++]=(unsigned char)(_v>>(8*_b)); \
                buf[n++]=22; buf[n++]=0x00; buf[n++]=0x14; memset(buf+n, (tag)+_o, 20); n+=20; } \
            memset(buf+n, 0, 4); n+=4; }while(0)
        unsigned char spk[2] = { 0x51, 0x00 };
        unsigned char tx[256]; unsigned long n;
        unsigned char cA[32], cB[32], cX[32], cY[32], idA[32], idB[32], idC[32], idD[32], idX[32], idY[32];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 64);
        mpool_init(mp, 64, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        memset(cA, 0xE1, 32); memset(cB, 0xE2, 32); memset(cX, 0xE3, 32); memset(cY, 0xE4, 32);
        utxo_put(ux, cA, 0, 1000000ULL, 0, 0, spk, 1); utxo_put(ux, cB, 0, 1000000ULL, 0, 0, spk, 1);
        utxo_put(ux, cX, 0, 1000000ULL, 0, 0, spk, 1); utxo_put(ux, cY, 0, 1000000ULL, 0, 0, spk, 1);
        long r[6]; unsigned long sz[6];
        EV_TX1(tx, n, cA, 0, 2, (1000000ULL - 113) / 2, 0x10); sz[0] = n;      /* A: 113 vB; (1000000-113)/2 = 499943 each, fee 114 */
        memset(idA, 0xA1, 32); r[0] = mpool_policy_add(pol, stbuf, mp, tx, n, idA, ux);
        EV_TX1(tx, n, cB, 0, 1, 1000000ULL - 1640, 0x20); sz[1] = n;            /* B */
        memset(idB, 0xB1, 32); r[1] = mpool_policy_add(pol, stbuf, mp, tx, n, idB, ux);
        EV_TX1(tx, n, idA, 0, 1, 499943ULL - 4100, 0x30); sz[2] = n;            /* D: spends A:0 */
        memset(idD, 0xD1, 32); r[2] = mpool_policy_add(pol, stbuf, mp, tx, n, idD, ux);
        { n = 0; tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0; tx[n++]=2;                  /* C: spends A:1 and B:0 */
          memcpy(tx+n, idA, 32); n+=32; tx[n++]=1; tx[n++]=0; tx[n++]=0; tx[n++]=0; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
          memcpy(tx+n, idB, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
          tx[n++]=1; { unsigned long long v = 499943ULL + (1000000ULL - 1640) - 2460; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
          tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x40, 20); n+=20; memset(tx+n,0,4); n+=4; }
        sz[3] = n; memset(idC, 0xC1, 32); r[3] = mpool_policy_add(pol, stbuf, mp, tx, n, idC, ux);
        EV_TX1(tx, n, cX, 0, 1, 1000000ULL - 1230, 0x50); sz[4] = n;            /* X */
        memset(idX, 0xF1, 32); r[4] = mpool_policy_add(pol, stbuf, mp, tx, n, idX, ux);
        okv(r[0]==1 && r[1]==1 && r[2]==1 && r[3]==1 && r[4]==1, "A, B, D (child of A), C (child of A and B) and X are in");
        if (!(r[0]==1 && r[1]==1 && r[2]==1 && r[3]==1 && r[4]==1)) printf("      r = %ld %ld %ld %ld %ld (%s)\n", r[0], r[1], r[2], r[3], r[4], mpool_policy_reason(pol));
        printf("      sizes %lu %lu %lu %lu %lu = %lu raw bytes in a %zu-byte blob\n", sz[0], sz[1], sz[2], sz[3], sz[4],
               sz[0]+sz[1]+sz[2]+sz[3]+sz[4], sizeof mblob);
        EV_TX1(tx, n, cY, 0, 1, 1000000ULL - 4100, 0x60);                        /* Y: 82 vB at 50/vB, needs room */
        memset(idY, 0xF2, 32); r[5] = mpool_policy_add(pol, stbuf, mp, tx, n, idY, ux);
        unsigned long l = 0;
        okv(r[5] == 1, "Y (50 sat/vB) is accepted, evicting to fit");
        if (r[5] != 1) printf("      refused as: %s\n", mpool_policy_reason(pol));
        okv(mpool_get(mp, idX, &l) == NULL, "X (15 sat/vB, the worst chunk) is the one evicted");
        okv(mpool_get(mp, idA, &l) != NULL && mpool_get(mp, idC, &l) != NULL && mpool_get(mp, idD, &l) != NULL && mpool_get(mp, idB, &l) != NULL,
            "A, B, C and D all stay (their cluster's worst chunk is C at 20, not {A,C} at 10.9)");
        #undef EV_TX1
    }
    /* ================================================================
     * MEM-3 (audit 2026-09-03): the parent list is no longer truncated.
     *
     * MPOL_MAX_PARENTS was 24 and mpol_collect_parents dropped everything
     * past it SILENTLY. parent[] is the only record of the graph --
     * descendants are found by walking it -- so a dropped parent did not
     * exist as far as eviction, expiry and RBF were concerned. The audit's
     * scenario: 30 low-feerate parents and a child spending all 30; the child
     * is stored linked to 24; RBF-replace the 30th (your own coin) and
     * collect_descendant_txids finds no child, so the child stays in the pool
     * spending an output the replacement has conflicted -- and
     * getblocktemplate includes it, because every REGISTERED ancestor is
     * present. An invalid block.
     *
     * 30 parents is the shape that matters: comfortably past the old cap of
     * 24, comfortably inside the 63 that v31's 64-transaction cluster limit
     * allows, so it must be ACCEPTED and fully linked.
     * ================================================================ */
    /* ================================================================
     * package RBF (2026-10-01): Core v31.1 MemPoolAccept::PackageRBFChecks.
     * A (10 sat/vB) is in the pool; P conflicts with A paying 1 sat/vB, so it
     * cannot replace A alone; C, P's child, pays 30 sat/vB. Together they
     * replace A: 2542 sat over 164 vB pays A's 820 plus the 164-sat increment,
     * out-pays P (15.5 > 1 sat/vB) and improves the diagram. Non-witness
     * fixtures (82 vB each); relay and incremental rates are 1 sat/vB.
     * ================================================================ */
    printf("== package RBF: a parent that cannot replace alone replaces with its child ==\n");
    {
        extern int mpol_package_rbf_check(void*, void*, const unsigned char* const*, const unsigned long*,
                                          const unsigned char*, int, unsigned long long, unsigned long long,
                                          unsigned long long, unsigned long long, char*, unsigned long);
        extern void mpol_package_fee_context(unsigned long long, unsigned long long);
        extern void mpol_package_rbf_context(int);
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        #define PR_TX(buf, n, prev, val, tag) do{ \
            n = 0; buf[n++]=2;buf[n++]=0;buf[n++]=0;buf[n++]=0; \
            buf[n++]=1; memcpy(buf+n, prev, 32); n+=32; memset(buf+n,0,4); n+=4; \
            buf[n++]=0; memset(buf+n,0xff,4); n+=4; buf[n++]=1; \
            { unsigned long long _v=(val); for (int _b=0;_b<8;_b++) buf[n++]=(unsigned char)(_v>>(8*_b)); } \
            buf[n++]=22; buf[n++]=0x00; buf[n++]=0x14; memset(buf+n, (tag), 20); n+=20; \
            memset(buf+n, 0, 4); n+=4; }while(0)
        unsigned char spk[2] = { 0x51, 0x00 };
        static unsigned char ta[256], tp[256], tc[256]; unsigned long na, np, nc;
        unsigned char coin[32], idA[32], ids[64];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        memset(coin, 0xF4, 32); utxo_put(ux, coin, 0, 100000ULL, 0, 0, spk, 1);
        PR_TX(ta, na, coin, 100000ULL - 820, 0x70);              /* A: 820 sat, 10 sat/vB */
        memset(idA, 0xC1, 32);
        okv(mpool_policy_add(pol, stbuf, mp, ta, na, idA, ux) == 1, "A (10 sat/vB) is in the pool");
        memset(ids, 0xC2, 32); memset(ids + 32, 0xC3, 32);       /* P's and C's txids */
        PR_TX(tp, np, coin, 100000ULL - 82, 0x71);               /* P: conflicts with A, 82 sat */
        PR_TX(tc, nc, ids, 100000ULL - 82 - 2460, 0x72);         /* C: spends P:0, 2460 sat */
        const unsigned char* txs[2] = { tp, tc }; unsigned long lens[2] = { np, nc };
        char why[320];
        long rp = mpool_policy_test(pol, stbuf, mp, tp, np, ids, ux, NULL, NULL);
        okv(rp != 1 && !strcmp(mpool_policy_reason(pol), "insufficient fee"), "P alone cannot replace A (insufficient fee)");
        int r = mpol_package_rbf_check(pol, stbuf, txs, lens, ids, 2, 2542, 164, 82, 82, why, sizeof why);
        okv(r == 1, "P + C pass PackageRBFChecks (2542 sat / 164 vB against A's 820)");
        if (r != 1) printf("      r=%d why=\"%s\"\n", r, why);
        /* Core's messages, word for word */
        r = mpol_package_rbf_check(pol, stbuf, txs, lens, ids, 2, 500, 164, 82, 82, why, sizeof why);
        okv(r == 0 && !strcmp(why, "package RBF failed: insufficient anti-DoS fees, rejecting replacement "
                                    "c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3c3, "
                                    "less fees than conflicting txs; 0.000005 < 0.0000082"),
            "under A's fee: Core's 'less fees than conflicting txs' (FormatMoney amounts, the child's txid)");
        if (r != 0) printf("      r=%d\n", r); else if (strstr(why, "less fees") == NULL || strstr(why, "0.000005 <") == NULL) printf("      why=\"%s\"\n", why);
        r = mpol_package_rbf_check(pol, stbuf, txs, lens, ids, 2, 900, 164, 82, 82, why, sizeof why);
        okv(r == 0 && strstr(why, "not enough additional fees to relay; 0.0000008 < 0.00000164") != NULL,
            "over A's fee but under the 164-sat increment: 'not enough additional fees to relay'");
        r = mpol_package_rbf_check(pol, stbuf, txs, lens, ids, 2, 1000, 164, 1100, 82, why, sizeof why);
        okv(r == 0 && !strcmp(why, "package RBF failed: package feerate is less than or equal to parent feerate, "
                                    "package feerate 0.00006097 BTC/kvB <= parent feerate is 0.00013414 BTC/kvB"),
            "a child paying only the anti-DoS fee: 'package feerate is less than or equal to parent feerate'");
        r = mpol_package_rbf_check(pol, stbuf, txs, lens, ids, 1, 82, 82, 82, 82, why, sizeof why);
        okv(r == 0 && !strcmp(why, "package RBF failed: package must be 1-parent-1-child"), "a conflicting package of one: not 1-parent-1-child");
        r = mpol_package_rbf_check(pol, stbuf, txs + 1, lens + 1, ids + 32, 1, 2460, 82, 2460, 82, why, sizeof why);
        okv(r == -1, "no member conflicts with the pool: no package RBF (-1)");
        /* the commit side: under the package context P replaces A */
        mpol_package_fee_context(2542, 164);
        mpol_package_rbf_context(1);
        long cp = mpool_policy_add(pol, stbuf, mp, tp, np, ids, ux);
        long cc = mpool_policy_add(pol, stbuf, mp, tc, nc, ids + 32, ux);
        mpol_package_rbf_context(0);
        mpol_package_fee_context(0, 0);
        unsigned long l = 0;
        okv(cp == 1 && cc == 1, "under the package context P and C are admitted");
        if (cp != 1 || cc != 1) printf("      cp=%ld cc=%ld reason \"%s\"\n", cp, cc, mpool_policy_reason(pol));
        okv(mpool_get(mp, idA, &l) == NULL, "...and A is evicted");
        #undef PR_TX
    }
    /* ================================================================
     * v31.1's replacement limit counts CLUSTERS (2026-10-02): Core's
     * GetEntriesForConflicts refuses more than 100 distinct clusters among
     * the direct conflicts; the evicted set itself is bounded only by the
     * cluster size. bmc applied the 100 to evicted ENTRIES. Two coins, each
     * spent by a 61-transaction chain (two clusters, 122 entries), are
     * replaced by one transaction spending both coins: Core accepts it.
     * Non-witness 82 vB fixtures at 1 sat/vB, so the chains hold 10004 sat.
     * ================================================================ */
    printf("== replacement limit: 100 conflicting clusters, not 100 evicted entries ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<22];
        static unsigned char mp[40 + 8192*80 + 8];
        static unsigned char mblob[1<<21];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        #define CL_TX(buf, n, prev, val, tag) do{ \
            n = 0; buf[n++]=2;buf[n++]=0;buf[n++]=0;buf[n++]=0; \
            buf[n++]=1; memcpy(buf+n, prev, 32); n+=32; memset(buf+n,0,4); n+=4; \
            buf[n++]=0; memset(buf+n,0xff,4); n+=4; buf[n++]=1; \
            { unsigned long long _v=(val); for (int _b=0;_b<8;_b++) buf[n++]=(unsigned char)(_v>>(8*_b)); } \
            buf[n++]=22; buf[n++]=0x00; buf[n++]=0x14; memset(buf+n, (tag), 20); n+=20; \
            memset(buf+n, 0, 4); n+=4; }while(0)
        unsigned char spk[2] = { 0x51, 0x00 };
        unsigned char tx[256]; unsigned long n;
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 8192);
        mpool_init(mp, 8192, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char coin[2][32]; memset(coin[0], 0xE1, 32); memset(coin[1], 0xE2, 32);
        static unsigned char ids[2][61][32];
        int all_in = 1;
        for (int c = 0; c < 2; c++){
            utxo_put(ux, coin[c], 0, 1000000ULL, 0, 0, spk, 1);
            unsigned long long val = 1000000ULL;
            for (int k = 0; k < 61; k++){
                val -= 82;
                CL_TX(tx, n, k == 0 ? coin[c] : ids[c][k-1], val, 0x80 + c);
                memset(ids[c][k], 0, 32); ids[c][k][0] = 0xD0 + c; ids[c][k][1] = (unsigned char)k; ids[c][k][31] = 0x5A;
                if (mpool_policy_add(pol, stbuf, mp, tx, n, ids[c][k], ux) != 1){
                    all_in = 0; printf("      chain %d tx %d refused: %s\n", c, k, mpool_policy_reason(pol)); break; }
            }
        }
        okv(all_in, "two 61-transaction chains are in the pool (two clusters, 122 entries)");
        /* R spends both coins: conflicts with both chain heads, evicts all 122 */
        { n = 0; tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0; tx[n++]=2;
          for (int c = 0; c < 2; c++){ memcpy(tx+n, coin[c], 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4; }
          tx[n++]=1; { unsigned long long v = 2000000ULL - 20000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
          tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x90, 20); n+=20; memset(tx+n,0,4); n+=4; }
        unsigned char idR[32]; memset(idR, 0xEF, 32);
        long r = mpool_policy_add(pol, stbuf, mp, tx, n, idR, ux);
        okv(r == 1, "R replaces 122 entries in 2 clusters (Core: 2 <= 100 clusters)");
        if (r != 1) printf("      refused as: %s\n", mpool_policy_reason(pol));
        unsigned long l = 0;
        okv(r == 1 && mpool_get(mp, ids[0][60], &l) == NULL && mpool_get(mp, ids[1][0], &l) == NULL,
            "...and both chains are evicted, tips included");
        #undef CL_TX
    }
    printf("== MEM-3: a 30-parent child keeps every parent link ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);

        enum { NP = 30 };
        static unsigned char ptxid[NP][32];
        unsigned char spk[2] = { 0x51, 0x00 };
        int all_ok = 1;
        for (int i = 0; i < NP; i++){
            unsigned char prev[32]; memset(prev, 0xC0 + (i & 15), 32); prev[0] = (unsigned char)i;
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0;
            tx[n]=1; tx[n+1]=0; tx[n+2]=0; tx[n+3]=0; n+=4;      /* seq 1: replaceable */
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x41+i, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            memset(ptxid[i], 0xD0, 32); ptxid[i][0] = (unsigned char)i;
            if (mpool_policy_add(pol, stbuf, mp, tx, n, ptxid[i], ux) != 1) all_ok = 0;
        }
        okv(all_ok, "MEM-3 30 independent parents accepted");

        static unsigned char ctx[NP*41 + 64]; unsigned long n = 0;
        ctx[n++]=2;ctx[n++]=0;ctx[n++]=0;ctx[n++]=0;
        ctx[n++]=NP;
        for (int i = 0; i < NP; i++){ memcpy(ctx+n, ptxid[i], 32); n+=32; memset(ctx+n, 0, 4); n+=4; ctx[n++]=0;
            memset(ctx+n,0xff,4); n+=4; }
        ctx[n++]=1; { unsigned long long v = (unsigned long long)NP*900000ULL - 50000ULL;
                      for (int b=0;b<8;b++) ctx[n++]=(unsigned char)(v>>(8*b)); }
        ctx[n++]=22; ctx[n++]=0x00; ctx[n++]=0x14; memset(ctx+n, 0x79, 20); n+=20;
        memset(ctx+n, 0, 4); n+=4;
        unsigned char ctid[32]; memset(ctid, 0xDF, 32);
        { long rC = mpool_policy_add(pol, stbuf, mp, ctx, n, ctid, ux);
          okv(rC == 1, "MEM-3 the 30-parent child is accepted"); }

        /* THE ASSERTION THAT MATTERS. Every parent must be recorded, so the
         * pool must report 30 -- with the old inline cap it reported 24 and
         * the six beyond it were invisible to every descendant walk. */
        { long np = mpool_policy_n_parents(stbuf, ctid);
          printf("      (child reports %ld parents; 30 expected, old cap was 24)\n", np);
          okv(np == NP, "MEM-3 the child records ALL 30 parents, not 24"); }

        /* And the consequence: replacing the LAST parent -- the one the old
         * cap dropped -- must take the child with it. Under the truncation
         * the child survived, spending an output that no longer existed. */
        {
            unsigned char prev[32]; memset(prev, 0xC0 + ((NP-1) & 15), 32); prev[0] = (unsigned char)(NP-1);
            unsigned char rtx[128]; unsigned long m = 0;
            rtx[m++]=2;rtx[m++]=0;rtx[m++]=0;rtx[m++]=0;
            rtx[m++]=1; memcpy(rtx+m, prev, 32); m+=32; memset(rtx+m, 0, 4); m+=4; rtx[m++]=0; memset(rtx+m,0xff,4); m+=4;
            rtx[m++]=1; { unsigned long long v = 500000ULL; for (int b=0;b<8;b++) rtx[m++]=(unsigned char)(v>>(8*b)); }
            rtx[m++]=22; rtx[m++]=0x00; rtx[m++]=0x14; memset(rtx+m, 0x7A, 20); m+=20;
            memset(rtx+m, 0, 4); m+=4;
            unsigned char rtid[32]; memset(rtid, 0xEE, 32);
            long rr = mpool_policy_add(pol, stbuf, mp, rtx, m, rtid, ux);
            printf("      (replacement of parent %d -> %ld %s)\n", NP-1, rr,
                   rr == 1 ? "accepted" : mpool_policy_reason(pol));
            okv(rr == 1, "MEM-3 a replacement of the LAST parent is accepted");
            unsigned long l;
            okv(mpool_get(mp, ptxid[NP-1], &l) == NULL,
                "MEM-3 ...the replaced parent is gone");
            okv(mpool_get(mp, ctid, &l) == NULL,
                "MEM-3 ...and the child went WITH it (the link was recorded)");
        }
    }

    printf("== cluster limit is measured POST-eviction for a replacement ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);
        POLICY_STATE_INIT(stbuf, 4096);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* 63 independent parents, one child C spending all of them: a
         * cluster of exactly 64, at the limit */
        static unsigned char ptxid[63][32];
        unsigned char spk[2] = { 0x51, 0x00 };
        int all_ok = 1;
        for (int i = 0; i < 63; i++){
            unsigned char prev[32]; memset(prev, 0xA0 + (i & 15), 32); prev[0] = (unsigned char)i;
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x31+i, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            memset(ptxid[i], 0xB0, 32); ptxid[i][0] = (unsigned char)i;
            if (mpool_policy_add(pol, stbuf, mp, tx, n, ptxid[i], ux) != 1) all_ok = 0;
        }
        okv(all_ok, "63 independent parents accepted");
        static unsigned char ctx[63*41 + 64]; unsigned long n = 0;
        ctx[n++]=2;ctx[n++]=0;ctx[n++]=0;ctx[n++]=0;
        ctx[n++]=63;
        for (int i = 0; i < 63; i++){ memcpy(ctx+n, ptxid[i], 32); n+=32; memset(ctx+n, 0, 4); n+=4; ctx[n++]=0;
            ctx[n]=1; ctx[n+1]=0; ctx[n+2]=0; ctx[n+3]=0; n+=4; }        /* sequence 1: BIP125 signaling */
        ctx[n++]=1; { unsigned long long v = 63*900000ULL - 50000ULL; for (int b=0;b<8;b++) ctx[n++]=(unsigned char)(v>>(8*b)); }
        ctx[n++]=22; ctx[n++]=0x00; ctx[n++]=0x14; memset(ctx+n, 0x78, 20); n+=20;
        memset(ctx+n, 0, 4); n+=4;
        unsigned char ctid[32]; memset(ctid, 0xBF, 32);
        { long rC = mpool_policy_add(pol, stbuf, mp, ctx, n, ctid, ux);   /* okv double-evaluates: never call inside it */
          okv(rC == 1, "child C joins them: cluster of exactly 64 accepted"); }
        /* C' double-spends one of C's inputs -> conflicts with C, evicting
         * it. The cluster C' joins is parent[0] ALONE once C is gone; the
         * old walk still counted C and the 62 parents behind it and refused
         * a replacement that was thinning the very cluster it joined. */
        unsigned char rtx[128]; n = 0;
        rtx[n++]=2;rtx[n++]=0;rtx[n++]=0;rtx[n++]=0;
        rtx[n++]=1; memcpy(rtx+n, ptxid[0], 32); n+=32; memset(rtx+n, 0, 4); n+=4; rtx[n++]=0;
        rtx[n]=1; rtx[n+1]=0; rtx[n+2]=0; rtx[n+3]=0; n+=4;
        rtx[n++]=1; { unsigned long long v = 100000ULL; for (int b=0;b<8;b++) rtx[n++]=(unsigned char)(v>>(8*b)); }
        rtx[n++]=22; rtx[n++]=0x00; rtx[n++]=0x14; memset(rtx+n, 0x79, 20); n+=20;
        memset(rtx+n, 0, 4); n+=4;
        unsigned char rtid[32]; memset(rtid, 0xC5, 32);
        long r = mpool_policy_add(pol, stbuf, mp, rtx, n, rtid, ux);
        if (r != 1) printf("      replacement rejected: %s\n", mpool_policy_reason(pol));
        okv(r == 1, "replacement is measured against the POST-eviction cluster");
    }
    printf("== bytespersigop: sigop-dense feerate (Core DEFAULT_BYTES_PER_SIGOP 20) ==\n");
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);   /* 1 sat/vB floor */
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0x7A, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
        unsigned char tx[128]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
        tx[n++]=1; { unsigned long long v = 1000000ULL - 200ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
        tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x88, 20); n+=20;
        memset(tx+n, 0, 4); n+=4;                                   /* ~60 vB paying 200 sat: 3.3 sat/vB */
        unsigned char tid[32]; memset(tid, 0x7B, 32);
        mpool_policy_set_pending_sigops(80);                        /* 80 x4-units -> eff vsize max(60, 400) = 400 -> 0.5 sat/vB */
        long r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
        okv(r != 1 && strstr(mpool_policy_reason(pol), "min relay fee") != NULL,
           "sigop-dense: fee judged against max(vsize, sigops*5) and refused");
        mpool_policy_set_pending_sigops(0);
        r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
        okv(r == 1, "the same tx without the sigop load is fine at 3.3 sat/vB");

        /* The adjustment is the ENTRY's size, not a number used once at the
         * fee gate: Core's GetTxSize() is the sigop-adjusted vsize, so the
         * chain-limit budgets, replacement arithmetic, eviction and
         * getmempoolentry all see it. Read it back off the accepted entry. */
        {   struct mp_entry_info ei;
            okv(mpool_policy_entry_info(stbuf, tid, &ei) == 1, "entry readable");
            okv(ei.size > 0 && ei.size < 200, "a sigop-free entry keeps its BIP141 vsize");
            unsigned long long plain = ei.size;

            /* same transaction, now carrying sigops and paying enough to get
             * in: its recorded size must be the ADJUSTED one */
            memset(stbuf, 0, sizeof stbuf);
            POLICY_STATE_INIT(stbuf, 256);
            mpool_init(mp, 4096, mblob, sizeof mblob);
            utxo_init(ux, 4096, ublob, sizeof ublob);
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx2[128]; unsigned long n2 = 0;
            tx2[n2++]=2;tx2[n2++]=0;tx2[n2++]=0;tx2[n2++]=0;
            tx2[n2++]=1; memcpy(tx2+n2, prev, 32); n2+=32; memset(tx2+n2,0,4); n2+=4; tx2[n2++]=0; memset(tx2+n2,0xff,4); n2+=4;
            tx2[n2++]=1; { unsigned long long v = 1000000ULL - 5000ULL; for (int b=0;b<8;b++) tx2[n2++]=(unsigned char)(v>>(8*b)); }
            tx2[n2++]=22; tx2[n2++]=0x00; tx2[n2++]=0x14; memset(tx2+n2,0x88,20); n2+=20;
            memset(tx2+n2,0,4); n2+=4;                       /* 5000 sat: clears 400 vB at 1 sat/vB */
            unsigned char tid2[32]; memset(tid2, 0x7C, 32);
            mpool_policy_set_pending_sigops(80);
            okv(mpool_policy_add(pol, stbuf, mp, tx2, n2, tid2, ux) == 1,
               "sigop-dense tx paying the adjusted price is accepted");
            okv(mpool_policy_entry_info(stbuf, tid2, &ei) == 1, "its entry is readable");
            okv(ei.size == 400, "the ENTRY records the sigop-adjusted vsize (80*20/4 = 400)");
            okv(ei.size > plain, "...which is larger than the BIP141 vsize it would have had");
        }
    }

    /* A rejected transaction must not price the next one. The count is parked
     * in a global by the caller before the call; there are rejection paths
     * between the top of mpol_accept and the fee gate, and one of them used to
     * leave the count parked for whatever came next. */
    {   printf("\n== a rejected tx does not leave its sigop count behind ==\n");
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0x9A, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);

        /* (1) a heavy sigop load parked, on a tx that dies EARLY -- it spends
         * an input that does not exist, which is refused well before the fee
         * gate where the count used to be cleared. */
        unsigned char miss[32]; memset(miss, 0xDD, 32);
        unsigned char bad[128]; unsigned long bn = 0;
        bad[bn++]=2;bad[bn++]=0;bad[bn++]=0;bad[bn++]=0;
        bad[bn++]=1; memcpy(bad+bn, miss, 32); bn+=32; memset(bad+bn,0,4); bn+=4; bad[bn++]=0; memset(bad+bn,0xff,4); bn+=4;
        bad[bn++]=1; { unsigned long long v = 1000ULL; for (int b=0;b<8;b++) bad[bn++]=(unsigned char)(v>>(8*b)); }
        bad[bn++]=22; bad[bn++]=0x00; bad[bn++]=0x14; memset(bad+bn,0x77,20); bn+=20;
        memset(bad+bn,0,4); bn+=4;
        unsigned char bid[32]; memset(bid, 0x9B, 32);
        mpool_policy_set_pending_sigops(4000);          /* 4000*20/4 = 20000 vB if it ever applied */
        okv(mpool_policy_add(pol, stbuf, mp, bad, bn, bid, ux) != 1,
           "the sigop-laden tx is rejected before the fee gate");

        /* (2) now an ordinary, sigop-FREE transaction, with nothing parked.
         * It pays 200 sat on ~60 vB, comfortably over the 1 sat/vB floor --
         * unless it inherits the 4000 sigops from the corpse above, which
         * would price it at 20000 vB and refuse it. */
        unsigned char ok2[128]; unsigned long on = 0;
        ok2[on++]=2;ok2[on++]=0;ok2[on++]=0;ok2[on++]=0;
        ok2[on++]=1; memcpy(ok2+on, prev, 32); on+=32; memset(ok2+on,0,4); on+=4; ok2[on++]=0; memset(ok2+on,0xff,4); on+=4;
        ok2[on++]=1; { unsigned long long v = 1000000ULL - 200ULL; for (int b=0;b<8;b++) ok2[on++]=(unsigned char)(v>>(8*b)); }
        ok2[on++]=22; ok2[on++]=0x00; ok2[on++]=0x14; memset(ok2+on,0x66,20); on+=20;
        memset(ok2+on,0,4); on+=4;
        unsigned char oid[32]; memset(oid, 0x9C, 32);
        long rr = mpool_policy_add(pol, stbuf, mp, ok2, on, oid, ux);
        okv(rr == 1, "the NEXT tx is judged on its own sigops, not the dead one's");
        if (rr != 1) printf("     (reason: %s)\n", mpool_policy_reason(pol));
    }

    /* Core takes the max on the WEIGHT scale and rounds once, at the end:
     * ceil(max(weight, sigops*bytespersigop) / 4). Rounding first and taking
     * the max after loses a byte whenever sigops*bytespersigop is not a
     * multiple of 4 -- invisible at the default bytespersigop of 20, which is
     * itself a multiple of 4, so this uses a value that is not. */
    {   printf("\n== the adjustment rounds the way Core rounds ==\n");
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0xB1, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
        unsigned char tx[128]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
        tx[n++]=1; { unsigned long long v = 1000000ULL - 90000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
        tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n,0x55,20); n+=20;
        memset(tx+n,0,4); n+=4;
        unsigned char tid[32]; memset(tid, 0xB2, 32);
        mpool_policy_set_bytespersigop(5);
        mpool_policy_set_pending_sigops(1001);   /* 1001*5 = 5005 weight units */
        okv(mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux) == 1, "accepted");
        {   struct mp_entry_info ei;
            okv(mpool_policy_entry_info(stbuf, tid, &ei) == 1, "entry readable");
            /* ceil(5005/4) = 1252, not 5005/4 = 1251 */
            okv(ei.size == 1252, "ceil(max(weight, sigops*bps)/4) -- 1252, not the truncated 1251");
        }
        mpool_policy_set_bytespersigop(20);      /* back to Core's default */
    }

    /* The package feerate is aggregated by daemon/main.c and tx_relay.c from
     * what the DRY RUN reports, and Core computes it over entry sizes -- which
     * are the sigop-adjusted ones. The structural walker that hands those
     * callers a vsize cannot count sigops (they need the UTXO view), so the
     * adjusted figure has to come back out of the policy layer. This is that
     * contract: mpool_policy_test reports it, and reports it even when the
     * transaction is REJECTED on fee, because a fee-reconsiderable member
     * still contributes its size to the package total. */
    {   printf("\n== the dry run reports the sigop-adjusted vsize ==\n");
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        unsigned char prev[32]; memset(prev, 0xC1, 32);
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, (const unsigned char*)"\x51", 1);
        unsigned char tx[128]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n,0,4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
        tx[n++]=1; { unsigned long long v = 1000000ULL - 200ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
        tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n,0x33,20); n+=20;
        memset(tx+n,0,4); n+=4;                     /* ~60 vB paying 200 sat */
        unsigned char tid[32]; memset(tid, 0xC2, 32);

        unsigned long long fee = 0, avs = 0;
        mpool_policy_set_pending_sigops(80);        /* 80*20/4 = 400 vB */
        long rv = mpool_policy_test(pol, stbuf, mp, tx, n, tid, ux, &fee, &avs);
        okv(rv != 1, "200 sat over the adjusted 400 vB is under the 1 sat/vB floor");
        okv(avs == 400, "the dry run still reports the ADJUSTED vsize on a fee rejection");

        /* and on an accept, with enough fee to clear 400 vB */
        unsigned char tx2[128]; unsigned long n2 = 0;
        tx2[n2++]=2;tx2[n2++]=0;tx2[n2++]=0;tx2[n2++]=0;
        tx2[n2++]=1; memcpy(tx2+n2, prev, 32); n2+=32; memset(tx2+n2,0,4); n2+=4; tx2[n2++]=0; memset(tx2+n2,0xff,4); n2+=4;
        tx2[n2++]=1; { unsigned long long v = 1000000ULL - 5000ULL; for (int b=0;b<8;b++) tx2[n2++]=(unsigned char)(v>>(8*b)); }
        tx2[n2++]=22; tx2[n2++]=0x00; tx2[n2++]=0x14; memset(tx2+n2,0x44,20); n2+=20;
        memset(tx2+n2,0,4); n2+=4;
        unsigned char tid2[32]; memset(tid2, 0xC3, 32);
        fee = 0; avs = 0;
        mpool_policy_set_pending_sigops(80);
        long rv2 = mpool_policy_test(pol, stbuf, mp, tx2, n2, tid2, ux, &fee, &avs);
        okv(rv2 == 1, "the better-paying one passes the dry run");
        okv(avs == 400, "...and reports the adjusted vsize too");
        okv(fee == 5000, "...with its fee");

        /* no sigops parked: the plain BIP141 vsize comes back */
        fee = 0; avs = 0;
        long rv3 = mpool_policy_test(pol, stbuf, mp, tx2, n2, tid2, ux, &fee, &avs);
        okv(rv3 == 1, "sigop-free dry run passes");
        okv(avs > 0 && avs < 200, "...and reports the plain vsize when nothing is parked");
    }

    printf("== MEM-15: a v0 witness program of the wrong length is NONSTANDARD ==\n");
    /* classify_spk's "other witness programs" arm accepted version 0 at any
     * program length 2..40. Core's Solver accepts v0 ONLY at 20 or 32 bytes
     * (both matched earlier in the function) and returns NONSTANDARD
     * otherwise. Wrong twice over: such an output is consensus-UNSPENDABLE, so
     * relaying it only adds permanent UTXO bloat -- and SPK_WITNESS_UNKNOWN
     * earns the WITNESS dust discount, so it was also CHEAPER to create than
     * Core permits.
     *
     * Versions 1..16 are the control's other half: those are genuinely
     * upgrade-reserved, Core relays them, and they must stay standard. */
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        mpool_policy_set_pending_sigops(0);
        unsigned char prev[32]; memset(prev, 0x5E, 32);
        unsigned char spk1[2] = { 0x51, 0x00 };
        struct { int ver; int plen; int want_ok; const char* what; } V[] = {
            { 0x00, 30, 0, "v0 with a 30-byte program (Core: NONSTANDARD)" },
            { 0x00,  2, 0, "v0 with a 2-byte program (Core: NONSTANDARD)" },
            { 0x52, 30, 1, "v2 with a 30-byte program (upgrade-reserved, relayed)" },
            { 0x60, 40, 1, "v16 with a 40-byte program (upgrade-reserved, relayed)" },
        };
        for (unsigned vi = 0; vi < sizeof V / sizeof V[0]; vi++){
            memset(stbuf, 0, sizeof stbuf);
            mpool_policy_init(pol, 1000, 25, 101000, 25, 101000, 1);
            POLICY_STATE_INIT(stbuf, 256);
            mpool_init(mp, 4096, mblob, sizeof mblob);
            utxo_init(ux, 4096, ublob, sizeof ublob);
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk1, 1);
            unsigned char tx[160]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
            tx[n++]=1; { unsigned long long v = 900000ULL; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=(unsigned char)(2 + V[vi].plen);
            tx[n++]=(unsigned char)V[vi].ver; tx[n++]=(unsigned char)V[vi].plen;
            memset(tx+n, 0x77, (size_t)V[vi].plen); n += (unsigned long)V[vi].plen;
            memset(tx+n, 0, 4); n+=4;
            unsigned char tid[32]; memset(tid, 0x5F, 32); tid[0]=(unsigned char)vi;
            long r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
            char lbl[140]; snprintf(lbl, sizeof lbl, "MEM-15 %s", V[vi].what);
            if (V[vi].want_ok) okv(r == 1, lbl);
            else okv(r != 1 && strstr(mpool_policy_reason(pol), "scriptpubkey") != NULL, lbl);
            if (V[vi].want_ok != (r == 1))
                printf("      r=%ld reason=%s\n", r, mpool_policy_reason(pol));
        }
    }

    printf("== MEM-16: min-relay fee rounds like Core's CFeeRate::GetFee ==\n");
    /* 2026-10-01: v31.1's GetFee ROUNDS UP (FeeFrac::EvaluateFeeUp). MEM-16
     * (2026-09-03) asserted truncation -- an older Core's GetFee -- and this
     * test pinned it: 8 sat over 82 vB "accepted". Measured on v31.1: 141 vB
     * at 100 sat/kvB is refused at 14 sat ("14 < 15"). The tx below is
     * non-segwit, so vsize == its serialized length, 82 bytes: Core needs
     * ceil(8.2) = 9 sat. So 9 sat is ACCEPTED and 8 is REFUSED -- the pair
     * pins the rounding from both sides. */
    {
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        mpool_policy_set_pending_sigops(0);
        unsigned char prev[32]; memset(prev, 0x6C, 32);
        unsigned char spk[2] = { 0x51, 0x00 };
        for (int fee = 9; fee >= 8; fee--){
            memset(stbuf, 0, sizeof stbuf);
            mpool_policy_init(pol, 100, 25, 101000, 25, 101000, 1);   /* 100 sat/kvB */
            POLICY_STATE_INIT(stbuf, 256);
            mpool_init(mp, 4096, mblob, sizeof mblob);
            utxo_init(ux, 4096, ublob, sizeof ublob);
            utxo_put(ux, prev, 0, 1000000ULL, 0, 0, spk, 1);
            unsigned char tx[128]; unsigned long n = 0;
            tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
            tx[n++]=1; memcpy(tx+n, prev, 32); n+=32; memset(tx+n, 0, 4); n+=4; tx[n++]=0; memset(tx+n,0xff,4); n+=4;
            tx[n++]=1; { unsigned long long v = 1000000ULL - (unsigned long long)fee; for (int b=0;b<8;b++) tx[n++]=(unsigned char)(v>>(8*b)); }
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, 0x66, 20); n+=20;
            memset(tx+n, 0, 4); n+=4;
            okv(n == 82, "the boundary tx is 82 bytes (so Core's floor is ceil(8.2) = 9 sat at 100 sat/kvB)");
            unsigned char tid[32]; memset(tid, 0x6D, 32); tid[0] = (unsigned char)fee;
            long r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
            if (fee == 9)
                okv(r == 1, "9 sat over 82 vB at 100 sat/kvB is ACCEPTED (Core: ceil(8.2) = 9)");
            else
                okv(r != 1 && strstr(mpool_policy_reason(pol), "min relay fee") != NULL,
                    "8 sat over 82 vB is REFUSED (Core rounds the floor UP)");
        }
    }

    test_cluster_walk_differential();
    test_descendant_walk_differential();

    printf("\n%s (%d failures)\n", failures ? "TESTS FAILED" : "ALL TESTS PASSED", failures);
    return failures ? 1 : 0;
}


/* ---- -permitbaremultisig, through the REAL acceptance path ---------------
 * The option was already covered at the config layer and at the setter, but
 * not where it matters: the actual REJECTION. standard_checks() is static
 * behind mpol_add_core, so the only honest way to assert it is to build a
 * transaction with a bare multisig output and push it through
 * mpool_policy_add twice -- once with the option on, once off -- and require
 * the verdict to differ.
 *
 * Note this scenario deliberately does NOT set -acceptnonstdtxn, unlike the
 * fee/graph scenarios above: standardness is precisely what is under test. */
static int test_bare_multisig(void){
    int bad = 0;
    printf("== permitbaremultisig: the rejection itself ==\n");

    /* a 1-of-1 bare multisig: OP_1 <33-byte pubkey> OP_1 OP_CHECKMULTISIG */
    unsigned char spk[37];
    spk[0] = 0x51; spk[1] = 0x21;
    for (int i = 0; i < 33; i++) spk[2+i] = (unsigned char)(0x02 + (i & 1));  /* plausible compressed key */
    spk[35] = 0x51; spk[36] = 0xae;

    unsigned char prev[32]; memset(prev, 0x11, 32);

    /* build the raw tx by hand: 1 input (empty scriptSig), 1 bare-multisig output */
    unsigned char tx[256]; unsigned long n = 0;
    tx[n++]=0x02; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* version 2 */
    tx[n++]=0x01;                                                 /* 1 input   */
    memcpy(tx+n, prev, 32); n += 32;
    tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* vout 0    */
    tx[n++]=0x00;                                                 /* empty scriptSig (push-only) */
    tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff;      /* sequence  */
    tx[n++]=0x01;                                                 /* 1 output  */
    { unsigned long long v = 100000ULL;                           /* well above dust */
      for (int i = 0; i < 8; i++) tx[n++] = (unsigned char)(v >> (8*i)); }
    tx[n++] = (unsigned char)sizeof spk;
    memcpy(tx+n, spk, sizeof spk); n += sizeof spk;
    tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* locktime  */

    unsigned char txid[32]; memset(txid, 0x22, 32);

    for (int permit = 1; permit >= 0; permit--){
        static unsigned char pol[128];
        static unsigned char stbuf[1<<21];
        static unsigned char mp[40 + 4096*80 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000 /* sat/kvB: 1 sat/vB, as before */, 25, 101000, 25, 101000, 1);
        mpool_policy_set_baremultisig(pol, (unsigned)permit);
        POLICY_STATE_INIT(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* fund it generously so the fee is never the reason for a rejection */
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, (const unsigned char*)"\x51", 1);

        long rv = mpool_policy_add(pol, stbuf, mp, tx, n, txid, ux);
        const char* why = mpool_policy_reason(pol);
        /* this API returns 1 for accepted and 0 for rejected -- NOT a negative
         * errno. Checking rv >= 0 makes both outcomes look like success, which
         * is how the first cut of this test "passed" the accept case while
         * proving nothing. */
        if (permit){
            if (rv == 1){ printf("  ok  permitbaremultisig=1 ACCEPTS a bare multisig output\n"); }
            else { printf("  FAIL permitbaremultisig=1 rejected it: %s\n", why ? why : "?"); bad++; }
        } else {
            if (rv == 0 && why && strcmp(why, "bare-multisig") == 0){
                printf("  ok  permitbaremultisig=0 REJECTS it, with reason \"bare-multisig\"\n");
            } else if (rv == 0){
                printf("  FAIL rejected, but for the wrong reason: %s\n", why ? why : "?"); bad++;
            } else { printf("  FAIL permitbaremultisig=0 still accepted it (rv=%ld)\n", rv); bad++; }
        }
    }
    return bad;
}

/* ---- run one scenario ---- */
static int run_scenario(int si,
                        unsigned max_anc, unsigned max_anc_bytes,
                        unsigned max_desc, unsigned max_desc_bytes,
                        unsigned rbf,
                        const char* const* utxo_txid, const unsigned* utxo_idx,
                        const unsigned long long* utxo_val, unsigned nutxo,
                        unsigned nsteps,
                        const char* const* step_tx, const char* const* step_txid,
                        const unsigned* step_kind, const unsigned* step_expect,
                        const unsigned long long* step_arg){
    /* policy config + state */
    static unsigned char pol[128];
    static unsigned char stbuf[1<<21];
    memset(stbuf, 0, sizeof stbuf);
    mpool_policy_init(pol, 1000 /* sat/kvB: 1 sat/vB, as before */, max_anc, max_anc_bytes, max_desc, max_desc_bytes, rbf);
    /* fixtures are synthetic, deliberately non-standard txs: run under
     * Core's own regtest escape hatch (-acceptnonstdtxn) so this test
     * keeps exercising fee/graph mechanics, not IsStandardTx. */
    mpool_policy_set_acceptnonstd(pol, 1);
    /* MEM-23 (2026-09-05): the 65-non-witness-byte floor is UNCONDITIONAL in
     * Core -- it mitigates CVE-2017-12842, so -acceptnonstdtxn does not switch
     * it off, and as of this change neither does ours. These fixtures are
     * ~60-byte synthetic transactions whose whole purpose is fee and
     * package-graph mechanics, so the floor is turned off HERE, explicitly,
     * rather than by weakening the production rule. No config option reaches
     * this; it is test-only. */
    { extern void mpol_policy_set_min_size(void*, unsigned);
      mpol_policy_set_min_size(pol, 0); }
    POLICY_STATE_INIT(stbuf, 256);

    /* structural mempool */
    static unsigned char mp[40 + 4096*80 + 8];
    static unsigned char mblob[1<<20];
    mpool_init(mp, 4096, mblob, sizeof mblob);

    /* confirmed UTXO set */
    static unsigned char ux[40 + 4096*48 + 8];
    static unsigned char ublob[1<<16];
    utxo_init(ux, 4096, ublob, sizeof ublob);
    for (unsigned i=0;i<nutxo;i++){
        unsigned char t[32];
        hex_in(t, utxo_txid[i]);
        utxo_put(ux, t, utxo_idx[i], utxo_val[i], 0, 0, (const unsigned char*)"\x51", 1);
    }

    printf("== scenario %d: %u steps ==\n", si, nsteps);
    unsigned ok=0, bad=0;
    for (unsigned i=0;i<nsteps;i++){
        switch (step_kind[i]){
        case 0: { /* add */
            unsigned char txbuf[MAXTX]; unsigned char txid[32];
            int n = hex_in(txbuf, step_tx[i]);
            hex_in(txid, step_txid[i]);
            long rv = mpool_policy_add(pol, stbuf, mp, txbuf, (unsigned long)n,
                                       txid, ux);
            int expect = (int)step_expect[i];
            if (rv == expect){ printf("  ok  : [%u] add  verdict=%ld (exp %d)\n",
                                      i, rv, expect); ok++;}
            else{ printf("  FAIL: [%u] add  verdict=%ld (exp %d) reason=%s\n",
                         i, rv, expect, mpool_policy_reason(pol)); bad++; failures++; }
            break;
        }
        case 1: { /* present */
            unsigned char txid[32];
            hex_in(txid, step_txid[i]);
            unsigned long len=0;
            const unsigned char* p = mpool_get(mp, txid, &len);
            int present = p!=NULL ? 1 : 0;
            int expect = (int)step_expect[i];
            if (present == expect){ printf("  ok  : [%u] mempool present=%d (exp %d)\n", i, present, expect); ok++;}
            else{ printf("  FAIL: [%u] mempool present=%d (exp %d)\n", i, present, expect); bad++; failures++; }
            break;
        }
        case 2: { /* est */
            unsigned long long got = mpool_policy_estimate_feerate(stbuf);
            unsigned long long expect = step_arg[i];
            /* allow EMA division differences of at most 1 sat/kB */
            long diff = (long)got - (long)expect; if (diff<0) diff=-diff;
            if (diff <= 1){ printf("  ok  : [%u] est feerate=%llu (exp %llu)\n", i, got, expect); ok++;}
            else{ printf("  FAIL: [%u] est feerate=%llu (exp %llu)\n", i, got, expect); bad++; failures++; }
            break;
        }
        default:
            printf("  FAIL: [%u] unknown kind %u\n", i, step_kind[i]); failures++;
        }
    }
    printf("  scenario %d: %u ok, %u bad\n", si, ok, bad);
    return bad?1:0;
}

static int hex_in(unsigned char* out, const char* h){
    int n = (int)strlen(h)/2;
    for (int i=0;i<n;i++){ unsigned v; sscanf(h+2*i,"%2x",&v); out[i]=(unsigned char)v; }
    return n;
}


/* ================================================================
 * 2026-10-08: mpol_add_core's cluster-limit walk finds a node's neighbours
 * through the children index instead of scanning the whole registry for each
 * node it pops (at a 77k pool that scan was ~63% of the mainnet worker's
 * CPU). The walk's outcome depends only on the set it reaches, so the index
 * must give the scan's answer on every transaction. This replays one random
 * workload twice -- scan, then index -- on fresh state and compares every
 * verdict and reason: chains, fan-ins (2-3 in-pool parents), diamonds, a
 * limitclustercount of 12 so the bound is hit often, and BIP125-signalling
 * replacements whose evicted sets the walk must leave out.
 * ================================================================ */
extern void mpool_policy_set_cluster_walk_scan(int on);
#define CWD_STEPS 1500
static int cwd_run(int scan, unsigned cluster_count, char verdict[CWD_STEPS], char reasons[CWD_STEPS][48],
                   int* n_cluster_refused, int* n_multi_parent_in, int* n_replaced,
                   void (*after)(void* st, void* mp)){
    static unsigned char pol[128];
    static unsigned char stbuf[1<<22];
    static unsigned char mp[40 + 8192*80 + 8];
    static unsigned char mblob[1<<21];
    static unsigned char ux[40 + 4096*48 + 8];
    static unsigned char ublob[1<<16];
    memset(stbuf, 0, sizeof stbuf);
    mpool_policy_init(pol, 1000, 200, 10100000, 200, 10100000, 1);
    mpool_policy_set_cluster_limits(pol, cluster_count, 101000);
    POLICY_STATE_INIT(stbuf, 8192);
    mpool_init(mp, 8192, mblob, sizeof mblob);
    utxo_init(ux, 4096, ublob, sizeof ublob);
    mpool_policy_set_cluster_walk_scan(scan);
    /* every output ever made: confirmed coins first, then each accepted tx's */
    static struct { unsigned char txid[32]; unsigned vout; unsigned long long value; int spent, pool; } out[CWD_STEPS * 3 + 256];
    int nout = 0;
    unsigned char spk[2] = { 0x51, 0x00 };
    for (int c = 0; c < 160; c++){
        memset(out[nout].txid, 0xC7, 32); out[nout].txid[0] = (unsigned char)c; out[nout].txid[1] = (unsigned char)(c >> 8);
        out[nout].vout = 0; out[nout].value = 5000000ULL; out[nout].spent = 0; out[nout].pool = 0;
        utxo_put(ux, out[nout].txid, 0, out[nout].value, 0, 0, spk, 1);
        nout++;
    }
    unsigned x = 0x9e3779b9u;
    #define CWD_RND() (x = x * 1103515245u + 12345u, (x >> 8))
    *n_cluster_refused = *n_multi_parent_in = *n_replaced = 0;
    for (int step = 0; step < CWD_STEPS; step++){
        int pick[3], np = 1 + (int)(CWD_RND() % 3);
        int replace = (CWD_RND() % 10) == 0;          /* spend an already-spent in-pool output: a conflict */
        int got = 0;
        for (int tries = 0; tries < 60 && got < np; tries++){
            int k;
            /* mostly in-pool outputs (clusters), recent ones (chains) */
            if ((CWD_RND() % 4) && nout > 160) k = nout - 1 - (int)(CWD_RND() % (unsigned)((nout - 160) < 40 ? (nout - 160) : 40));
            else k = (int)(CWD_RND() % (unsigned)nout);
            if (replace && got == 0){ if (!out[k].spent || !out[k].pool) continue; }
            else if (out[k].spent) continue;
            int dup = 0; for (int q = 0; q < got; q++) if (pick[q] == k) dup = 1;
            if (dup) continue;
            pick[got++] = k;
        }
        if (got == 0){ verdict[step] = 2; reasons[step][0] = 0; continue; }
        unsigned long long in = 0; int pool_parents = 0;
        for (int q = 0; q < got; q++){ in += out[pick[q]].value; pool_parents += out[pick[q]].pool; }
        unsigned long long fee = replace ? 400000ULL + (CWD_RND() % 1000) : 2000ULL + (CWD_RND() % 3000);
        if (in <= fee + 3 * 1000){ verdict[step] = 2; reasons[step][0] = 0; continue; }
        int nouts = 1 + (int)(CWD_RND() % 3);
        unsigned long long each = (in - fee) / (unsigned long long)nouts;
        unsigned char tx[3*41 + 3*31 + 32]; unsigned long n = 0;
        tx[n++]=2;tx[n++]=0;tx[n++]=0;tx[n++]=0;
        tx[n++]=(unsigned char)got;
        for (int q = 0; q < got; q++){
            memcpy(tx+n, out[pick[q]].txid, 32); n+=32;
            for (int b=0;b<4;b++) tx[n++]=(unsigned char)(out[pick[q]].vout>>(8*b));
            tx[n++]=0; tx[n++]=0xfd; tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff;   /* BIP125 */
        }
        tx[n++]=(unsigned char)nouts;
        for (int o = 0; o < nouts; o++){
            for (int b=0;b<8;b++) tx[n++]=(unsigned char)(each>>(8*b));
            tx[n++]=22; tx[n++]=0x00; tx[n++]=0x14; memset(tx+n, (unsigned char)(step + o), 20); tx[n+1] = (unsigned char)(step >> 8); n+=20;
        }
        memset(tx+n, 0, 4); n+=4;
        unsigned char tid[32]; memset(tid, 0xD3, 32); tid[0] = (unsigned char)step; tid[1] = (unsigned char)(step >> 8);
        long r = mpool_policy_add(pol, stbuf, mp, tx, n, tid, ux);
        verdict[step] = (char)(r == 1);
        snprintf(reasons[step], 48, "%s", r == 1 ? "" : mpool_policy_reason(pol));
        if (r != 1 && strstr(reasons[step], "too-large-cluster")) (*n_cluster_refused)++;
        if (r == 1){
            if (pool_parents >= 2) (*n_multi_parent_in)++;
            if (replace) (*n_replaced)++;
            for (int q = 0; q < got; q++) out[pick[q]].spent = 1;
            for (int o = 0; o < nouts && nout < (int)(sizeof out / sizeof out[0]); o++){
                memcpy(out[nout].txid, tid, 32); out[nout].vout = (unsigned)o; out[nout].value = each;
                out[nout].spent = 0; out[nout].pool = 1; nout++;
            }
        }
    }
    #undef CWD_RND
    mpool_policy_set_cluster_walk_scan(0);
    if (after) after(stbuf, mp);
    return (int)mpool_count(mp);
}
static void test_cluster_walk_differential(void){
    printf("== the cluster-limit walk: children index vs the registry scan ==\n");
    static char va[CWD_STEPS], vb[CWD_STEPS];
    static char ra[CWD_STEPS][48], rb[CWD_STEPS][48];
    const unsigned limits[2] = { 12, 64 };
    for (int L = 0; L < 2; L++){
        int ca, ma, xa, cb, mb, xb;
        int pa = cwd_run(1, limits[L], va, ra, &ca, &ma, &xa, 0);
        int pb = cwd_run(0, limits[L], vb, rb, &cb, &mb, &xb, 0);
        int first = -1;
        for (int i = 0; i < CWD_STEPS && first < 0; i++)
            if (va[i] != vb[i] || strcmp(ra[i], rb[i])) first = i;
        if (first >= 0) printf("      limitclustercount=%u: step %d: scan %d \"%s\", index %d \"%s\"\n",
                               limits[L], first, va[first], ra[first], vb[first], rb[first]);
        printf("      limitclustercount=%u: pool %d, %d too-large-cluster, %d accepted with 2+ in-pool parents, %d replacements\n",
               limits[L], pb, cb, mb, xb);
        char m[200];
        snprintf(m, sizeof m, "limitclustercount=%u: every verdict and reason is the scan's (%d transactions)", limits[L], CWD_STEPS);
        okv(first < 0 && pa == pb, m);
        if (L == 0){
            okv(cb >= 20, "...the workload hits the cluster bound (at least 20 too-large-cluster refusals)");
            okv(mb >= 20 && xb >= 5, "...and covers fan-ins (2+ in-pool parents) and accepted replacements");
        }
    }
}

/* ================================================================
 * 2026-10-08 (2): collect_descendant_txids -- the descendant set behind RBF
 * eviction, package removal and sibling eviction -- walks the children index
 * after its first pop instead of scanning the registry for every node it
 * pops. Its output is a LIST whose order the removal paths consume, so this
 * compares the list itself, not just its size:
 *
 *   1. On the cluster-walk workload's final pool (limitclustercount 64, so
 *      clusters run deep), every transaction's descendant list under the scan
 *      and under the index, element for element, at the full bound and at a
 *      bound of 3 so the -1 overflow is taken often.
 *   2. Then a removal sequence run on two fresh copies of that workload, one
 *      per mode: remove_package on every 5th surviving transaction, comparing
 *      each removed count and the pool size after.
 * ================================================================ */
extern void mpool_policy_set_desc_walk_scan(int on);
extern long mpool_policy_remove_package(void* st, void* mp, const unsigned char txid[32]);
extern long mpool_policy_descendant_txids(void* st, const unsigned char txid[32],
                                          unsigned char (*out)[32], int cap);
static int dwd_lists, dwd_mismatch, dwd_with_desc, dwd_overflow, dwd_max;
static long dwd_removed[CWD_STEPS + 1];
static int dwd_nremoved;
static void dwd_tid(unsigned char tid[32], int step){
    memset(tid, 0xD3, 32); tid[0] = (unsigned char)step; tid[1] = (unsigned char)(step >> 8);
}
static void dwd_compare(void* st, void* mp){
    (void)mp;
    static unsigned char a[128][32], b[128][32];
    const int caps[2] = { 128, 3 };
    for (int step = 0; step < CWD_STEPS; step++){
        unsigned char tid[32]; dwd_tid(tid, step);
        for (int c = 0; c < 2; c++){
            mpool_policy_set_desc_walk_scan(1);
            long na = mpool_policy_descendant_txids(st, tid, a, caps[c]);
            mpool_policy_set_desc_walk_scan(0);
            long nb = mpool_policy_descendant_txids(st, tid, b, caps[c]);
            if (na == -2) break;                          /* not in the pool */
            dwd_lists++;
            if (na != nb || (na > 0 && memcmp(a, b, (size_t)na * 32))) dwd_mismatch++;
            if (c == 0 && na > 0) dwd_with_desc++;
            if (c == 0 && na > dwd_max) dwd_max = (int)na;
            if (c == 1 && na == -1) dwd_overflow++;
        }
    }
}
static void dwd_remove(void* st, void* mp){
    dwd_nremoved = 0;
    for (int step = 0; step < CWD_STEPS; step += 5){
        unsigned char tid[32]; dwd_tid(tid, step);
        dwd_removed[dwd_nremoved++] = mpool_policy_remove_package(st, mp, tid);
    }
    dwd_removed[dwd_nremoved++] = (long)mpool_count(mp);
}
static void test_descendant_walk_differential(void){
    printf("== the descendant walk: children index vs the registry scan ==\n");
    static char v[CWD_STEPS]; static char r[CWD_STEPS][48];
    int c, m, x;
    dwd_lists = dwd_mismatch = dwd_with_desc = dwd_overflow = dwd_max = 0;
    cwd_run(0, 64, v, r, &c, &m, &x, dwd_compare);
    printf("      %d lists compared, %d with descendants (largest %d), %d overflowed at a bound of 3, %d differ\n",
           dwd_lists, dwd_with_desc, dwd_max, dwd_overflow, dwd_mismatch);
    okv(dwd_mismatch == 0, "every descendant list is the scan's, element for element, at bounds 128 and 3");
    okv(dwd_with_desc >= 100 && dwd_max >= 10 && dwd_overflow >= 20,
        "...over sets that are many, deep (10+), and overflow the small bound");

    static long rs[CWD_STEPS + 1]; int ns;
    mpool_policy_set_desc_walk_scan(1);
    cwd_run(0, 64, v, r, &c, &m, &x, dwd_remove);
    mpool_policy_set_desc_walk_scan(0);
    memcpy(rs, dwd_removed, sizeof rs); ns = dwd_nremoved;
    cwd_run(0, 64, v, r, &c, &m, &x, dwd_remove);
    long total = 0, multi = 0;
    for (int i = 0; i + 1 < ns; i++){ total += rs[i]; if (rs[i] > 1) multi++; }
    printf("      remove_package x%d: %ld removed, %ld removals took descendants, pool %ld -> %ld\n",
           ns - 1, total, multi, rs[ns - 1] + total, rs[ns - 1]);
    okv(ns == dwd_nremoved && !memcmp(rs, dwd_removed, (size_t)ns * sizeof rs[0]),
        "remove_package: every removed count and the final pool size are the scan's");
    okv(multi >= 10, "...and at least 10 of those removals took a descendant set");
}
