/* test_tapscript_scale.c -- inscription-SCALE tapscript coverage.
 *
 * CHAIN_AHEAD_CENSUS.md's Outcome table (2026-08-22) left two rows open:
 *
 *   | ">10 KB tapscript / real inscription" untested at scale | **Still open.**
 *     ... The single biggest remaining untested risk, unchanged. |
 *   | `tap_leaf_hash` 4 MB leaf cap | Still open, design-worthy-not-urgent. |
 *
 * This closes both with REAL mainnet transactions -- the largest tapscript
 * leaf, the deepest control block and the widest script-path witness stack
 * the chain has ever carried -- each driven through the real block-connection
 * dispatch tx_verify_block_connect, exactly like tests/test_segwit_coverage.c.
 *
 * WHAT MAKES THE NEGATIVE CASES LOAD-BEARING: a verifier that silently
 * TRUNCATED a large leaf (a fixed buffer, a u16 length, a capped memcpy) would
 * still ACCEPT the unmodified fixture, because the truncated prefix hashes
 * consistently on both sides of nothing. So for every fixture we also flip the
 * LAST byte of the leaf script and require a "commitment mismatch" rejection --
 * that byte only changes the answer if the WHOLE leaf actually reached
 * tap_leaf_hash. Same idea for the deepest control block (flip its last merkle
 * node) and for the widest witness (flip a byte of the first initial-stack
 * item, which only matters if all 10 items were really pushed).
 *
 * IT ALSO CARRIES THE INCIDENT #18 REGRESSION. Looking for a size wall on
 * this path turned up a different bug beside it: the tapscript initial stack
 * had no MAX_SCRIPT_ELEMENT_SIZE check at all, so a >524-byte initial-stack
 * item overran a 528,000-byte heap buffer, and a 521-byte one was a silent
 * consensus false-accept. That shape does not exist on mainnet (47,578 sampled
 * real script-path inputs top out at a 79-byte initial-stack item), so those
 * four vectors are synthetic -- with their verdicts taken from Bitcoin Core
 * itself via validation/diff_tapscript_stack.py, not from this author. See
 * tapscript_stack_vec.h.
 *
 * Fixtures are generated by validation/fetch_tapscript_scale.py:
 *   - <=64 KB raw tx  -> inlined in tapscript_scale_vec.h (always runs, no oracle)
 *   - >64 KB raw tx   -> tests/fixtures/tapscript_big.txt, gitignored; regenerate
 *                        with `python3 validation/fetch_tapscript_scale.py --big
 *                        tests/fixtures`. Absent => those cases SKIP loudly and
 *                        the test still exits 0, rather than failing merely
 *                        because the Core oracle is offline.
 */
#define _GNU_SOURCE
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/wait.h>
#include <malloc.h>
#include "tapscript_scale_vec.h"
#include "tapscript_stack_vec.h"

typedef unsigned char u8; typedef unsigned long u64;

struct lsm_state {
    long log_fd, idx_fd;
    u64 log_len, ckpt_log_off, ckpt_n;
    u64 op_count, op_threshold, fill_threshold;
    void* tomb_buf; u64 tomb_cap, tomb_n, total_live, next_gen;
    void* manifest_buf; u64 manifest_cap, manifest_n;
    void* scratch_buf; u64 scratch_cap;
    u64 next_run_no;
    void* tomb_hash_buf; u64 tomb_hash_mask;
    int  bulk_mode; u64 pad2[16];
};
extern long utxo_struct_size(unsigned long);
extern void utxo_init(void*, unsigned long, void*, unsigned long);
extern long utxo_lsm_init(struct lsm_state*);
extern long utxo_lsm_put(struct lsm_state*, void*, const u8 txid[32], uint32_t index,
                         u64 value, u64 height, u64 is_coinbase, const u8* script, uint32_t slen);
extern int  tx_verify_block_connect(const u8* tx, u64 txlen, long height, const u8 bh[32],
                                    void* lst, void* u, const char** reason);
extern long tap_leaf_hash(uint8_t out[32], uint8_t leaf_version,
                          const uint8_t* script, uint64_t slen);

#define BLOOM_MAX_BYTES (4*1024*1024)
#define SCRIPT_MAX_BYTES 65536

/* link-only stubs (real defs live in daemon/utxo_live.c, not linked here) */
long bidx_get(void* bx, uint32_t caller_tx_index, const u8 txid[32], uint32_t index,
              u64* value, u64* height, u64* is_coinbase, const u8** script, unsigned long* slen){
  (void)bx;(void)caller_tx_index;(void)txid;(void)index;(void)value;(void)height;(void)is_coinbase;(void)script;(void)slen; return 0; }
long mempool_resolve_confirmed_utxo(void* u, const u8 txid[32], unsigned long index,
              unsigned long long* value, const u8** script, unsigned long* slen){
  (void)u;(void)txid;(void)index;(void)value;(void)script;(void)slen; return 0; }

/* ---- fast hex (the 3.9 MB fixture is 7.9 MB of hex; sscanf-per-byte is not ok) ---- */
static int nib(int c){
  if (c>='0'&&c<='9') return c-'0';
  if (c>='a'&&c<='f') return c-'a'+10;
  if (c>='A'&&c<='F') return c-'A'+10;
  return -1;
}
static long hx(const char* h, u8* o){
  long n=0;
  for(;;h+=2,n++){ int a=nib(h[0]); if(a<0) break; int b=nib(h[1]); if(b<0) break; o[n]=(u8)((a<<4)|b); }
  return n;
}

static int fails=0, checks=0;
static void ck(const char* n,int c){ checks++; printf("%s %s\n",c?"  ok ":"  FAIL",n); if(!c)fails++; }

static struct lsm_state g_lst; static void* g_tab;
static void seed_lsm(void){
  unsigned long slots=1UL<<12; long us=utxo_struct_size(slots);
  g_tab=malloc((size_t)us); void* blob=malloc(4UL<<20); utxo_init(g_tab,slots,blob,4UL<<20);
  memset(&g_lst,0,sizeof g_lst);
  u64 op=slots*2, fill=slots*3/4, tomb=op, desc=slots*3, scr=desc*128+BLOOM_MAX_BYTES+SCRIPT_MAX_BYTES;
  g_lst.op_threshold=op; g_lst.fill_threshold=fill;
  g_lst.tomb_buf=malloc(tomb*36); g_lst.tomb_cap=tomb;
  g_lst.manifest_buf=malloc(256*16); g_lst.manifest_cap=256;
  g_lst.scratch_buf=malloc(scr); g_lst.scratch_cap=scr;
  if(utxo_lsm_init(&g_lst)!=1){fprintf(stderr,"lsm_init\n");exit(1);}
}
static u8 g_spk[10000];
static void seed_prevout(const char* txid_hex, unsigned index, unsigned long long value,
                         const char* spk_hex){
  u8 tid[32], rev[32];
  hx(txid_hex, tid);
  for(int b=0;b<32;b++) rev[b]=tid[31-b];
  long sl = hx(spk_hex, g_spk);
  if(utxo_lsm_put(&g_lst,g_tab,rev,index,value,0,0,g_spk,(uint32_t)sl)!=1){
    fprintf(stderr,"utxo_lsm_put failed\n"); exit(1); }
}

/* ---------------- a fixture, inline or blob, in one shape ---------------- */
typedef struct {
  char  name[64];
  long  height;
  char  txid[80];
  u8*   tx; long txlen;
  unsigned target;
  unsigned long leaf_off, leaf_len, ctrl_len;
  unsigned depth, nwit, ninit;
  char  note[256];
} fx_t;

static u8 g_bh[32] = {0};

static void run_fixture(const fx_t* F){
  const char* reason="?";
  char nm[400];
  int r = tx_verify_block_connect(F->tx,(u64)F->txlen,F->height,g_bh,&g_lst,g_tab,&reason);
  snprintf(nm,sizeof nm,"%s @%ld: %s", F->name, F->height, F->note);
  ck(nm, r==1);
  if(r!=1) printf("       REASON: %s\n", reason);

  /* ---- negative 1: flip the LAST byte of the leaf script.
   * A verifier that truncated the leaf anywhere before its end would still
   * accept this; a correct one recomputes a different TapLeaf hash and so a
   * different merkle root, and fails the control-block commitment. ---- */
  {
    unsigned long p = F->leaf_off + F->leaf_len - 1;
    u8 save = F->tx[p]; F->tx[p] ^= 0x01;
    const char* rs="?";
    int rr = tx_verify_block_connect(F->tx,(u64)F->txlen,F->height,g_bh,&g_lst,g_tab,&rs);
    snprintf(nm,sizeof nm,"%s: flipping the LAST byte of the %lu-byte leaf is REJECTED "
             "(whole leaf really reaches tap_leaf_hash)", F->name, F->leaf_len);
    ck(nm, rr==0);
    if(rr!=0) printf("       (accepted -- the leaf tail is NOT being hashed)\n");
    else printf("       reason: %s\n", rs);
    F->tx[p] = save;
  }
  /* ---- negative 2: flip the FIRST byte of the leaf script (cheap control:
   * proves negative 1 is not just "any mutation rejects for another reason"). */
  {
    unsigned long p = F->leaf_off;
    u8 save = F->tx[p]; F->tx[p] ^= 0x01;
    const char* rs="?";
    int rr = tx_verify_block_connect(F->tx,(u64)F->txlen,F->height,g_bh,&g_lst,g_tab,&rs);
    snprintf(nm,sizeof nm,"%s: flipping the FIRST byte of the leaf is REJECTED", F->name);
    ck(nm, rr==0);
    F->tx[p] = save;
  }
  /* ---- negative 3: flip the last byte of the control block (its deepest
   * merkle sibling). Only matters if all `depth` nodes are walked. ---- */
  if (F->depth > 0) {
    unsigned long p = F->leaf_off + F->leaf_len;   /* control block follows the leaf ... */
    /* ... after its own compactsize length prefix; find it by scanning past
     * the varint, whose size we can derive from ctrl_len. */
    unsigned long csn = (F->ctrl_len < 0xfd) ? 1 : (F->ctrl_len <= 0xffff ? 3 : 5);
    unsigned long last = p + csn + F->ctrl_len - 1;
    u8 save = F->tx[last]; F->tx[last] ^= 0x01;
    const char* rs="?";
    int rr = tx_verify_block_connect(F->tx,(u64)F->txlen,F->height,g_bh,&g_lst,g_tab,&rs);
    snprintf(nm,sizeof nm,"%s: flipping the deepest of %u merkle nodes in the %lu-byte "
             "control block is REJECTED", F->name, F->depth, F->ctrl_len);
    ck(nm, rr==0);
    F->tx[last] = save;
  }
}

/* ---------------- blob loader (large fixtures) ---------------- */
static int load_blob(const char* path){
  FILE* fh = fopen(path, "r");
  if (!fh) return 0;
  char* line = NULL; size_t cap = 0; ssize_t n;
  fx_t F; memset(&F,0,sizeof F);
  int in_fx = 0, loaded = 0;
  /* prevouts are seeded as they are read; a fixture is run at its END line. */
  while ((n = getline(&line, &cap, fh)) > 0) {
    while (n && (line[n-1]=='\n' || line[n-1]=='\r')) line[--n] = 0;
    if (!strncmp(line,"FIXTURE ",8)) { memset(&F,0,sizeof F); snprintf(F.name,sizeof F.name,"%s",line+8); in_fx=1; }
    else if (!in_fx) continue;
    else if (!strncmp(line,"HEIGHT ",7)) F.height = atol(line+7);
    else if (!strncmp(line,"TXID ",5))   snprintf(F.txid,sizeof F.txid,"%s",line+5);
    else if (!strncmp(line,"TARGET ",7)) F.target = (unsigned)atol(line+7);
    else if (!strncmp(line,"LEAF ",5))   sscanf(line+5,"%lu %lu",&F.leaf_off,&F.leaf_len);
    else if (!strncmp(line,"CTRL ",5))   sscanf(line+5,"%lu %u",&F.ctrl_len,&F.depth);
    else if (!strncmp(line,"NWIT ",5))   sscanf(line+5,"%u %u",&F.nwit,&F.ninit);
    else if (!strncmp(line,"NOTE ",5))   snprintf(F.note,sizeof F.note,"%s",line+5);
    else if (!strncmp(line,"PREV ",5)) {
      char t[80], s[20001]; unsigned idx; unsigned long long val;
      if (sscanf(line+5,"%79s %u %llu %20000s",t,&idx,&val,s)==4) seed_prevout(t,idx,val,s);
    }
    else if (!strncmp(line,"TX ",3)) {
      size_t hl = strlen(line+3);
      F.tx = malloc(hl/2 + 8);
      F.txlen = hx(line+3, F.tx);
    }
    else if (!strcmp(line,"END")) {
      if (F.tx && F.txlen > 0) { run_fixture(&F); loaded++; }
      free(F.tx); memset(&F,0,sizeof F); in_fx=0;
    }
  }
  free(line); fclose(fh);
  return loaded;
}

/* ---------------- tap_leaf_hash capacity sweep ---------------- */
static void leafsize_sweep(void){
  unsigned long maxn = 0;
  for (unsigned i=0;i<TS_LEAFSIZE_N;i++) if (TS_LEAFSIZES[i].len > maxn) maxn = TS_LEAFSIZES[i].len;
  u8* s = malloc(maxn ? maxn : 1);
  if (!s) { ck("tap_leaf_hash sweep: malloc", 0); return; }
  for (unsigned long i=0;i<maxn;i++) s[i] = (u8)((i*167 + 13) & 0xff);
  char nm[200];
  for (unsigned i=0;i<TS_LEAFSIZE_N;i++){
    const ts_leafsize_t* L = &TS_LEAFSIZES[i];
    u8 out[32]; memset(out,0xAA,32);
    long r = tap_leaf_hash(out, 0xc0, s, (uint64_t)L->len);
    if (L->ok) {
      u8 want[32]; hx(L->hash_hex, want);
      snprintf(nm,sizeof nm,"tap_leaf_hash(%lu B leaf) == BIP341 reference", L->len);
      ck(nm, r==1 && memcmp(out,want,32)==0);
    } else {
      snprintf(nm,sizeof nm,"tap_leaf_hash(%lu B leaf) fails CLEANLY (returns 0, no overflow)", L->len);
      ck(nm, r==0);
    }
  }
  free(s);
}

/* ---------------- BIP342 initial-stack limit vectors ----------------
 * Synthetic (the shape does not occur on mainnet), but every expected verdict
 * is Bitcoin Core's own: validation/diff_tapscript_stack.py replays each vector
 * through Core's VerifyScript via validation/core_verify_oracle's TAPVERIFY
 * command, and all four agree. See tapscript_stack_vec.h's header. */
static long wr_cs(u8* d, unsigned long n){
  if (n < 0xfd){ d[0]=(u8)n; return 1; }
  if (n <= 0xffff){ d[0]=0xfd; d[1]=(u8)n; d[2]=(u8)(n>>8); return 3; }
  d[0]=0xfe; for(int i=0;i<4;i++) d[1+i]=(u8)(n>>(8*i)); return 5;
}
/* version 2 | marker/flag | 1 input (outpoint, empty scriptSig, seq ffffffff) |
 * 1 22-byte-P2WPKH output | witness [filler(item_len), leaf, control] | locktime 0 */
static u8* build_tss_tx(const tss_vec_t* V, long* outlen){
  u8 leaf[4096], ctrl[4096], op[32];
  long ll = hx(V->leaf_hex, leaf), cl = hx(V->control_hex, ctrl);
  hx(V->outpoint_hex, op);
  size_t cap = 128 + (size_t)V->item_len + 9 + (size_t)ll + 9 + (size_t)cl + 9;
  u8* t = malloc(cap); long n = 0;
  t[n++]=0x02; t[n++]=0; t[n++]=0; t[n++]=0;          /* version 2 */
  t[n++]=0x00; t[n++]=0x01;                            /* segwit marker+flag */
  t[n++]=0x01;                                         /* 1 input */
  memcpy(t+n, op, 32); n+=32;
  t[n++]=0; t[n++]=0; t[n++]=0; t[n++]=0;              /* vout 0 */
  t[n++]=0x00;                                         /* empty scriptSig */
  t[n++]=0xff; t[n++]=0xff; t[n++]=0xff; t[n++]=0xff;  /* nSequence */
  t[n++]=0x01;                                         /* 1 output */
  for(int b=0;b<8;b++) t[n++]=(u8)(V->out_value>>(8*b));
  t[n++]=22; t[n++]=0x00; t[n++]=0x14; memset(t+n,0,20); n+=20;
  t[n++]=0x03;                                         /* 3 witness items */
  n += wr_cs(t+n, V->item_len);
  for (unsigned long i=0;i<V->item_len;i++) t[n+i] = (u8)((i*167 + 13) & 0xff);
  n += (long)V->item_len;
  n += wr_cs(t+n, (unsigned long)ll); memcpy(t+n, leaf, ll); n += ll;
  n += wr_cs(t+n, (unsigned long)cl); memcpy(t+n, ctrl, cl); n += cl;
  t[n++]=0; t[n++]=0; t[n++]=0; t[n++]=0;              /* nLockTime */
  *outlen = n;
  return t;
}
static void stack_limit_vectors(void){
  char nm[512];
  for (unsigned v=0; v<TSS_N; v++){
    const tss_vec_t* V = &TSS_VECS[v];
    u8 opb[32]; hx(V->outpoint_hex, opb);
    long sl = hx(V->spk_hex, g_spk);
    if(utxo_lsm_put(&g_lst,g_tab,opb,0,V->value,0,0,g_spk,(uint32_t)sl)!=1){
      fprintf(stderr,"utxo_lsm_put failed\n"); exit(1); }
    long txlen=0; u8* tx = build_tss_tx(V, &txlen);
    snprintf(nm,sizeof nm,"%s (item %lu B): %s", V->name, V->item_len,
             V->expect ? "ACCEPT (Core agrees)" : "REJECT (Core agrees)");
    if (V->forked){
      /* An unfixed build overruns a 528,000-byte heap buffer here, so the
       * verdict is asserted from a CHILD's exit status: a signal means the
       * overflow is back, not merely a wrong answer. Same technique as
       * tests/test_stack_push_len.c. */
      fflush(NULL);
      pid_t p = fork();
      if (p == 0){
        const char* rs="?";
        int r = tx_verify_block_connect(tx,(u64)txlen,800000,g_bh,&g_lst,g_tab,&rs);
        _exit(r ? 3 : 2);
      }
      int st=0; waitpid(p,&st,0);
      int crashed = WIFSIGNALED(st);
      int verdict = WIFEXITED(st) ? (WEXITSTATUS(st) == 3 ? 1 : 0) : -1;
      ck(nm, !crashed && verdict == V->expect);
      if (crashed) printf("       CHILD KILLED BY SIGNAL %d -- the stack_push overrun is back\n",
                          WTERMSIG(st));
      else if (verdict != V->expect) printf("       verdict=%d expected=%d\n", verdict, V->expect);
    } else {
      const char* rs="?";
      int r = tx_verify_block_connect(tx,(u64)txlen,800000,g_bh,&g_lst,g_tab,&rs);
      ck(nm, r == V->expect);
      if (r != V->expect)
        printf("       r=%d expected=%d%s%s\n", r, V->expect,
               r ? " (FALSE ACCEPT of a spend Core rejects)" : " reason=", r ? "" : rs);
    }
    free(tx);
  }
}

int main(void){
  /* Pin glibc's mmap threshold low so the BMC_TLS_BUF scratch buffers
   * (ts_main_e is 528,000 B) are more likely to get their own mappings, where
   * an overrun faults instead of quietly scribbling over a neighbour.
   *
   * Do NOT rely on the fault: whether the pre-fix stack_push overrun SIGSEGVs
   * depends entirely on heap layout. Measured on this build: with
   * MALLOC_MMAP_THRESHOLD_=131072 in the environment the pre-fix child took
   * SIGSEGV; with the default adaptive threshold the same binary silently
   * corrupted adjacent buffers and returned the WRONG VERDICT instead. The
   * verdict comparison below is what actually fails deterministically; the
   * signal check just names the failure correctly when it does happen. */
  mallopt(M_MMAP_THRESHOLD, 128*1024);
  /* Resolve the blob path BEFORE chdir'ing into the LSM's scratch directory. */
  static char blobpath[1024];
  {
    const char* env = getenv("TAPSCRIPT_BIG_BLOB");
    if (env) snprintf(blobpath,sizeof blobpath,"%s",env);
    else {
      char cwd[768]; if(!getcwd(cwd,sizeof cwd)) snprintf(cwd,sizeof cwd,".");
      snprintf(blobpath,sizeof blobpath,"%s/tests/fixtures/%s",cwd,TS_BIG_BLOB);
    }
  }
  char tmpl[]="/tmp/tapscaleXXXXXX"; char* d=mkdtemp(tmpl); if(!d||chdir(d)){perror("dir");return 1;}
  seed_lsm();

  printf("== tap_leaf_hash capacity sweep (independent BIP341 reference hashes)\n");
  leafsize_sweep();

  printf("\n== BIP342 initial-stack limits (verdicts cross-checked against Core)\n");
  stack_limit_vectors();

  printf("\n== inline fixtures (real mainnet, checked in)\n");
  for (unsigned f=0; f<TS_N; f++){
    const ts_fixture_t* X = &TS_FIXTURES[f];
    for (unsigned k=0;k<X->n_in;k++)
      seed_prevout(X->prev[k].txid_hex, X->prev[k].index, X->prev[k].value, X->prev[k].spk_hex);
  }
  for (unsigned f=0; f<TS_N; f++){
    const ts_fixture_t* X = &TS_FIXTURES[f];
    fx_t F; memset(&F,0,sizeof F);
    snprintf(F.name,sizeof F.name,"%s",X->name);
    snprintf(F.txid,sizeof F.txid,"%s",X->txid);
    snprintf(F.note,sizeof F.note,"%s",X->note);
    F.height=X->height; F.target=X->target;
    F.leaf_off=X->leaf_off; F.leaf_len=X->leaf_len; F.ctrl_len=X->ctrl_len;
    F.depth=X->depth; F.nwit=X->nwit; F.ninit=X->ninit;
    size_t hl = strlen(X->tx_hex);
    F.tx = malloc(hl/2 + 8); F.txlen = hx(X->tx_hex, F.tx);
    run_fixture(&F);
    free(F.tx);
  }

  /* ---- widest witness: flip a byte of the FIRST initial-stack item of the
   * 12-item fixture. Only rejects if every one of the 10 initial items really
   * made it onto the tapscript stack (incident #15's cap was 8). ---- */
  for (unsigned f=0; f<TS_N; f++){
    const ts_fixture_t* X = &TS_FIXTURES[f];
    if (strcmp(X->name,"tap_12items")!=0) continue;
    size_t hl = strlen(X->tx_hex);
    u8* tx = malloc(hl/2 + 8); long txlen = hx(X->tx_hex, tx);
    /* Corrupt one byte of the control block's INTERNAL PUBKEY (control[1..32])
     * -- a different field from negatives 1-3, and one that only changes the
     * answer if the taproot tweak is genuinely recomputed from it. */
    unsigned long csn = (X->ctrl_len < 0xfd) ? 1 : (X->ctrl_len <= 0xffff ? 3 : 5);
    unsigned long p = X->leaf_off + X->leaf_len + csn + 1;   /* control[1] */
    u8 save = tx[p]; tx[p] ^= 0x01;
    const char* rs="?";
    int rr = tx_verify_block_connect(tx,(u64)txlen,X->height,g_bh,&g_lst,g_tab,&rs);
    ck("tap_12items: flipping the control block's internal pubkey is REJECTED", rr==0);
    tx[p]=save;
    free(tx);
  }

  printf("\n== large fixtures (gitignored blob: tests/fixtures/%s)\n", TS_BIG_BLOB);
  {
    int n = load_blob(blobpath);
    if (!n) {
      printf("  SKIP: %s not present (regenerate with\n"
             "        python3 validation/fetch_tapscript_scale.py --big tests/fixtures).\n"
             "        The 371,967 B and 3,938,182 B leaf fixtures are NOT covered by this run.\n",
             blobpath);
    }
  }

  printf("\n%s (%d/%d)\n", fails?"TESTS FAILED":"ALL PASS", checks-fails, checks);
  return fails?1:0;
}
