/* test_scriptverify_parity.c -- the ASM-driven VerifyScript must agree with
 * the C reference, verdict AND ScriptError code, on every vector.
 *
 * The vectors are the genuine P2SH spends in p2sh_vectors.h, generated by
 * validation/gen_p2sh_vectors.py and already differentially validated against
 * Bitcoin Core's own interpreter (validation/p2sh_diff.py, zero divergence).
 * So agreement here is agreement with Core, transitively -- which is the
 * point: bitcoin_scriptverify.c is replacing bitcoin_verify.c's role, and a
 * replacement that changes a verdict is a consensus change.
 *
 * This test does NOT assert absolute codes; it asserts the two agree. An
 * absolute-value test would have to be updated whenever Core's enum shifts,
 * and that is exactly the staleness that made twelve tapscript assertions
 * wrong when the interpreter was corrected.
 */
#include <stdio.h>
#include <string.h>
#include <stdint.h>

extern int verify_script(const unsigned char* ss, unsigned long ssl,
                         const unsigned char* spk, unsigned long spl,
                         unsigned long long flags, unsigned long nIn,
                         const unsigned char* tx, unsigned long txlen,
                         unsigned char* work, unsigned long workcap);
extern int sv_verify_script(const unsigned char* ss, unsigned long ssl,
                            const unsigned char* spk, unsigned long spl,
                            uint64_t flags, unsigned long nIn,
                            const unsigned char* tx, unsigned long txlen,
                            unsigned char* work, unsigned long workcap);

#define FLAGS_MODERN 0x20e15ULL
#define FLAGS_PREB16 0x614ULL

#include "p2sh_vectors.h"

static int fails = 0, checks = 0;

static void cmp(const char* label,
                const unsigned char* ss, unsigned long ssn,
                const unsigned char* spk, unsigned long spkn,
                const unsigned char* tx, unsigned long txn,
                unsigned long long flags){
    static unsigned char w1[1<<20], w2[1<<20];
    int c_ref = verify_script(ss, ssn, spk, spkn, flags, 0, tx, txn, w1, sizeof w1);
    int c_asm = sv_verify_script(ss, ssn, spk, spkn, flags, 0, tx, txn, w2, sizeof w2);
    checks++;
    if (c_ref == c_asm)
        printf("ok  : %-42s both -> %d\n", label, c_ref);
    else {
        printf("FAIL: %-42s C ref -> %d, asm-driven -> %d\n", label, c_ref, c_asm);
        fails++;
    }
}

#define LEN(a) (unsigned long)sizeof(a)

int main(void){
    printf("---- scriptverify parity (asm script_eval vs C reference) ----\n");

    cmp("2of3 genuine spend (2/3 sigs)", SS_23, LEN(SS_23), SPK_23, LEN(SPK_23),
        TX_23, LEN(TX_23), FLAGS_MODERN);
    cmp("2of3 pre-BIP16 (P2SH off)", SS_23, LEN(SS_23), SPK_23, LEN(SPK_23),
        TX_23, LEN(TX_23), FLAGS_PREB16);
    cmp("2of3 wrong signature", SS_WRONG, LEN(SS_WRONG), SPK_23, LEN(SPK_23),
        TX_WRONG, LEN(TX_WRONG), FLAGS_MODERN);
    cmp("2of3 insufficient sigs", SS_INSUFF, LEN(SS_INSUFF), SPK_23, LEN(SPK_23),
        TX_INSUFF, LEN(TX_INSUFF), FLAGS_MODERN);
    cmp("2of3 null dummy", SS_NULLD, LEN(SS_NULLD), SPK_23, LEN(SPK_23),
        TX_NULLD, LEN(TX_NULLD), FLAGS_MODERN);
    cmp("2of3 non-pushonly redeem", SS_BADREDEEM, LEN(SS_BADREDEEM), SPK_23, LEN(SPK_23),
        TX_BADREDEEM, LEN(TX_BADREDEEM), FLAGS_MODERN);
    cmp("1of1 P2PKH redeem genuine", SS_1OF1, LEN(SS_1OF1), SPK_1OF1, LEN(SPK_1OF1),
        TX_1OF1, LEN(TX_1OF1), FLAGS_MODERN);
    cmp("1of1 wrong signature", SS_1OF1BAD, LEN(SS_1OF1BAD), SPK_1OF1, LEN(SPK_1OF1),
        TX_1OF1BAD, LEN(TX_1OF1BAD), FLAGS_MODERN);

    printf("\n%d check(s), %d divergence(s)\n", checks, fails);
    if (fails){ printf("PARITY FAILED\n"); return 1; }
    printf("ALL TESTS PASSED (0 failures)\n");
    return 0;
}
