/* test_mempool_policy.c -- drive the mempool POLICY layer through the vectors
 * generated by gen_mempool_policy_vectors.py (the independent Python oracle).
 *
 * For every scenario the C harness builds a fresh policy world (pol + state +
 * structural mempool + confirmed UTXO set), preloads the scenario's funded
 * confirmed outputs, and replays the ordered steps:
 *   - "add"     : mpool_policy_add(...)  -> verdict must equal oracle's
 *   - "present" : mpool_get(txid)        -> must equal oracle's (in/out of mp)
 *   - "est"     : mpool_policy_estimate_feerate() -> must equal oracle's EMA
 *
 * The policy module under test is bitcoin_mempool_policy.c (pure C glue over
 * the verified asm mempool + asm utxo). A mismatch with the oracle is a bug.
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "mempool_policy_vec.h"

/* ---- asm structural mempool ---- */
extern size_t mpool_struct_size(unsigned long slots);
extern void   mpool_init(void* mp, unsigned long slots, void* blob, unsigned long blob_cap);
extern long   mpool_put(void* mp, const unsigned char txid[32],
                        const unsigned char* tx, unsigned long txlen);
extern const unsigned char* mpool_get(void* mp, const unsigned char txid[32],
                                      unsigned long* out_len);
extern long   mpool_count(void* mp);
/* ---- asm UTXO set ---- */
extern size_t utxo_struct_size(unsigned long slots);
extern void   utxo_init(void* u, unsigned long slots, void* blob, unsigned long blob_cap);
extern long   utxo_put(void* u, const unsigned char txid[32], unsigned long index,
                       unsigned long long value, unsigned long height,
                       unsigned long is_coinbase, const unsigned char* script, unsigned long slen);
/* ---- policy module (bitcoin_mempool_policy.c) ---- */
extern size_t mpool_policy_state_size(unsigned n);
extern void   mpool_policy_state_init(void* st, unsigned n);
extern void   mpool_policy_init(void* pol, unsigned long long relay_fee_rate,
                                unsigned max_anc, unsigned max_anc_bytes,
                                unsigned max_desc, unsigned max_desc_bytes,
                                unsigned rbf_enabled);
extern void mpool_policy_set_acceptnonstd(void*, unsigned);
extern void mpool_policy_set_baremultisig(void*, unsigned);
static int test_bare_multisig(void);   /* defined below main */
extern long   mpool_policy_add(void* pol, void* st, void* mp,
                               const unsigned char* tx, unsigned long txlen,
                               const unsigned char txid[32], void* utxo);
extern unsigned long long mpool_policy_estimate_feerate(void* st);
extern const char* mpool_policy_reason(void* pol);

/* bitcoin_mempool_policy.c now calls mempool_resolve_confirmed_utxo instead
 * of utxo_get directly (see its own extern's comment) -- this harness still
 * wants the real, single-table bitcoin_utxo.asm behavior, so just pass
 * through unchanged. */
extern long utxo_get(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, unsigned long* height,
                     unsigned long* is_coinbase, const unsigned char** script,
                     unsigned long* slen);
long mempool_resolve_confirmed_utxo(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, const unsigned char** script,
                     unsigned long* slen){
    unsigned long h_unused, cb_unused;
    return utxo_get(u, txid, index, value, &h_unused, &cb_unused, script, slen);
}

static int hex_in(unsigned char* out, const char* h);

static int failures = 0;
#define MAXTX 4096

static int run_scenario(int si,
                        unsigned max_anc, unsigned max_anc_bytes,
                        unsigned max_desc, unsigned max_desc_bytes,
                        unsigned rbf,
                        const char* const* utxo_txid, const unsigned* utxo_idx,
                        const unsigned long long* utxo_val, unsigned nutxo,
                        unsigned nsteps,
                        const char* const* step_tx, const char* const* step_txid,
                        const unsigned* step_kind, const unsigned* step_expect,
                        const unsigned long long* step_arg);

int main(void){
    /* ---- scenario 0: core (fee / double-spend / RBF) ---- */
    run_scenario(0, SCEN0_MAXANC, SCEN0_MAXANC_B, SCEN0_MAXDESC, SCEN0_MAXDESC_B,
                 SCEN0_RBF, SCEN0_UTXO_TXID, SCEN0_UTXO_IDX, SCEN0_UTXO_VAL, SCEN0_NUTXO,
                 SCEN0_NSTEPS, SCEN0_STEP_TX, SCEN0_STEP_TXID, SCEN0_STEP_KIND,
                 SCEN0_STEP_EXPECT, SCEN0_STEP_ARG);
    /* ---- scenario 1: ancestor limit ---- */
    run_scenario(1, SCEN1_MAXANC, SCEN1_MAXANC_B, SCEN1_MAXDESC, SCEN1_MAXDESC_B,
                 SCEN1_RBF, SCEN1_UTXO_TXID, SCEN1_UTXO_IDX, SCEN1_UTXO_VAL, SCEN1_NUTXO,
                 SCEN1_NSTEPS, SCEN1_STEP_TX, SCEN1_STEP_TXID, SCEN1_STEP_KIND,
                 SCEN1_STEP_EXPECT, SCEN1_STEP_ARG);
    /* ---- scenario 2: descendant limit ---- */
    run_scenario(2, SCEN2_MAXANC, SCEN2_MAXANC_B, SCEN2_MAXDESC, SCEN2_MAXDESC_B,
                 SCEN2_RBF, SCEN2_UTXO_TXID, SCEN2_UTXO_IDX, SCEN2_UTXO_VAL, SCEN2_NUTXO,
                 SCEN2_NSTEPS, SCEN2_STEP_TX, SCEN2_STEP_TXID, SCEN2_STEP_KIND,
                 SCEN2_STEP_EXPECT, SCEN2_STEP_ARG);
    /* ---- scenario 3: fee estimator ---- */
    run_scenario(3, SCEN3_MAXANC, SCEN3_MAXANC_B, SCEN3_MAXDESC, SCEN3_MAXDESC_B,
                 SCEN3_RBF, SCEN3_UTXO_TXID, SCEN3_UTXO_IDX, SCEN3_UTXO_VAL, SCEN3_NUTXO,
                 SCEN3_NSTEPS, SCEN3_STEP_TX, SCEN3_STEP_TXID, SCEN3_STEP_KIND,
                 SCEN3_STEP_EXPECT, SCEN3_STEP_ARG);

    failures += test_bare_multisig();

    printf("\n%s (%d failures)\n", failures ? "TESTS FAILED" : "ALL TESTS PASSED", failures);
    return failures ? 1 : 0;
}


/* ---- -permitbaremultisig, through the REAL acceptance path ---------------
 * The option was already covered at the config layer and at the setter, but
 * not where it matters: the actual REJECTION. standard_checks() is static
 * behind mpol_add_core, so the only honest way to assert it is to build a
 * transaction with a bare multisig output and push it through
 * mpool_policy_add twice -- once with the option on, once off -- and require
 * the verdict to differ.
 *
 * Note this scenario deliberately does NOT set -acceptnonstdtxn, unlike the
 * fee/graph scenarios above: standardness is precisely what is under test. */
static int test_bare_multisig(void){
    int bad = 0;
    printf("== permitbaremultisig: the rejection itself ==\n");

    /* a 1-of-1 bare multisig: OP_1 <33-byte pubkey> OP_1 OP_CHECKMULTISIG */
    unsigned char spk[37];
    spk[0] = 0x51; spk[1] = 0x21;
    for (int i = 0; i < 33; i++) spk[2+i] = (unsigned char)(0x02 + (i & 1));  /* plausible compressed key */
    spk[35] = 0x51; spk[36] = 0xae;

    unsigned char prev[32]; memset(prev, 0x11, 32);

    /* build the raw tx by hand: 1 input (empty scriptSig), 1 bare-multisig output */
    unsigned char tx[256]; unsigned long n = 0;
    tx[n++]=0x02; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* version 2 */
    tx[n++]=0x01;                                                 /* 1 input   */
    memcpy(tx+n, prev, 32); n += 32;
    tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* vout 0    */
    tx[n++]=0x00;                                                 /* empty scriptSig (push-only) */
    tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff; tx[n++]=0xff;      /* sequence  */
    tx[n++]=0x01;                                                 /* 1 output  */
    { unsigned long long v = 100000ULL;                           /* well above dust */
      for (int i = 0; i < 8; i++) tx[n++] = (unsigned char)(v >> (8*i)); }
    tx[n++] = (unsigned char)sizeof spk;
    memcpy(tx+n, spk, sizeof spk); n += sizeof spk;
    tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00; tx[n++]=0x00;      /* locktime  */

    unsigned char txid[32]; memset(txid, 0x22, 32);

    for (int permit = 1; permit >= 0; permit--){
        static unsigned char pol[128];
        static unsigned char stbuf[1<<20];
        static unsigned char mp[40 + 4096*48 + 8];
        static unsigned char mblob[1<<20];
        static unsigned char ux[40 + 4096*48 + 8];
        static unsigned char ublob[1<<16];
        memset(stbuf, 0, sizeof stbuf);
        mpool_policy_init(pol, 1000 /* sat/kvB: 1 sat/vB, as before */, 25, 101000, 25, 101000, 1);
        mpool_policy_set_baremultisig(pol, (unsigned)permit);
        mpool_policy_state_init(stbuf, 256);
        mpool_init(mp, 4096, mblob, sizeof mblob);
        utxo_init(ux, 4096, ublob, sizeof ublob);
        /* fund it generously so the fee is never the reason for a rejection */
        utxo_put(ux, prev, 0, 1000000ULL, 0, 0, (const unsigned char*)"\x51", 1);

        long rv = mpool_policy_add(pol, stbuf, mp, tx, n, txid, ux);
        const char* why = mpool_policy_reason(pol);
        /* this API returns 1 for accepted and 0 for rejected -- NOT a negative
         * errno. Checking rv >= 0 makes both outcomes look like success, which
         * is how the first cut of this test "passed" the accept case while
         * proving nothing. */
        if (permit){
            if (rv == 1){ printf("  ok  permitbaremultisig=1 ACCEPTS a bare multisig output\n"); }
            else { printf("  FAIL permitbaremultisig=1 rejected it: %s\n", why ? why : "?"); bad++; }
        } else {
            if (rv == 0 && why && strcmp(why, "bare-multisig") == 0){
                printf("  ok  permitbaremultisig=0 REJECTS it, with reason \"bare-multisig\"\n");
            } else if (rv == 0){
                printf("  FAIL rejected, but for the wrong reason: %s\n", why ? why : "?"); bad++;
            } else { printf("  FAIL permitbaremultisig=0 still accepted it (rv=%ld)\n", rv); bad++; }
        }
    }
    return bad;
}

/* ---- run one scenario ---- */
static int run_scenario(int si,
                        unsigned max_anc, unsigned max_anc_bytes,
                        unsigned max_desc, unsigned max_desc_bytes,
                        unsigned rbf,
                        const char* const* utxo_txid, const unsigned* utxo_idx,
                        const unsigned long long* utxo_val, unsigned nutxo,
                        unsigned nsteps,
                        const char* const* step_tx, const char* const* step_txid,
                        const unsigned* step_kind, const unsigned* step_expect,
                        const unsigned long long* step_arg){
    /* policy config + state */
    static unsigned char pol[128];
    static unsigned char stbuf[1<<20];
    memset(stbuf, 0, sizeof stbuf);
    mpool_policy_init(pol, 1000 /* sat/kvB: 1 sat/vB, as before */, max_anc, max_anc_bytes, max_desc, max_desc_bytes, rbf);
    /* fixtures are synthetic, deliberately non-standard txs: run under
     * Core's own regtest escape hatch (-acceptnonstdtxn) so this test
     * keeps exercising fee/graph mechanics, not IsStandardTx. */
    mpool_policy_set_acceptnonstd(pol, 1);
    mpool_policy_state_init(stbuf, 256);

    /* structural mempool */
    static unsigned char mp[40 + 4096*48 + 8];
    static unsigned char mblob[1<<20];
    mpool_init(mp, 4096, mblob, sizeof mblob);

    /* confirmed UTXO set */
    static unsigned char ux[40 + 4096*48 + 8];
    static unsigned char ublob[1<<16];
    utxo_init(ux, 4096, ublob, sizeof ublob);
    for (unsigned i=0;i<nutxo;i++){
        unsigned char t[32];
        hex_in(t, utxo_txid[i]);
        utxo_put(ux, t, utxo_idx[i], utxo_val[i], 0, 0, (const unsigned char*)"\x51", 1);
    }

    printf("== scenario %d: %u steps ==\n", si, nsteps);
    unsigned ok=0, bad=0;
    for (unsigned i=0;i<nsteps;i++){
        switch (step_kind[i]){
        case 0: { /* add */
            unsigned char txbuf[MAXTX]; unsigned char txid[32];
            int n = hex_in(txbuf, step_tx[i]);
            hex_in(txid, step_txid[i]);
            long rv = mpool_policy_add(pol, stbuf, mp, txbuf, (unsigned long)n,
                                       txid, ux);
            int expect = (int)step_expect[i];
            if (rv == expect){ printf("  ok  : [%u] add  verdict=%ld (exp %d)\n",
                                      i, rv, expect); ok++;}
            else{ printf("  FAIL: [%u] add  verdict=%ld (exp %d) reason=%s\n",
                         i, rv, expect, mpool_policy_reason(pol)); bad++; failures++; }
            break;
        }
        case 1: { /* present */
            unsigned char txid[32];
            hex_in(txid, step_txid[i]);
            unsigned long len=0;
            const unsigned char* p = mpool_get(mp, txid, &len);
            int present = p!=NULL ? 1 : 0;
            int expect = (int)step_expect[i];
            if (present == expect){ printf("  ok  : [%u] mempool present=%d (exp %d)\n", i, present, expect); ok++;}
            else{ printf("  FAIL: [%u] mempool present=%d (exp %d)\n", i, present, expect); bad++; failures++; }
            break;
        }
        case 2: { /* est */
            unsigned long long got = mpool_policy_estimate_feerate(stbuf);
            unsigned long long expect = step_arg[i];
            /* allow EMA division differences of at most 1 sat/kB */
            long diff = (long)got - (long)expect; if (diff<0) diff=-diff;
            if (diff <= 1){ printf("  ok  : [%u] est feerate=%llu (exp %llu)\n", i, got, expect); ok++;}
            else{ printf("  FAIL: [%u] est feerate=%llu (exp %llu)\n", i, got, expect); bad++; failures++; }
            break;
        }
        default:
            printf("  FAIL: [%u] unknown kind %u\n", i, step_kind[i]); failures++;
        }
    }
    printf("  scenario %d: %u ok, %u bad\n", si, ok, bad);
    return bad?1:0;
}

static int hex_in(unsigned char* out, const char* h){
    int n = (int)strlen(h)/2;
    for (int i=0;i<n;i++){ unsigned v; sscanf(h+2*i,"%2x",&v); out[i]=(unsigned char)v; }
    return n;
}
