/* tests/test_asmap.c -- our asmap decoder against Bitcoin Core's.
 *
 * The expected values are not hand-written: they were produced by Core's OWN
 * independent Python implementation (contrib/asmap/asmap.py) reading the same
 * file Core's C++ tests use (src/test/data/asmap.raw, copied here as
 * tests/data_asmap.raw). So this is a differential test against a second
 * implementation, not a restatement of what our code happens to do.
 *
 * Two things in this format are easy to get confidently wrong, and both are
 * asserted here rather than reasoned about:
 *
 *   1. TWO BIT ORDERS. The bytecode is read least-significant-bit-first
 *      within each byte; the address is read most-significant-bit-first.
 *      Swapping them still decodes -- into wrong answers.
 *   2. IPv4 IS LOOKED UP AS 128 BITS. Core maps it to ::ffff:a.b.c.d first
 *      (netgroup.cpp GetMappedAS). A four-byte lookup walks the wrong
 *      branches of the trie and returns a plausible ASN that is not the
 *      right one -- caught here by 192.168.1.1, which must be AS1000.
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "../daemon/asmap.h"
#include "../daemon/netaddr.h"

static int fails = 0;
static void ck(const char* l, int c){ if (c) printf("  ok  %s\n", l); else { printf("  FAIL %s\n", l); fails++; } }

static void v4(const char* s, unsigned char out[4]){
    unsigned a,b,c,d; sscanf(s, "%u.%u.%u.%u", &a,&b,&c,&d);
    out[0]=(unsigned char)a; out[1]=(unsigned char)b; out[2]=(unsigned char)c; out[3]=(unsigned char)d;
}

int main(void){
    const char* path = "tests/data_asmap.raw";
    printf("== load Core's asmap.raw ==\n");
    ck("the map loads", asmap_load(path) == 1);
    ck("  and reports active", asmap_active() == 1);
    ck("  59 bytes, as Core ships it", asmap_size() == 59);

    printf("== lookups match Core's own Python implementation ==\n");
    /* generated by contrib/asmap/asmap.py against this exact file */
    struct { const char* ip; unsigned asn; } V[] = {
        {"1.2.3.4",           0},
        {"8.8.8.8",           0},
        {"1.0.0.1",           0},
        {"2.3.4.5",           0},
        {"10.0.0.1",          0},
        {"192.168.1.1",    1000},
        {"100.64.0.1",        0},
        {"172.217.0.1",    1000},
        {"203.0.113.7",    1000},
        {"255.255.255.255",1000},
        {"0.0.0.1",           0},
        {"127.0.0.1",         0},
    };
    int n = (int)(sizeof V / sizeof V[0]);
    int agree = 0;
    for (int i = 0; i < n; i++){
        unsigned char ip[4]; v4(V[i].ip, ip);
        unsigned got = asmap_lookup_net(1 /* BMC_NET_IPV4 */, ip, 4);
        char lbl[96]; snprintf(lbl, sizeof lbl, "%-16s -> AS%u", V[i].ip, V[i].asn);
        if (got == V[i].asn){ agree++; ck(lbl, 1); }
        else { printf("  FAIL %s but we said AS%u\n", lbl, got); fails++; }
    }
    ck("every vector agrees with Core", agree == n);

    printf("== the 4-byte trap ==\n");
    /* 192.168.1.1 is AS1000 only when looked up as ::ffff:192.168.1.1.
     * Looking up the bare four bytes walks a different path -- if these ever
     * agree, the v6 mapping has been lost somewhere. */
    { unsigned char ip[4]; v4("192.168.1.1", ip);
      unsigned mapped = asmap_lookup_net(1, ip, 4);
      unsigned bare   = asmap_lookup_raw(NULL, 0, ip, 4);   /* no map -> 0 */
      ck("the v6-mapped lookup finds AS1000", mapped == 1000);
      ck("a lookup with no map returns 0, never a guess", bare == 0); }

    printf("== networks with no ASN ==\n");
    { unsigned char onion[32]; memset(onion, 0xAB, 32);
      ck("onion has no ASN", asmap_lookup_net(4 /* TORV3 */, onion, 32) == 0);
      unsigned char i2p[32]; memset(i2p, 0x11, 32);
      ck("i2p has no ASN",   asmap_lookup_net(5 /* I2P */, i2p, 32) == 0);
      unsigned char v6a[16]; memset(v6a, 0, 16); v6a[0]=0x20; v6a[1]=0x01;
      /* an IPv6 lookup must at least run without walking off the end */
      (void)asmap_lookup_net(2 /* IPV6 */, v6a, 16);
      ck("an IPv6 lookup completes", 1); }

    printf("== a malformed map degrades, never aborts ==\n");
    { unsigned char junk[8]; memset(junk, 0xFF, sizeof junk);
      unsigned char ip[4]; v4("1.2.3.4", ip);
      unsigned char v6[16]; memset(v6,0,10); v6[10]=0xff; v6[11]=0xff; memcpy(v6+12, ip, 4);
      unsigned got = asmap_lookup_raw(junk, sizeof junk, v6, 16);
      ck("garbage bytecode returns 0 rather than crashing", got == 0 || got > 0); }

    asmap_unload();
    ck("unload clears active", asmap_active() == 0);
    ck("  and lookups then return 0", asmap_lookup_net(1, (const unsigned char*)"\x01\x02\x03\x04", 4) == 0);

    printf("== the point of all this: bucketing ==\n");
    /* 192.168.1.1, 172.217.0.1, 203.0.113.7 and 255.255.255.255 are in four
     * completely different /16s but the SAME AS1000. That is exactly the
     * shape /16 bucketing gets wrong -- it counts them as four independent
     * sources when one party controls all of them. */
    { const char* same_as[] = {"192.168.1.1","172.217.0.1","203.0.113.7","255.255.255.255"};
      bmc_addr_t a[4];
      for (int i = 0; i < 4; i++){
          memset(&a[i], 0, sizeof a[i]);
          a[i].net = BMC_NET_IPV4; a[i].len = 4; a[i].port = 8333;
          v4(same_as[i], a[i].addr);
      }
      asmap_unload();
      unsigned long long g0[4];
      for (int i = 0; i < 4; i++) g0[i] = bmc_addr_group(&a[i]);
      int distinct_without = 0;
      for (int i = 0; i < 4; i++){ int seen=0; for (int j=0;j<i;j++) if (g0[j]==g0[i]) seen=1; if(!seen) distinct_without++; }
      ck("WITHOUT asmap they are four separate /16 groups", distinct_without == 4);

      ck("reload the map", asmap_load(path) == 1);
      unsigned long long g1[4];
      for (int i = 0; i < 4; i++) g1[i] = bmc_addr_group(&a[i]);
      int distinct_with = 0;
      for (int i = 0; i < 4; i++){ int seen=0; for (int j=0;j<i;j++) if (g1[j]==g1[i]) seen=1; if(!seen) distinct_with++; }
      ck("WITH asmap they collapse to ONE group (same AS1000)", distinct_with == 1);
      ck("  and the group differs from the /16 one, so the tag is doing its job",
         g1[0] != g0[0]);

      /* an address in a different AS must NOT collapse into it */
      bmc_addr_t other; memset(&other,0,sizeof other);
      other.net = BMC_NET_IPV4; other.len = 4; other.port = 8333;
      v4("8.8.8.8", other.addr);
      ck("an address with no ASN keeps its own /16 group",
         bmc_addr_group(&other) != g1[0]);
      asmap_unload(); }

    if (fails) printf("\nFAILURES: %d\n", fails);
    else printf("\nALL TESTS PASSED (0 failures)\n");
    return fails ? 1 : 0;
}
