/* test_bip32_extkey.c -- verify the BIP32 full-path derivation + extended-key
 * (xprv/xpub) encoding built on top of the verified asm primitives
 * (bip32_master + bip32_ckd_priv) in bitcoin_bip32.asm.
 *
 * For every vector in bip32_extkey_vec.h (generated by the INDEPENDENT `bip32`
 * Python oracle + pure-Python base58check) it checks, end to end:
 *   1. bip32_derive_path  -> exact (k, c) for the full path
 *   2. scalar_to_pubkey   -> compressed pubkey
 *   3. bip32_fingerprint  -> node's own fingerprint == oracle
 *   4. bip32_extkey_serialize + base58check_encode -> xprv == oracle
 *   5. bip32_extkey_serialize (public) + base58check_encode -> xpub == oracle
 *   6. key -> address     -> P2PKH address == oracle
 *
 * The last two vectors are a BIP44 m/44'/0'/0'/0/0 and a BIP84 m/84'/0'/0'/0/0
 * receive path, tying key -> address -> extended key exactly as a wallet uses
 * them. The first is the canonical BIP32 test-vector-1 chain end.
 */
#include <stdio.h>
#include <string.h>

#include "bip32_extkey_vec.h"

/* ---------------- verified asm primitives ---------------- */
extern int  bip32_master(unsigned char k[32], unsigned char c[32],
                         const unsigned char* seed, long seedlen);
extern int  bip32_ckd_priv(unsigned char k[32], unsigned char c[32],
                           const unsigned char* kpar, const unsigned char* cpar,
                           unsigned index);
extern int  bip32_derive_path(unsigned char k[32], unsigned char c[32],
                              const unsigned char* seed, long seedlen,
                              const unsigned* indexes, long n);
extern void bip32_fingerprint(unsigned char fp[4], const unsigned char pub[33]);
extern int  bip32_extkey_serialize(unsigned char ser[78], int is_priv,
                                   unsigned char depth,
                                   const unsigned char parent_fp[4],
                                   unsigned child, const unsigned char c[32],
                                   const unsigned char* key, long keylen);
extern void scalar_to_pubkey(unsigned char pub[33], const unsigned char k[32]);
extern void hash160(unsigned char out[20], const void* in, long long len);
extern void base58check_encode(char* out, const unsigned char* payload,
                               long long paylen);

static int failures = 0;

static unsigned char hx_parse_byte(const char* s) {
    unsigned v;
    sscanf(s, "%2x", &v);
    return (unsigned char)v;
}
static void hx_to(unsigned char* dst, const char* hex, int n) {
    for (int i = 0; i < n; i++) dst[i] = hx_parse_byte(hex + i * 2);
}
static int hx_eq(const unsigned char* a, const unsigned char* b, int n) {
    return memcmp(a, b, (size_t)n) == 0;
}
static void pr_hex(const unsigned char* d, int n) {
    for (int i = 0; i < n; i++) printf("%02x", d[i]);
}
static int str_eq(const char* a, const char* b) { return strcmp(a, b) == 0; }

static int check_node(const unsigned char* seed, long seedlen,
                      const char* name, const unsigned* idx, long n,
                      const unsigned char* exp_k, const unsigned char* exp_c,
                      const unsigned char* exp_pub, const unsigned char* exp_fp,
                      unsigned depth, const unsigned char* exp_parent_fp,
                      unsigned child, const char* exp_xprv, const char* exp_xpub,
                      const char* exp_addr) {
    int ok = 1;
    unsigned char k[32], c[32];

    /* 1. full-path derivation */
    int r = bip32_derive_path(k, c, seed, seedlen, idx, n);
    if (r != 1 || !hx_eq(k, exp_k, 32) || !hx_eq(c, exp_c, 32)) {
        printf("FAIL %s derive_path (r=%d)\n  k got ", name, r); pr_hex(k, 32);
        printf("\n  k exp "); pr_hex(exp_k, 32); printf("\n  c got "); pr_hex(c, 32);
        printf("\n  c exp "); pr_hex(exp_c, 32); printf("\n");
        ok = 0;
    }

    unsigned char pub[33];
    scalar_to_pubkey(pub, k);
    if (!hx_eq(pub, exp_pub, 33)) {
        printf("FAIL %s pubkey\n  got ", name); pr_hex(pub, 33);
        printf("\n  exp "); pr_hex(exp_pub, 33); printf("\n");
        ok = 0;
    }

    /* 3. node's own fingerprint (HASH160(pub)[0..4]) */
    unsigned char fp[4];
    bip32_fingerprint(fp, pub);
    if (!hx_eq(fp, exp_fp, 4)) {
        printf("FAIL %s fingerprint\n  got ", name); pr_hex(fp, 4);
        printf("\n  exp "); pr_hex(exp_fp, 4); printf("\n");
        ok = 0;
    }

    /* 4+5. serialize xprv/xpub and base58check-encode */
    unsigned char ser[78];
    char b58[128];
    bip32_extkey_serialize(ser, 1, (unsigned char)depth, exp_parent_fp, child, c, k, 32);
    base58check_encode(b58, ser, 78);
    if (!str_eq(b58, exp_xprv)) {
        printf("FAIL %s xprv\n  got %s\n  exp %s\n", name, b58, exp_xprv);
        ok = 0;
    }

    /* xpub uses depth/fp/child of THIS node */
    bip32_extkey_serialize(ser, 0, (unsigned char)depth, exp_parent_fp, child, c, pub, 33);
    base58check_encode(b58, ser, 78);
    if (!str_eq(b58, exp_xpub)) {
        printf("FAIL %s xpub\n  got %s\n  exp %s\n", name, b58, exp_xpub);
        ok = 0;
    }

    /* 6. key -> P2PKH address (mainnet) from the derived pubkey */
    unsigned char h[20], payload[21];
    hash160(h, pub, 33);
    payload[0] = 0x00; memcpy(payload + 1, h, 20);
    base58check_encode(b58, payload, 21);
    if (!str_eq(b58, exp_addr)) {
        printf("FAIL %s address\n  got %s\n  exp %s\n", name, b58, exp_addr);
        ok = 0;
    }

    if (ok) printf("PASS %s\n", name);
    if (!ok) failures++;
    return ok;
}

int main(void) {
    unsigned char seed[16];
    for (int i = 0; i < 16; i++) seed[i] = (unsigned char)i;

    for (size_t i = 0; i < BIP32VEC_LEN; i++) {
        const struct bip32_vec* v = &BIP32VEC[i];
        unsigned char exp_k[32], exp_c[32], exp_pub[33], exp_fp[4], exp_pfp[4];
        hx_to(exp_k, v->k, 32); hx_to(exp_c, v->c, 32);
        hx_to(exp_pub, v->pub, 33); hx_to(exp_fp, v->fp, 4);
        hx_to(exp_pfp, v->parent_fp, 4);
        check_node(seed, 16, v->path, v->idx, (long)v->n,
                   exp_k, exp_c, exp_pub, exp_fp,
                   v->depth, exp_pfp, v->child, v->xprv, v->xpub, v->addr);
    }

    /* Known-vector MASTER extended keys (BIP32 test vector 1, chain m):
     * depth 0, parent fingerprint 0x00000000, child 0. */
    {
        unsigned char k[32], c[32];
        unsigned char zero4[4] = {0, 0, 0, 0};
        const char* exp_xprv =
            "xprv9s21ZrQH143K3QTDL4LXw2F7HEK3wJUD2nW2nRk4stbPy6cq3jPPqjiChkVvvNKmPGJxWUtg6LnF5kejMRNNU3TGtRBeJgk33yuGBxrMPHi";
        const char* exp_xpub =
            "xpub661MyMwAqRbcFtXgS5sYJABqqG9YLmC4Q1Rdap9gSE8NqtwybGhePY2gZ29ESFjqJoCu1Rupje8YtGqsefD265TMg7usUDFdp6W1EGMcet8";
        if (bip32_master(k, c, seed, 16) != 1) {
            printf("FAIL master return\n"); failures++;
        }
        unsigned char pub[33]; scalar_to_pubkey(pub, k);
        unsigned char ser[78]; char b58[128];
        bip32_extkey_serialize(ser, 1, 0, zero4, 0, c, k, 32);
        base58check_encode(b58, ser, 78);
        if (!str_eq(b58, exp_xprv)) {
            printf("FAIL master xprv\n  got %s\n  exp %s\n", b58, exp_xprv);
            failures++;
        } else printf("PASS master xprv\n");
        bip32_extkey_serialize(ser, 0, 0, zero4, 0, c, pub, 33);
        base58check_encode(b58, ser, 78);
        if (!str_eq(b58, exp_xpub)) {
            printf("FAIL master xpub\n  got %s\n  exp %s\n", b58, exp_xpub);
            failures++;
        } else printf("PASS master xpub\n");
    }

    printf(failures ? "FAILURES %d\n" : "ALL TESTS PASSED (0 failures)\n", failures);
    return failures ? 1 : 0;
}
