/* test_txval.c -- whole-transaction validation against the UTXO set.
 *
 * For a full serialized bitcoin tx it checks, in order:
 *   1) every input's outpoint (txid, index) is present AND unspent in the
 *      UTXO store  ->  double-spend guard
 *   2) every input's P2PKH signature verifies (asm verify_p2pkh over the
 *      SIGHASH_ALL digest built with that input's prevout script)
 *   3) sum(inputs) >= sum(outputs)  ->  a valid fee
 *
 * Reuses:
 *   bitcoin_utxo  (utxo_init/put/get -- the spend source)
 *   bitcoin_script(verify_p2pkh -- signature + pubkey check)
 *   bitcoin_tx    (tx_parse -- structural parse of the raw tx)
 *
 * The signed transactions and their UTXO preloads come from
 * txval_vec.h (generated by gen_txval_vectors.py, genuine ECDSA spends over
 * the asm SIGHASH_ALL layout).
 */
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "txval_vec.h"

/* --- asm externs --- */
extern int  tx_parse(void* info, const unsigned char* tx, unsigned long txlen);
extern void utxo_init(void* u, unsigned long slots, void* blob, unsigned long cap);
extern long utxo_put(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long value, unsigned long height,
                     unsigned long is_coinbase, const unsigned char* script, unsigned long slen);
extern long utxo_get(void* u, const unsigned char txid[32], unsigned long index,
                     unsigned long long* value, unsigned long* height,
                     unsigned long* is_coinbase, const unsigned char** script, unsigned long* slen);
extern int  verify_p2pkh(const unsigned char* tx, unsigned long txlen,
                         unsigned long input_index,
                         const unsigned char* prevout_script, unsigned long prevout_len,
                         unsigned char* work, unsigned long cap);

/* --- txinfo struct (mirrors the 64-byte layout filled by tx_parse) --- */
typedef struct {
    unsigned long long tx_len;            /* +0  */
    unsigned int version;                 /* +8  */
    unsigned int n_in;                    /* +12 */
    unsigned int n_out;                   /* +16 */
    unsigned int locktime;                /* +20 */
    unsigned long long in0_script_off;    /* +24 */
    unsigned long long in0_script_len;    /* +32 */
    unsigned long long out0_value_off;    /* +40 */
    unsigned long long out0_script_off;   /* +48 */
    unsigned long long out0_script_len;   /* +56 */
} txinfo;

/* ========================================================================== */
/* tiny CompactSize / serialization helpers                                  */
/* ========================================================================== */
static unsigned long rd_varint(const unsigned char* p, const unsigned char** adv) {
    unsigned long v = *p++;
    if (v < 0xfd) { *adv = p; return v; }
    if (v == 0xfd) { v = (unsigned long)p[0] | ((unsigned long)p[1] << 8); p += 2; }
    else if (v == 0xfe) { v = 0; for (int i = 0; i < 4; i++) v |= (unsigned long)p[i] << (8*i); p += 4; }
    else { v = 0; for (int i = 0; i < 8; i++) v |= (unsigned long)p[i] << (8*i); p += 8; }
    *adv = p;
    return v;
}

/* Walk to input i, returning its outpoint (txid, index). */
static int input_outpoint(const unsigned char* tx, unsigned int i,
                          unsigned char txid[32], unsigned long* index) {
    const unsigned char* p = tx + 4;                 /* skip version */
    unsigned long n_in = rd_varint(p, &p);
    if (i >= n_in) return 0;
    for (unsigned int j = 0; j <= i; j++) {
        memcpy(txid, p, 32);
        *index = (unsigned long)p[32] | ((unsigned long)p[33] << 8)
               | ((unsigned long)p[34] << 16) | ((unsigned long)p[35] << 24);
        p += 36;
        unsigned long sl = rd_varint(p, &p);
        p += sl + 4;                                 /* script + sequence */
    }
    return 1;
}

/* ========================================================================== */
/* The whole-transaction validator.                                           */
/* Returns 1 valid, 0 invalid (with a reason printed).                         */
/* ========================================================================== */
static int validate_tx(const unsigned char* tx, unsigned long txlen,
                       void* utxo, unsigned char* work, unsigned long workcap) {
    txinfo info;
    if (tx_parse(&info, tx, txlen) != 1) {
        printf("  [parse] malformed tx\n");
        return 0;
    }
    if (info.n_in == 0 || info.n_out == 0) {
        printf("  [shape] empty input/output list\n");
        return 0;
    }

    /* Pass 1 -- double-spend guard: every outpoint must exist in the UTXO set. */
    unsigned long long total_in = 0;
    const unsigned char* scripts[64];
    unsigned long slens[64];
    unsigned long long vals[64];
    for (unsigned int i = 0; i < info.n_in && i < 64; i++) {
        unsigned char txid[32];
        unsigned long index;
        const unsigned char* s = tx;
        (void)input_outpoint(s, i, txid, &index);

        unsigned long long val; const unsigned char* sp; unsigned long sl, h_unused, cb_unused;
        if (utxo_get(utxo, txid, index, &val, &h_unused, &cb_unused, &sp, &sl) != 1) {
            printf("  [double-spend] input %u (txid %02x%02x..%02x idx %lu) "
                   "absent/unspent\n",
                   i, txid[0], txid[1], txid[31], index);
            return 0;
        }
        scripts[i] = sp; slens[i] = sl; vals[i] = val;
        total_in += val;
    }

    /* Pass 2 -- signature: every input's P2PKH spend must verify. */
    for (unsigned int i = 0; i < info.n_in && i < 64; i++) {
        if (verify_p2pkh(tx, txlen, i, scripts[i], slens[i], work, workcap) != 1) {
            printf("  [sig] input %u signature does not verify\n", i);
            return 0;
        }
    }

    /* Pass 3 -- fee: sum(outputs) must not exceed sum(inputs). */
    unsigned long long total_out = 0;
    {
        const unsigned char* p = tx + 4;
        (void)rd_varint(p, &p);                      /* n_in */
        for (unsigned int i = 0; i < info.n_in; i++) {
            p += 36;
            unsigned long sl = rd_varint(p, &p);
            p += sl + 4;
        }
        (void)rd_varint(p, &p);                      /* n_out */
        for (unsigned int i = 0; i < info.n_out; i++) {
            unsigned long long v = 0;
            for (int j = 0; j < 8; j++) v |= (unsigned long long)p[j] << (8*j);
            p += 8;
            unsigned long sl = rd_varint(p, &p);
            p += sl;
            total_out += v;
        }
    }
    if (total_out > total_in) {
        printf("  [fee] in=%llu out=%llu (outputs exceed inputs)\n",
               total_in, total_out);
        return 0;
    }

    return 1;
}

/* ========================================================================== */
/* harness                                                                   */
/* ========================================================================== */
static int fails = 0;
static void ck(const char* label, int got, int expected) {
    if (got == expected) printf("ok  : %s\n", label);
    else { printf("FAIL: %s (got %d exp %d)\n", label, got, expected); fails++; }
}

static void hex_in(unsigned char* out, const char* h) {
    int n = (int)(strlen(h)) / 2;
    for (int i = 0; i < n; i++) {
        unsigned int v;
        sscanf(h + 2 * i, "%2x", &v);
        out[i] = (unsigned char)v;
    }
}

static void preload_utxo(void* utxo) {
    /* one utxo entry per element in txval_vec.h */
    struct { const char* txid; unsigned long idx;
             unsigned long long val; const char* script; } e[] = {
        { U_v1_input0_TXID, U_v1_input0_IDX, U_v1_input0_VAL, U_v1_input0_SCRIPT },
        { U_v1_input1_TXID, U_v1_input1_IDX, U_v1_input1_VAL, U_v1_input1_SCRIPT },
        { U_v2_input0_TXID, U_v2_input0_IDX, U_v2_input0_VAL, U_v2_input0_SCRIPT },
        { U_v4_input0_TXID, U_v4_input0_IDX, U_v4_input0_VAL, U_v4_input0_SCRIPT },
        { U_v5_input0_TXID, U_v5_input0_IDX, U_v5_input0_VAL, U_v5_input0_SCRIPT },
        { U_v6_input0_TXID, U_v6_input0_IDX, U_v6_input0_VAL, U_v6_input0_SCRIPT },
    };
    for (int i = 0; i < (int)(sizeof e / sizeof e[0]); i++) {
        unsigned char t[32], sc[64];
        int sn = (int)(strlen(e[i].script)) / 2;
        hex_in(t, e[i].txid);
        hex_in(sc, e[i].script);
        utxo_put(utxo, t, e[i].idx, e[i].val, 0, 0, sc, sn);
    }
}

static void run_case(const char* label, const char* txhex, void* utxo,
                     unsigned char* work, unsigned long workcap, int expected) {
    unsigned char tx[2048];
    int n = (int)(strlen(txhex)) / 2;
    hex_in(tx, txhex);
    int r = validate_tx(tx, (unsigned long)n, utxo, work, workcap);
    printf("  >> %s -> %d (expected %d)\n", label, r, expected);
    ck(label, r, expected);
}

int main(void) {
    static unsigned char ux[40 + 512 * 48 + 8];
    static unsigned char ublob[1 << 16];
    static unsigned char work[8192];
    utxo_init(ux, 512, ublob, sizeof ublob);
    preload_utxo(ux);

    run_case("valid 2in/2out (real sigs, fee 20000)",  TX_V1, ux, work, sizeof work, 1);
    run_case("valid 1in/1out (real sig,  fee 10000)",  TX_V2, ux, work, sizeof work, 1);
    run_case("double-spend: outpoint absent",           TX_V3, ux, work, sizeof work, 0);
    run_case("fee fail: outputs exceed inputs",         TX_V4, ux, work, sizeof work, 0);
    run_case("sig fail: empty scriptSig",               TX_V5, ux, work, sizeof work, 0);
    run_case("sig fail: wrong signing key",             TX_V6, ux, work, sizeof work, 0);

    printf("\n%s (%d failures)\n", fails ? "TESTS FAILED" : "ALL TESTS PASSED", fails);
    return fails ? 1 : 0;
}
