/* tests/test_verify_core_vectors.c -- whole-input spends signed and judged by
 * Bitcoin Core (tests/verify_core_vectors.h, generated by the manual
 * tests/fuzz_verify_diff), replayed through the exact verifier calls
 * daemon/tx_verify.c makes: sv_verify_script (legacy, witness-stripped
 * view), sv_classify_segwit + sv_verify_witness_v0 (witness v0, native and
 * P2SH-wrapped), taproot_verify_input (key path and script path, stripped
 * tx). Verdict must match Core's; the error code too where our side has one
 * (legacy and v0). The gate's memory of the 2026-09-02 differential without
 * needing Core's build. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
typedef uint8_t u8; typedef uint32_t u32; typedef uint64_t u64;
#include "verify_core_vectors.h"
extern int sv_verify_script(const unsigned char*, unsigned long, const unsigned char*, unsigned long, u64, unsigned long, const unsigned char*, unsigned long, unsigned char*, unsigned long);
extern int sv_classify_segwit(const u8* spk, u32 spl, const u8* ss, u32 ssl, u32* version, const u8** prog, u32* proglen, int* wrapped);
extern int sv_verify_witness_v0(const u8* prog, u32 proglen, const u8* const* wit, const u32* witlen, u32 nwit, u64 amount, u64 flags, unsigned long nIn, const u8* tx, unsigned long txlen, unsigned char* work, unsigned long workcap);
extern int taproot_verify_input(const u8* spk, const u8* const* wit, const u32* witlen, u32 nwit, const u8* tx, int64_t txlen, int64_t n_in, const u8* prevouts, const u8* amounts, const u8* spks, int64_t num_inputs, const char** reason);
long mempool_resolve_confirmed_utxo(void* u, const unsigned char txid[32], unsigned long index, unsigned long long* value, const unsigned char** script, unsigned long* slen){ (void)u; (void)txid; (void)index; (void)value; (void)script; (void)slen; return 0; }
#define F_WITNESS (1ull<<11)
#define F_DISC_WPROG (1ull<<12)
#define F_TAPROOT (1ull<<17)
static int fails = 0;
static int unhex(const char* h, u8* out, int cap){ int n = 0; for (const char* p = h; p[0] && p[1] && n < cap; p += 2){ unsigned v; sscanf(p, "%2x", &v); out[n++] = (u8)v; } return n; }
/* ---- minimal tx parser (witness form or legacy) ---- */
#define MAXIN 4
#define MAXWIT 8
typedef struct { const u8* p; u32 n; } sl;
typedef struct { u8 txid[32]; u32 vout; sl ss; u32 seq; int nwit; const u8* wit[MAXWIT]; u32 witlen[MAXWIT]; u64 amount; sl spk; } vin;
static u64 rcs(const u8* b, size_t* p){ u8 c = b[(*p)++]; if (c < 0xfd) return c; if (c == 0xfd){ u64 v = b[*p] | (b[*p+1] << 8); *p += 2; return v; } if (c == 0xfe){ u64 v = 0; for (int i = 0; i < 4; i++) v |= (u64)b[*p+i] << (8*i); *p += 4; return v; } u64 v = 0; for (int i = 0; i < 8; i++) v |= (u64)b[*p+i] << (8*i); *p += 8; return v; }
static u32 r32(const u8* b, size_t* p){ u32 v = b[*p] | (b[*p+1] << 8) | (b[*p+2] << 16) | ((u32)b[*p+3] << 24); *p += 4; return v; }
static int parse_tx(const u8* b, size_t n, vin* in, int* nin){
    size_t p = 0; r32(b, &p); int wit = 0; if (b[p] == 0 && b[p+1] == 1){ wit = 1; p += 2; }
    *nin = (int)rcs(b, &p); if (*nin > MAXIN) return 0;
    for (int i = 0; i < *nin; i++){ memcpy(in[i].txid, b + p, 32); p += 32; in[i].vout = r32(b, &p); in[i].ss.n = (u32)rcs(b, &p); in[i].ss.p = b + p; p += in[i].ss.n; in[i].seq = r32(b, &p); in[i].nwit = 0; }
    int nout = (int)rcs(b, &p); for (int i = 0; i < nout; i++){ p += 8; u64 l = rcs(b, &p); p += l; }
    if (wit) for (int i = 0; i < *nin; i++){ in[i].nwit = (int)rcs(b, &p); for (int k = 0; k < in[i].nwit; k++){ in[i].witlen[k] = (u32)rcs(b, &p); in[i].wit[k] = b + p; p += in[i].witlen[k]; } }
    p += 4; return p == n;
}
/* the witness-stripped serialization (what daemon/tx_verify.c hands the legacy and taproot verifiers) */
static size_t strip(const u8* b, size_t n, u8* out){
    size_t p = 0, o = 0; memcpy(out, b, 4); p = 4; o = 4; int wit = 0; if (b[p] == 0 && b[p+1] == 1){ wit = 1; p += 2; }
    size_t s = p; int nin = (int)rcs(b, &p); for (int i = 0; i < nin; i++){ p += 36; u64 l = rcs(b, &p); p += l + 4; }
    int nout = (int)rcs(b, &p); for (int i = 0; i < nout; i++){ p += 8; u64 l = rcs(b, &p); p += l; }
    memcpy(out + o, b + s, p - s); o += p - s;
    if (wit) for (int i = 0; i < nin; i++){ int nw = (int)rcs(b, &p); for (int k = 0; k < nw; k++){ u64 l = rcs(b, &p); p += l; } }
    memcpy(out + o, b + p, 4); o += 4; return o;
}
static u8 work[1 << 16];
int main(void){
    static u8 tx[8000], sp[4000], lt[8000]; static vin in[MAXIN];
    for (size_t v = 0; v < sizeof VVEC / sizeof VVEC[0]; v++){
        const struct vvec* V = &VVEC[v]; int n = unhex(V->tx, tx, sizeof tx), spn = unhex(V->spent, sp, sizeof sp); int nin = 0;
        if (!parse_tx(tx, (size_t)n, in, &nin)){ printf("  FAIL %s/%s: tx parse\n", V->tmpl, V->mut); fails++; continue; }
        size_t p = 0; for (int i = 0; i < nin && p < (size_t)spn; i++){ u64 a = 0; for (int k = 0; k < 8; k++) a |= (u64)sp[p+k] << (8*k); p += 8; in[i].amount = a; in[i].spk.n = (u32)rcs(sp, &p); in[i].spk.p = sp + p; p += in[i].spk.n; }
        vin* I = &in[V->nIn]; u64 flags = V->flags; int ook = 0, oerr = 0; const char* reason = ""; size_t ltn = strip(tx, (size_t)n, lt);
        if (I->spk.n == 34 && I->spk.p[0] == 0x51 && I->spk.p[1] == 0x20 && (flags & F_TAPROOT)){
            static u8 prevouts[36*MAXIN], amounts[8*MAXIN], spks[2000]; int so = 0;
            for (int i = 0; i < nin; i++){ memcpy(prevouts + 36*i, in[i].txid, 32); for (int k = 0; k < 4; k++) prevouts[36*i+32+k] = (in[i].vout >> (8*k)) & 255; for (int k = 0; k < 8; k++) amounts[8*i+k] = (in[i].amount >> (8*k)) & 255; spks[so++] = (u8)in[i].spk.n; memcpy(spks + so, in[i].spk.p, in[i].spk.n); so += in[i].spk.n; }
            oerr = -1; ook = (I->ss.n == 0 && I->nwit > 0) ? taproot_verify_input(I->spk.p, I->wit, I->witlen, (u32)I->nwit, lt, (int64_t)ltn, V->nIn, prevouts, amounts, spks, nin, &reason) : 0;
        } else {
            int done = 0;
            if (flags & F_WITNESS){ u32 wver = 0, wplen = 0; const u8* wprog = 0; int wrapped = 0;
                int cls = sv_classify_segwit(I->spk.p, I->spk.n, I->ss.p, I->ss.n, &wver, &wprog, &wplen, &wrapped);
                if (cls < 0){ oerr = 42; ook = 0; done = 1; }
                else if (cls > 0){ done = 1;
                    if (!wrapped && I->ss.n != 0){ oerr = 41; ook = 0; }
                    else if (wver == 0){
                        if (wplen == 20 && I->nwit != 2){ oerr = 40; ook = 0; }
                        else if (wplen == 32 && I->nwit < 1){ oerr = 39; ook = 0; }
                        else { oerr = sv_verify_witness_v0(wprog, wplen, I->wit, I->witlen, (u32)I->nwit, I->amount, flags, (unsigned long)V->nIn, tx, (unsigned long)n, work, sizeof work); ook = oerr == 0; }
                    } else if (flags & F_DISC_WPROG){ oerr = 34; ook = 0; } else ook = 1; } }
            if (!done){ oerr = sv_verify_script(I->ss.p, I->ss.n, I->spk.p, I->spk.n, flags, (unsigned long)V->nIn, lt, (unsigned long)ltn, work, sizeof work); ook = oerr == 0; if (ook && I->nwit && (flags & F_WITNESS)){ oerr = 43; ook = 0; } }
        }
        int good = (ook == V->ok) && (ook || oerr < 0 || oerr == V->err);
        if (!good){ printf("  FAIL %-18s %-20s ours %d/%d %s  Core %d/%d\n", V->tmpl, V->mut, ook, oerr, reason, V->ok, V->err); fails++; }
    }
    printf("%zu Core-judged spends replayed; %s (%d failures)\n", sizeof VVEC / sizeof VVEC[0], fails ? "TESTS FAILED" : "ALL PASS", fails); return fails ? 1 : 0;
}
