/* GENERATED by validation/gen_script_flags.py -- DO NOT EDIT.
 * C mirror of script_flags_consts.inc: the buried-deployment heights this
 * node ENFORCES, read out of Core's kernel/chainparams.cpp (CMainParams).
 * getdeploymentinfo reports these, so what the RPC says and what the
 * script-flag path does cannot drift apart. Re-run after a Core upgrade.
 */
#ifndef SCRIPT_FLAGS_CONSTS_H
#define SCRIPT_FLAGS_CONSTS_H

#define SFC_HEIGHT_BIP34  227931
#define SFC_HEIGHT_DERSIG 363725   /* BIP66 */
#define SFC_HEIGHT_CLTV   388381   /* BIP65 */
#define SFC_HEIGHT_CSV    419328
#define SFC_HEIGHT_SEGWIT 481824   /* WITNESS + NULLDUMMY (BIP147) */

/* signet (SigNetParams) */
#define SFC_S_HEIGHT_BIP34  1
#define SFC_S_HEIGHT_DERSIG 1   /* BIP66 */
#define SFC_S_HEIGHT_CLTV   1   /* BIP65 */
#define SFC_S_HEIGHT_CSV    1
#define SFC_S_HEIGHT_SEGWIT 1

/* regtest (CRegTestParams) */
#define SFC_R_HEIGHT_BIP34  1
#define SFC_R_HEIGHT_DERSIG 1   /* BIP66 */
#define SFC_R_HEIGHT_CLTV   1   /* BIP65 */
#define SFC_R_HEIGHT_CSV    1
#define SFC_R_HEIGHT_SEGWIT 0

/* testnet4 (CTestNet4Params) */
#define SFC_T_HEIGHT_BIP34  1
#define SFC_T_HEIGHT_DERSIG 1   /* BIP66 */
#define SFC_T_HEIGHT_CLTV   1   /* BIP65 */
#define SFC_T_HEIGHT_CSV    1
#define SFC_T_HEIGHT_SEGWIT 1

#endif
