/* GENERATED by validation/gen_script_error_defines.py -- DO NOT EDIT.
 * Bitcoin Core ScriptError values, read from Core's own script_error.h.
 * The asm interpreter (bitcoin_interp.asm) is the authoritative consensus
 * implementation and emits these values directly; this header exists so C
 * tests and wrappers compare against the same numbers rather than a
 * hand-copied enum. Re-run the generator after a Core upgrade. */
#ifndef SCRIPT_ERROR_CODES_H
#define SCRIPT_ERROR_CODES_H

#define SCRIPT_ERR_OK                                    0
#define SCRIPT_ERR_UNKNOWN_ERROR                         1
#define SCRIPT_ERR_EVAL_FALSE                            2
#define SCRIPT_ERR_OP_RETURN                             3
#define SCRIPT_ERR_SCRIPTNUM                             4
#define SCRIPT_ERR_SCRIPT_SIZE                           5
#define SCRIPT_ERR_PUSH_SIZE                             6
#define SCRIPT_ERR_OP_COUNT                              7
#define SCRIPT_ERR_STACK_SIZE                            8
#define SCRIPT_ERR_SIG_COUNT                             9
#define SCRIPT_ERR_PUBKEY_COUNT                          10
#define SCRIPT_ERR_VERIFY                                11
#define SCRIPT_ERR_EQUALVERIFY                           12
#define SCRIPT_ERR_CHECKMULTISIGVERIFY                   13
#define SCRIPT_ERR_CHECKSIGVERIFY                        14
#define SCRIPT_ERR_NUMEQUALVERIFY                        15
#define SCRIPT_ERR_BAD_OPCODE                            16
#define SCRIPT_ERR_DISABLED_OPCODE                       17
#define SCRIPT_ERR_INVALID_STACK_OPERATION               18
#define SCRIPT_ERR_INVALID_ALTSTACK_OPERATION            19
#define SCRIPT_ERR_UNBALANCED_CONDITIONAL                20
#define SCRIPT_ERR_NEGATIVE_LOCKTIME                     21
#define SCRIPT_ERR_UNSATISFIED_LOCKTIME                  22
#define SCRIPT_ERR_SIG_HASHTYPE                          23
#define SCRIPT_ERR_SIG_DER                               24
#define SCRIPT_ERR_MINIMALDATA                           25
#define SCRIPT_ERR_SIG_PUSHONLY                          26
#define SCRIPT_ERR_SIG_HIGH_S                            27
#define SCRIPT_ERR_SIG_NULLDUMMY                         28
#define SCRIPT_ERR_PUBKEYTYPE                            29
#define SCRIPT_ERR_CLEANSTACK                            30
#define SCRIPT_ERR_MINIMALIF                             31
#define SCRIPT_ERR_SIG_NULLFAIL                          32
#define SCRIPT_ERR_DISCOURAGE_UPGRADABLE_NOPS            33
#define SCRIPT_ERR_DISCOURAGE_UPGRADABLE_WITNESS_PROGRAM 34
#define SCRIPT_ERR_DISCOURAGE_UPGRADABLE_TAPROOT_VERSION 35
#define SCRIPT_ERR_DISCOURAGE_OP_SUCCESS                 36
#define SCRIPT_ERR_DISCOURAGE_UPGRADABLE_PUBKEYTYPE      37
#define SCRIPT_ERR_WITNESS_PROGRAM_WRONG_LENGTH          38
#define SCRIPT_ERR_WITNESS_PROGRAM_WITNESS_EMPTY         39
#define SCRIPT_ERR_WITNESS_PROGRAM_MISMATCH              40
#define SCRIPT_ERR_WITNESS_MALLEATED                     41
#define SCRIPT_ERR_WITNESS_MALLEATED_P2SH                42
#define SCRIPT_ERR_WITNESS_UNEXPECTED                    43
#define SCRIPT_ERR_WITNESS_PUBKEYTYPE                    44
#define SCRIPT_ERR_SCHNORR_SIG_SIZE                      45
#define SCRIPT_ERR_SCHNORR_SIG_HASHTYPE                  46
#define SCRIPT_ERR_SCHNORR_SIG                           47
#define SCRIPT_ERR_TAPROOT_WRONG_CONTROL_SIZE            48
#define SCRIPT_ERR_TAPSCRIPT_VALIDATION_WEIGHT           49
#define SCRIPT_ERR_TAPSCRIPT_CHECKMULTISIG               50
#define SCRIPT_ERR_TAPSCRIPT_MINIMALIF                   51
#define SCRIPT_ERR_TAPSCRIPT_EMPTY_PUBKEY                52
#define SCRIPT_ERR_OP_CODESEPARATOR                      53
#define SCRIPT_ERR_SIG_FINDANDDELETE                     54
#define SCRIPT_ERR_ERROR_COUNT                           55

#endif
