/* daemon/banlist.c -- the ban list survives a restart, as Core's does.
 *
 * Core keeps <datadir>/banlist.json and writes it whenever the list changes
 * (banman.cpp DumpBanlist) and at shutdown; it loads it at startup and sweeps
 * entries whose ban has expired. The file it writes is:
 *
 *   { "_warning_": "...",
 *     "banned_nets": [ { "address": "1.2.3.0/24", "version": 1,
 *                        "ban_created": 1757000000,
 *                        "banned_until": 1757086400 }, ... ] }
 *
 * (addrdb.cpp; the four key names and the version constant are
 * net_types.cpp BANMAN_JSON_* and CBanEntry::CURRENT_VERSION.)
 *
 * This node banned only in memory: every restart forgave every ban. The
 * behavioural-compatibility register carried it as PARTIAL -- "scored ...
 * not persisted across restart". A peer banned for a consensus violation
 * came back the moment the node did.
 *
 * Writes are tmp + fsync + rename + directory fsync, the same discipline the
 * UTXO checkpoint uses: a half-written ban list is worse than none, because
 * it silently forgives whatever it truncates. */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include "banlist.h"
#include "../rpc_json.h"

#define BANLIST_NAME "banlist.json"
#define BANLIST_TMP  "banlist.json.tmp"
#define BAN_ENTRY_VERSION 1        /* CBanEntry::CURRENT_VERSION */
static const char* BAN_WARNING =
    "This file is automatically generated and updated by Bitcoin Core. "
    "Please do not edit this file while the node is running, as any changes "
    "might be ignored or overwritten.";

/* Serialize `n` entries and replace banlist.json atomically. 0 on success. */
int banlist_save(const ban_entry_t* e, int n)
{
    rj_val* root = rj_obj();
    rj_obj_set(root, "_warning_", rj_str(BAN_WARNING));
    rj_val* arr = rj_arr();
    for (int i = 0; i < n; i++){
        if (!e[i].subnet[0] || e[i].until <= 0) continue;
        rj_val* o = rj_obj();
        rj_obj_set(o, "address",      rj_str(e[i].subnet));
        rj_obj_set(o, "version",      rj_numf("%d", BAN_ENTRY_VERSION));
        rj_obj_set(o, "ban_created",  rj_numf("%lld", (long long)e[i].created));
        rj_obj_set(o, "banned_until", rj_numf("%lld", (long long)e[i].until));
        rj_arr_push(arr, o);
    }
    rj_obj_set(root, "banned_nets", arr);
    long tlen = 0;
    char* txt = rj_write_alloc(root, 1 /* pretty, as Core writes it */, &tlen);
    rj_free(root);
    if (!txt || tlen <= 0){ free(txt); return -1; }

    int rc = -1;
    int fd = open(BANLIST_TMP, O_WRONLY|O_CREAT|O_TRUNC, 0644);
    if (fd >= 0){
        size_t len = (size_t)tlen, off = 0;
        while (off < len){
            ssize_t w = write(fd, txt + off, len - off);
            if (w <= 0) break;
            off += (size_t)w;
        }
        if (off == len && fsync(fd) == 0){
            close(fd); fd = -1;
            if (rename(BANLIST_TMP, BANLIST_NAME) == 0){
                int dfd = open(".", O_RDONLY);
                if (dfd >= 0){ fsync(dfd); close(dfd); }
                rc = 0;
            }
        }
        if (fd >= 0) close(fd);
    }
    if (rc != 0) unlink(BANLIST_TMP);
    free(txt);
    return rc;
}

/* Load banlist.json, dropping entries whose ban has already expired (Core
 * sweeps on load). Returns the number handed to `add`, or -1 if the file
 * could not be read; a missing file is 0, not an error. */
int banlist_load(long long now, int (*add)(const char* subnet, long long until, long long created))
{
    int fd = open(BANLIST_NAME, O_RDONLY);
    if (fd < 0) return 0;
    static char buf[1 << 16];
    ssize_t n = read(fd, buf, sizeof buf - 1);
    close(fd);
    if (n <= 0) return -1;
    buf[n] = 0;

    rj_val* root = rj_parse(buf, (size_t)n);
    if (!root || root->typ != RJ_OBJ){ if (root) rj_free(root); return -1; }
    rj_val* arr = rj_obj_get(root, "banned_nets");
    if (!arr || arr->typ != RJ_ARR){ rj_free(root); return -1; }

    int loaded = 0, expired = 0;
    for (size_t i = 0; i < arr->nitems; i++){
        rj_val* o = arr->items[i];
        if (!o || o->typ != RJ_OBJ) continue;
        rj_val* a = rj_obj_get(o, "address");
        rj_val* u = rj_obj_get(o, "banned_until");
        rj_val* c = rj_obj_get(o, "ban_created");
        if (!a || a->typ != RJ_STR || !a->str || !u || u->typ != RJ_NUM) continue;
        long long until   = strtoll(u->str, NULL, 10);
        long long created = (c && c->typ == RJ_NUM && c->str) ? strtoll(c->str, NULL, 10) : 0;
        if (until <= now){ expired++; continue; }        /* Core sweeps these */
        if (add(a->str, until, created)) loaded++;
    }
    rj_free(root);
    if (loaded || expired)
        fprintf(stderr, "[ban] banlist.json: %d ban(s) restored, %d expired and dropped\n", loaded, expired);
    return loaded;
}
