#!/usr/bin/env python3
"""fe_oracle.py -- Python arbitrary-precision ground truth for the secp256k1
field primitives, and the generator for tests/fe_vec.h.

Written for the 2026-08-22 field rewrite (PERF_SCOPE.md section 5). The point
of this file is that it shares NOTHING with the assembly: it uses Python's own
big integers and the textbook definitions, so agreement is evidence, not a
tautology.

It emits two things into tests/fe_vec.h:

  1. FE_VEC[] -- explicit (a, b, a+b, a-b, a*b, a^2, a^-1) tuples, so a
     failure names an operand pair a human can look at.

  2. A DIGEST over the FULL cross-product of the structured operand family
     (every ordered pair, ~1e6 of them). The C harness rebuilds the identical
     family with the identical construction rules, folds the same digest over
     the assembly's answers, and compares one 64-bit number. That covers the
     entire structured space -- every limb boundary against every other limb
     boundary -- without a 300 MB header.

WHY STRUCTURED OPERANDS AND NOT JUST RANDOM ONES
  Incident #7 (2026-08-21) was two lost carries, one in sc_mul's MULACC and
  one in fe_mul's fold 2. Random operands hit them with probability ~2^-64 and
  ~2^-190; no amount of random differential testing was ever going to find
  them. They were deterministic on structured inputs -- (p - 2^31)^2 exposes
  the fe_mul one exactly. Carry bugs live at limb boundaries, so the family
  below is built out of limb boundaries.
"""
import sys

P = 2**256 - 2**32 - 977
C = 2**32 + 977
M64 = 2**64 - 1


def family():
    """The structured operand family. MUST match build_family() in
    tests/test_fe_repr.c exactly, including order -- the digest depends on it.

    Construction, in this order:
      0..7 ; P-1..P-8 ; 2^i, 2^i-1, 2^i+1 for i in 0..255 ;
      P-2^i, P-2^i-1, P-2^i+1 for i in 0..255 ;
      C-1, C, C+1, 2C, P-C, P-2C ;
      per-limb saturation patterns: 0xFFFFFFFFFFFFFFFF, 0x8000000000000000,
      0x00000000FFFFFFFF and 0xFFFFFFFF00000000 placed at each of the 4 limbs.
    Everything is taken mod P, then de-duplicated keeping first appearance.
    """
    v = []
    v += list(range(8))
    v += [P - k for k in range(1, 9)]
    for i in range(256):
        v += [2**i, 2**i - 1, 2**i + 1]
    for i in range(256):
        v += [P - 2**i, P - 2**i - 1, P - 2**i + 1]
    v += [C - 1, C, C + 1, 2 * C, P - C, P - 2 * C]
    for j in range(4):
        for pat in (0xFFFFFFFFFFFFFFFF, 0x8000000000000000,
                    0x00000000FFFFFFFF, 0xFFFFFFFF00000000):
            v += [pat << (64 * j)]
    out, seen = [], set()
    for x in v:
        x %= P
        if x not in seen:
            seen.add(x)
            out.append(x)
    return out


def fold(h, x):
    """FNV-1a-style 64-bit fold over the four limbs of x. Must match the C."""
    for i in range(4):
        h ^= (x >> (64 * i)) & M64
        h = (h * 0x100000001B3) & M64
    return h


def digest(fam):
    """Digest of a*b, a+b and a-b over EVERY ordered pair of the family."""
    h = 0xCBF29CE484222325
    for a in fam:
        for b in fam:
            h = fold(h, (a * b) % P)
            h = fold(h, (a + b) % P)
            h = fold(h, (a - b) % P)
    return h


def sqr_inv_digest(fam):
    h = 0xCBF29CE484222325
    for a in fam:
        h = fold(h, (a * a) % P)
        h = fold(h, pow(a, P - 2, P))      # 0^-1 is defined as 0 by Fermat
    return h


def limbs_c(x):
    return "{" + ",".join("0x%016xULL" % ((x >> (64 * i)) & M64)
                          for i in range(4)) + "}"


def gen(n, seed):
    import random
    rng = random.Random(seed)
    fam = family()
    cases = []
    # every structured value against a rotating set of structured partners,
    # so the explicit vectors are dominated by boundary-vs-boundary pairs
    for i, a in enumerate(fam):
        b = fam[(i * 7919 + 1) % len(fam)]
        cases.append((a, b))
    # plus the specific shapes that have broken this code before
    cases += [((P - 2**31) % P, (P - 2**31) % P),   # incident #7, fe_mul fold 2
              (P - 1, P - 1), (P - 1, 1), (1, P - 1),
              (2**255, 2**255), (2**128, 2**128), (M64, M64),
              (2**256 - 1 - (2**32 + 976), 2), (P - 2, P - 2),
              (0, 0), (0, P - 1), (P - 1, 0)]
    while len(cases) < n:
        cases.append((rng.randrange(P), rng.randrange(P)))
    cases = cases[:n]

    w = sys.stdout.write
    w("/* GENERATED by validation/fe_oracle.py -- do not edit.\n"
      " * Ground truth for the secp256k1 field primitives, from Python's\n"
      " * arbitrary-precision integers. Regenerate with:\n"
      " *   python3 validation/fe_oracle.py gen %d %d > tests/fe_vec.h\n"
      " */\n" % (n, seed))
    w("#ifndef FE_VEC_H\n#define FE_VEC_H\n#include <stdint.h>\n\n")
    w("typedef struct { uint64_t a[4], b[4], add[4], sub[4], mul[4],"
      " sqr[4], inv[4]; } fe_vec_t;\n\n")
    w("static const fe_vec_t FE_VEC[] = {\n")
    for a, b in cases:
        w("{%s,%s,%s,%s,%s,%s,%s},\n" % (
            limbs_c(a), limbs_c(b), limbs_c((a + b) % P), limbs_c((a - b) % P),
            limbs_c((a * b) % P), limbs_c((a * a) % P),
            limbs_c(pow(a, P - 2, P))))
    w("};\n")
    w("#define FE_VEC_N ((int)(sizeof(FE_VEC)/sizeof(FE_VEC[0])))\n\n")
    fam = family()
    w("/* Digest over the FULL ordered cross-product of the structured family\n"
      " * (%d values -> %d pairs), covering a*b, a+b and a-b for every pair.\n"
      " * tests/test_fe_repr.c rebuilds the identical family and folds the\n"
      " * identical digest over the assembly's answers. */\n"
      % (len(fam), len(fam) ** 2))
    w("#define FE_FAMILY_N %d\n" % len(fam))
    w("#define FE_CROSS_DIGEST 0x%016xULL\n" % digest(fam))
    w("#define FE_SQRINV_DIGEST 0x%016xULL\n" % sqr_inv_digest(fam))
    w("\n#endif\n")


def selftest():
    fam = family()
    assert len(fam) == len(set(fam))
    assert all(0 <= x < P for x in fam)
    # the family must actually contain the shapes we claim it does
    for want in (0, 1, P - 1, 2**255, 2**128 - 1, (P - 2**31) % P, C):
        assert want % P in fam, hex(want)
    print("family size", len(fam), "pairs", len(fam) ** 2)
    print("cross digest  0x%016x" % digest(fam))
    print("sqrinv digest 0x%016x" % sqr_inv_digest(fam))


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "gen":
        gen(int(sys.argv[2]), int(sys.argv[3]))
    else:
        selftest()
