#!/usr/bin/env python3
"""fetch_segwit_coverage.py -- census-driven coverage fixtures (CHAIN_AHEAD_CENSUS.md):
real mainnet spends of shapes our verifier HANDLES but had never run on real
data. Each is located by scanning the block at (or near) its census height for
a shape predicate, so the full txid is derived from chain data, not a truncated
prefix. Emits tests/segwit_coverage_vec.h. Large (inscription) fixtures are
fetched to a gitignored blob by fetch_segwit_coverage_big.py, not inlined.

Usage: python3 validation/fetch_segwit_coverage.py > tests/segwit_coverage_vec.h
"""
import json, subprocess, sys
CLI = "/storage/bitcoin-core-source/build/bin/bitcoin-cli -conf=/storage/core-oracle/bitcoin.conf -datadir=/storage/core-oracle".split()
def rpc(*a):
    r = subprocess.run(CLI + list(a), capture_output=True, text=True)
    if r.returncode != 0: sys.exit("rpc failed: %s: %s" % (a, r.stderr.strip()))
    return r.stdout.strip()
def getblock2(h):
    return json.loads(rpc("getblock", rpc("getblockhash", str(h)), "2"))

def script_ops(hexs):
    """yield opcode bytes of a script (skipping push data). hexs = script hex."""
    b = bytes.fromhex(hexs); i = 0; n = len(b)
    while i < n:
        op = b[i]; i += 1
        if op <= 0x4b: i += op
        elif op == 0x4c and i < n: l=b[i]; i+=1+l
        elif op == 0x4d and i+1 < n: l=b[i]|(b[i+1]<<8); i+=2+l
        elif op == 0x4e and i+3 < n: l=b[i]|(b[i+1]<<8)|(b[i+2]<<16)|(b[i+3]<<24); i+=4+l
        else: yield op

def is_p2sh_wpkh(v):      return v['scriptSig']['hex'].startswith('160014') and len(v.get('txinwitness',[]))==2
def wsh_last(v):
    w=v.get('txinwitness',[]); ss=v['scriptSig']['hex']
    if (ss=='' or ss.startswith('220020')) and len(w)>=1: return w[-1]  # witnessScript
    return None
def tap_leaf(v):
    """for a P2TR script-path input, return the leaf script hex (2nd-to-last witness item), else None."""
    w=v.get('txinwitness',[]); ss=v['scriptSig']['hex']
    if ss!='' or len(w)<2: return None
    ctrl=w[-1]
    if len(ctrl)<2: return None
    if (int(ctrl[:2],16) & 0xfe) != 0xc0: return None   # control block leaf-version byte 0xc0/0xc1
    return w[-2]
def sig_hashtype(item):
    """if item looks like a DER sig (30..) return its trailing hashtype byte, else None."""
    if len(item)<8 or not item.startswith('30'): return None
    return int(item[-2:],16)

# predicate -> find first (tx, target_input_index) in a small window from `start`
def find(start, pred, rng=6, label=""):
    for h in range(start, start+rng):
        try: blk=getblock2(h)
        except SystemExit: continue
        for tx in blk['tx']:
            for i,v in enumerate(tx['vin']):
                if 'coinbase' in v: continue
                if pred(v):
                    return h, tx['txid'], i
    sys.stderr.write("NOT FOUND: %s near %d\n"%(label,start)); return None

# --- predicates ---
def p_codesep(v):
    ws=wsh_last(v)
    return ws is not None and 0xab in set(script_ops(ws))
def p_ht(code):
    def f(v):
        for w in v.get('txinwitness',[]):
            if sig_hashtype(w)==code: return True
        return False
    return f
def p_tap_op(op):
    def f(v):
        ls=tap_leaf(v)
        return ls is not None and op in set(script_ops(ls))
    return f
def p_wititems(nmin):
    return lambda v: len(v.get('txinwitness',[])) >= nmin

TARGETS = [
 ("p2wsh_codesep",     532000, p_codesep,        "OP_CODESEPARATOR inside a P2WSH witnessScript"),
 ("sighash_acp_81",    730000, p_ht(0x81),       "SIGHASH_ALL|ANYONECANPAY (0x81)"),
 ("sighash_none_acp",  815500, p_ht(0x82),       "SIGHASH_NONE|ANYONECANPAY (0x82)"),
 ("sighash_single_acp",788500, p_ht(0x83),       "SIGHASH_SINGLE|ANYONECANPAY (0x83)"),
 ("tapscript_csadd",   826000, p_tap_op(0xba),   "tapscript OP_CHECKSIGADD (0xba)"),
 ("tapscript_cltv",    824500, p_tap_op(0xb1),   "tapscript OP_CHECKLOCKTIMEVERIFY (0xb1)"),
 ("tapscript_csv",     806500, p_tap_op(0xb2),   "tapscript OP_CHECKSEQUENCEVERIFY (0xb2)"),
 ("wit_21items",       551500, p_wititems(9),    "witness stack >8 items (exceeds old TXV_MAX_WIT_ITEMS=8)"),
]
print("/* GENERATED by validation/fetch_segwit_coverage.py from the Core oracle -- do not hand-edit. */")
print("/* Census-driven coverage (CHAIN_AHEAD_CENSUS.md): real shapes the verifier handles but had never run on real data. */")
print("typedef struct { const char* txid_hex; unsigned index; unsigned long long value; const char* spk_hex; } cov_prevout_t;")
print("typedef struct { const char* name; long height; const char* txid; const char* tx_hex; unsigned n_in; const cov_prevout_t* prev;")
print("                 unsigned target; unsigned xfail_witcap; const char* note; } cov_fixture_t;")
entries=[]; idx=0
for name,h0,pred,note in TARGETS:
    got=find(h0,pred,label=name)
    if not got: continue
    h,txid,tgt=got
    bh=rpc("getblockhash",str(h))
    t=json.loads(rpc("getrawtransaction",txid,"true",bh))
    if len(t['hex'])//2 > 90000:
        sys.stderr.write("SKIP %s: tx too large for inline (%d B) -- use big-fetch\n"%(name,len(t['hex'])//2)); continue
    prevs=[]
    for v in t['vin']:
        pv=json.loads(rpc("getrawtransaction",v['txid'],"true"))['vout'][v['vout']]
        prevs.append((v['txid'],v['vout'],int(round(pv['value']*1e8)),pv['scriptPubKey']['hex']))
    xf = 1 if (name=="wit_21items") else 0
    print("static const cov_prevout_t cov_prev_%d[%d] = {"%(idx,len(prevs)))
    for p in prevs: print('  { "%s", %d, %dULL, "%s" },'%p)
    print("};")
    entries.append('  { "%s", %d, "%s", "%s", %d, cov_prev_%d, %d, %d, "%s" },'%(name,h,txid,t['hex'],len(prevs),idx,tgt,xf,note+" @"+str(h)))
    idx+=1
print("static const cov_fixture_t COV_FIXTURES[%d] = {"%len(entries))
for e in entries: print(e)
print("};")
print("#define COV_N %d"%len(entries))
