#!/usr/bin/env python3
"""fetch_segwit_real.py -- real mainnet segwit-v0 spends as fixtures for
tests/test_segwit_real.c, pulled from the local Core oracle (read-only RPC).

Each fixture: the spending tx (full witness serialization), every input's
prevout (scriptPubKey + value, so the test can seed a UTXO view and run the
REAL block dispatch tx_verify_block_connect), and the target input's witness
items (so the test can drive sv_verify_witness_v0 directly for negatives).

Usage: python3 validation/fetch_segwit_real.py > tests/segwit_real_vec.h
Requires the oracle (see project memory: /storage/core-oracle, txindex=1)."""
import json, subprocess, sys
CLI = "/storage/bitcoin-core-source/build/bin/bitcoin-cli -conf=/storage/core-oracle/bitcoin.conf -datadir=/storage/core-oracle".split()
def rpc(*a):
    r = subprocess.run(CLI + list(a), capture_output=True, text=True)
    if r.returncode != 0: sys.exit("rpc failed: %s: %s" % (a, r.stderr.strip()))
    return r.stdout.strip()
# (name, height, txid, target input index, what it exercises)
FIX = [
 ("p2sh_p2wpkh_481825",        481825, "6fd6f5968f86130d4b1fb6e564f27cf13cbec0adae46b558444c7f796e966a05", 1, "P2SH-P2WPKH; the replay's 2nd segwit-block reject"),
 ("p2sh_p2wsh_2of3_481945",    481945, "06c543e4f1f2ff6448e2c370078ac80b1d1ab324aa9dbef8db2202313a70c643", 0, "P2SH-P2WSH 2-of-3 CHECKMULTISIG"),
 ("p2sh_p2wsh_2of2_482385",    482385, "cf2dc05b95aea939fda7309ac9faf921ca9316155452943dc8f6b2c3a8d67dff", 0, "P2SH-P2WSH 2-of-2"),
 ("native_p2wsh_1of2_483705",  483705, "8e70f2a5327e6b2b53d04ebd82a4020d6868557c07764767fd9b8e51c9487619", 0, "native P2WSH 1-of-2"),
 ("p2sh_p2wsh_1of1_580000",    580000, "4188ab94cb1fd039a00ebdb0dfc986fa7d3242d3e5d45b3441d4cdecc1e277af", 0, "P2SH-P2WSH 1-of-1"),
 ("p2sh_p2wsh_3of4_622000",    622000, "0abebaafe6a0a2f8849b89bdcf4cf5594171209de06b7cbdaf68e3afed49cb53", 0, "P2SH-P2WSH 3-of-4"),
 ("native_p2wsh_5of7_757000",  757000, "9187a9dca3700780a7360497aa436cab386f384f4c0ccdccdd995ea60d1caa28", 0, "native P2WSH 5-of-7"),
 ("native_p2wsh_htlc_517000",  517000, "4022cbaecf465bde217611bf5a248d6725afbcd42a6494e93db54ba81e925412", 0, "native P2WSH HTLC-style: CLTV, OP_IF, hash (Lightning-era)"),
 ("p2sh_p2wsh_htlc_577625",    577625, "853487f14cbca2cc1c7fc867763b6d2005813ee5f693f8011713e245ffcd8fe0", 0, "P2SH-P2WSH HTLC-style: CLTV, OP_IF, HASH160"),
]
print("/* GENERATED by validation/fetch_segwit_real.py from the Core oracle -- do not hand-edit. */")
print("typedef struct { const char* txid_hex; unsigned index; unsigned long long value; const char* spk_hex; } sr_prevout_t;")
print("typedef struct { const char* name; long height; const char* txid; const char* tx_hex; unsigned n_in; const sr_prevout_t* prev;")
print("                 unsigned target; unsigned nwit; const char* const* wit_hex; const char* note; } sr_fixture_t;")
entries = []
for i, (name, h, txid, tgt, note) in enumerate(FIX):
    bh = rpc("getblockhash", str(h))
    t = json.loads(rpc("getrawtransaction", txid, "true", bh))
    prevs = []
    for v in t['vin']:
        pv = json.loads(rpc("getrawtransaction", v['txid'], "true"))['vout'][v['vout']]
        prevs.append((v['txid'], v['vout'], int(round(pv['value'] * 1e8)), pv['scriptPubKey']['hex']))
    wit = t['vin'][tgt].get('txinwitness', [])
    print("static const sr_prevout_t sr_prev_%d[%d] = {" % (i, len(prevs)))
    for p in prevs: print('  { "%s", %d, %dULL, "%s" },' % p)
    print("};")
    print("static const char* const sr_wit_%d[%d] = { %s };" % (i, max(1, len(wit)), ", ".join('"%s"' % w for w in wit) or '""'))
    entries.append('  { "%s", %d, "%s", "%s", %d, sr_prev_%d, %d, %d, sr_wit_%d, "%s" },' % (name, h, txid, t['hex'], len(prevs), i, tgt, len(wit), i, note))
print("static const sr_fixture_t SR_FIXTURES[%d] = {" % len(entries))
for e in entries: print(e)
print("};")
print("#define SR_N %d" % len(entries))
