#!/usr/bin/env python3
"""gen_muhash_vectors.py -- regenerate tests/muhash_vectors.h from Bitcoin
Core's OWN MuHash3072 implementation.

Compiles validation/muhash_oracle.cpp against Core's source tree and its
prebuilt libbitcoin_crypto.a (which is where muhash.cpp and chacha20.cpp
live), runs it, and emits the vectors as a C header the test includes.

The vectors are COMMITTED so `make test` never needs a Core build tree, but
they are never hand-written: this is the same generated-not-transcribed
discipline as validation/gen_script_error_defines.py and
validation/glv_split_oracle.py (ENGINEERING_RULES.md 1). Re-run after a Core
upgrade:

    python3 validation/gen_muhash_vectors.py --out tests/muhash_vectors.h

Exit status is non-zero if the Core tree is absent or the oracle fails, so a
Makefile rule wiring this up cannot silently produce an empty header.
"""

import argparse
import os
import subprocess
import sys
import tempfile

DEFAULT_CORE = "/storage/bitcoin-core-source"


def build_oracle(core_src, oracle_cpp, out_bin):
    inc_src = os.path.join(core_src, "src")
    inc_build = os.path.join(core_src, "build", "src")
    libs = [
        os.path.join(core_src, "build", "lib", "libbitcoin_crypto.a"),
        os.path.join(core_src, "build", "lib", "libbitcoin_util.a"),
    ]
    for p in [inc_src, inc_build] + libs:
        if not os.path.exists(p):
            sys.exit("gen_muhash_vectors: missing %s -- is Core built at %s?" % (p, core_src))
    cmd = ["g++", "-std=c++20", "-O2", "-I", inc_src, "-I", inc_build,
           "-o", out_bin, oracle_cpp] + libs
    subprocess.run(cmd, check=True)


def emit(lines, out_path, core_src):
    ks, elem, mul, sets = [], [], [], []
    for line in lines:
        f = line.split()
        if not f:
            continue
        if f[0] == "KS":
            ks.append((f[1], f[2]))
        elif f[0] == "ELEM":
            elem.append(("" if f[1] == "-" else f[1], f[2]))
        elif f[0] == "MUL":
            mul.append((f[1], f[2], f[3]))
        elif f[0] == "SET":
            sets.append((int(f[1]), f[2]))
        else:
            sys.exit("gen_muhash_vectors: unrecognised oracle line: %r" % line)

    # A plausibility floor (ENGINEERING_RULES.md 3.5): a broken parse looks
    # exactly like a short vector list, so refuse to write one.
    if len(ks) < 3 or len(elem) < 5 or len(mul) < 4 or len(sets) < 4:
        sys.exit("gen_muhash_vectors: implausibly few vectors "
                 "(ks=%d elem=%d mul=%d sets=%d) -- refusing to write %s"
                 % (len(ks), len(elem), len(mul), len(sets), out_path))

    try:
        rev = subprocess.run(["git", "-C", core_src, "rev-parse", "--short", "HEAD"],
                             capture_output=True, text=True).stdout.strip()
    except Exception:
        rev = ""

    o = []
    o.append("/* GENERATED by validation/gen_muhash_vectors.py -- DO NOT EDIT.")
    o.append(" *")
    o.append(" * Ground truth for MuHash3072, produced by running")
    o.append(" * validation/muhash_oracle.cpp against Bitcoin Core's own")
    o.append(" * src/crypto/muhash.cpp + src/crypto/chacha20.cpp.")
    if rev:
        o.append(" * Core tree: %s @ %s" % (core_src, rev))
    o.append(" */")
    o.append("#ifndef MUHASH_VECTORS_H")
    o.append("#define MUHASH_VECTORS_H")
    o.append("")
    o.append("/* ChaCha20 keystream, 384 bytes, nonce 0 / counter 0. */")
    o.append("static const struct { const char* key; const char* ks; } MUHASH_KS[] = {")
    for k, s in ks:
        o.append('    { "%s", "%s" },' % (k, s))
    o.append("};")
    o.append("")
    o.append("/* MuHash3072::ToNum3072(data) -> 384 LE limb bytes. */")
    o.append("static const struct { const char* data; const char* num; } MUHASH_ELEM[] = {")
    for d, n in elem:
        o.append('    { "%s", "%s" },' % (d, n))
    o.append("};")
    o.append("")
    o.append("/* Num3072::Multiply(a, b) -> 384 LE limb bytes. */")
    o.append("static const struct { const char* a; const char* b; const char* r; } MUHASH_MUL[] = {")
    for a, b, r in mul:
        o.append('    { "%s", "%s", "%s" },' % (a, b, r))
    o.append("};")
    o.append("")
    o.append("/* MuHash over a deterministic n-element set (see muhash_oracle.cpp's")
    o.append(" * Splitmix element generator), finalized to 32 bytes. */")
    o.append("static const struct { int n; const char* hash; } MUHASH_SET[] = {")
    for n, h in sets:
        o.append('    { %d, "%s" },' % (n, h))
    o.append("};")
    o.append("")
    o.append("#endif /* MUHASH_VECTORS_H */")

    with open(out_path, "w") as f:
        f.write("\n".join(o) + "\n")
    print("gen_muhash_vectors: wrote %s (%d ks, %d elem, %d mul, %d set)"
          % (out_path, len(ks), len(elem), len(mul), len(sets)))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="tests/muhash_vectors.h")
    ap.add_argument("--core-src", default=DEFAULT_CORE)
    args = ap.parse_args()

    here = os.path.dirname(os.path.abspath(__file__))
    oracle_cpp = os.path.join(here, "muhash_oracle.cpp")
    with tempfile.TemporaryDirectory() as td:
        binp = os.path.join(td, "muhash_oracle")
        build_oracle(args.core_src, oracle_cpp, binp)
        out = subprocess.run([binp], capture_output=True, text=True, check=True)
    emit(out.stdout.splitlines(), args.out, args.core_src)


if __name__ == "__main__":
    main()
