#!/usr/bin/env python3
"""gen_bip32_vectors.py -- generate BIP32 full-path + extended-key test vectors.

Uses the INDEPENDENT `bip32` reference implementation (pip package) as the
oracle, plus a tiny pure-Python base58check, to emit a C header of exact
expected values for asm/tests/test_bip32_extkey.c:

  * full-path derivation  m/0'/1/2'/2/1000000000   (BIP32 test vector 1 chain)
  * a BIP44 receive path  m/44'/0'/0'/0/0
  * a BIP84 native-segwit path m/84'/0'/0'/0/0

For every node in those paths we emit: k, c, compressed pubkey, the node's own
BIP32 fingerprint, and the base58check xprv/xpub strings. This lets the asm test
check derive_path byte-exact AND serialize+base58check the extended keys AND
recover the P2PKH address from the pubkey (key -> address -> extended key).

Run from anywhere with `bip32` installed:  python3 gen_bip32_vectors.py > vec.h
"""
import hashlib

from bip32 import BIP32

B58 = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"


def b58check(payload: bytes) -> str:
    checksum = hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
    data = payload + checksum
    n = int.from_bytes(data, "big")
    s = ""
    while n:
        n, r = divmod(n, 58)
        s = B58[r] + s
    pad = len(data) - len(data.lstrip(b"\x00"))
    return "1" * pad + s


def h160(b: bytes) -> bytes:
    return hashlib.new("ripemd160", hashlib.sha256(b).digest()).digest()


def main():
    seed = bytes(range(16))   # BIP32 test vector 1 seed
    root = BIP32.from_seed(seed)

    paths = [
        "m/0'/1/2'/2/1000000000",   # exact BIP32 vector-1 chain end
        "m/44'/0'/0'/0/0",          # BIP44 receive path
        "m/84'/0'/0'/0/0",          # BIP84 (native segwit) path
    ]

    # Reconstruct every PREFIX of each path into a dict of node objects, so a
    # child can look up its parent's fingerprint. The master is 'm' (from_seed).
    nodes = {"m": root}
    for p in paths:
        acc = "m"
        for comp in p.split("/")[1:]:
            acc += "/" + comp
            if acc not in nodes:
                nodes[acc] = BIP32.from_xpriv(root.get_xpriv_from_path(acc))

    out = []
    out.append("/* Autogenerated by asm/validation/gen_bip32_vectors.py -- do not edit. */")
    out.append("/* BIP32 full-path derivation + xprv/xpub extended-key vectors    */")
    out.append("/* (oracle: independent `bip32` package, pure-Python base58check)  */")
    out.append("")
    out.append("static const struct bip32_vec { const char* path; unsigned n;")
    out.append("    unsigned idx[6];")
    out.append("    const char *k, *c, *pub, *fp;")
    out.append("    unsigned depth; const char *parent_fp; unsigned child;")
    out.append("    const char *xprv, *xpub, *addr;")
    out.append("} BIP32VEC[] = {")
    for p in paths:
        node = nodes[p]
        comps = p.split("/")[1:]
        idxs = []
        for comp in comps:
            hard = comp.endswith("'")
            num = int(comp.rstrip("'"))
            idxs.append(num | (0x80000000 if hard else 0))
        address = b58check(b"\x00" + h160(node.pubkey))
        parent = nodes[p.rsplit("/", 1)[0]]
        out.append('    { "%s", %d, {' % (p, len(idxs))
                   + ", ".join("0x%08x" % i for i in idxs) + "},")
        out.append('      "%s", "%s", "%s", "%s",'
                   % (node.privkey.hex(), node.chaincode.hex(),
                      node.pubkey.hex(), node.get_fingerprint().hex()))
        out.append('      %u, "%s", 0x%08x,' % (node.depth,
                   node.parent_fingerprint.hex(), node.index))
        out.append('      "%s", "%s", "%s" },' % (
                   node.get_xpriv(), node.get_xpub(), address))
    out.append("};")
    out.append("")
    out.append("#define BIP32VEC_LEN (sizeof(BIP32VEC)/sizeof(BIP32VEC[0]))")
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
