#!/usr/bin/env python3
"""gen_ecdsa_inverse_vectors.py -- valid ECDSA signature fixtures for
tests/test_ecdsa_inverse.c (PERF_SCOPE.md 4.2 levers A+B differential test).

Signatures come from coincurve (libsecp256k1), an implementation independent
of this repo's asm, so the vectors are also a third-party oracle: every entry
is (z, r, s, Qx, Qy) that libsecp256k1 itself signed, with z < n and the
pubkey uncompressed. Limbs are 4 x u64 little-endian ascending, the repo's
convention. Deterministic: seeded from argv[1] (default 20260821).

    python3 validation/gen_ecdsa_inverse_vectors.py [seed] [count] > tests/ecdsa_inverse_vec.h
"""
import sys, random
import coincurve

N = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141

def limbs(x):
    return ", ".join("0x%016xULL" % ((x >> (64 * i)) & (2**64 - 1)) for i in range(4))

def main():
    seed = int(sys.argv[1]) if len(sys.argv) > 1 else 20260821
    count = int(sys.argv[2]) if len(sys.argv) > 2 else 1024
    rng = random.Random(seed)
    out = []
    while len(out) < count:
        d = rng.getrandbits(256)
        if not (1 <= d < N):
            continue
        z = rng.getrandbits(256)
        if z >= N:
            continue
        pk = coincurve.PrivateKey(d.to_bytes(32, "big"))
        sig = pk.sign_recoverable(z.to_bytes(32, "big"), hasher=None)  # r||s||recid
        r = int.from_bytes(sig[0:32], "big")
        s = int.from_bytes(sig[32:64], "big")
        pub = pk.public_key.format(compressed=False)                  # 04||X||Y
        qx = int.from_bytes(pub[1:33], "big")
        qy = int.from_bytes(pub[33:65], "big")
        # independent check: libsecp256k1 verifies its own (r,s) under this pubkey
        der = pk.sign(z.to_bytes(32, "big"), hasher=None)
        assert coincurve.PublicKey(pub).verify(der, z.to_bytes(32, "big"), hasher=None)
        assert 1 <= r < N and 1 <= s < N
        out.append((z, r, s, qx, qy))
    print("/* GENERATED by validation/gen_ecdsa_inverse_vectors.py seed=%d count=%d" % (seed, count))
    print(" * (z, r, s, Qx, Qy) per row, 4 x u64 LE limbs each, signed by libsecp256k1")
    print(" * via coincurve. Do not edit by hand. */")
    print("#define EIV_N %d" % count)
    print("static const u64 eiv[EIV_N][20] = {")
    for (z, r, s, qx, qy) in out:
        print("  {%s,\n   %s,\n   %s,\n   %s,\n   %s}," % (limbs(z), limbs(r), limbs(s), limbs(qx), limbs(qy)))
    print("};")

if __name__ == "__main__":
    main()
