#!/usr/bin/env python3
"""GLV split oracle -- PERF_SCOPE.md 4.3 / secp256k1_scalar.asm sc_split_lambda.

An independent re-implementation of libsecp256k1's
secp256k1_scalar_split_lambda (scalar_impl.h:142-178) and
secp256k1_scalar_mul_shift_var (scalar_4x64_impl.h:893-915) in Python ints,
with the constants DERIVED from Core's stated basis and checked against the
transcribed values, so a transcription slip is caught here rather than by a
wrong verify result.

Modes:
  gen N SEED   -> print tests/glv_split_vec.h: N random k (< n) plus the edge
                  set, each with its exact (r1, r2). Consumed by
                  tests/test_glv_split.c for byte-exact comparison.
  check        -> read "k r1 r2" hex lines on stdin (tests/test_glv_split
                  --dump N), recompute, report mismatches. Exit 1 on any.
"""
import sys, random

N  = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141
LAMBDA = 0x5363AD4CC05C30E0A5261C028812645A122E22EA20816678DF02967C1B23BD72

# Core's lattice basis (scalar_impl.h comment block):
A1 = 0x3086d221a7d46bcde86c90e49284eb15
B1 = -0xe4437ed6010e88286f547fa90abfe4c3
A2 = 0x114ca50f7a8e2f3f657c1108d9d44cfd8
B2 = A1
MINUS_B1 = (-B1) % N
MINUS_B2 = (-B2) % N
def rnd_div(a, b):            # round(a/b) to nearest, ties up (Core's "round")
    q, r = divmod(a, b)
    return q + (1 if 2*r >= b else 0)
G1 = rnd_div(2**384 * B2, N)
G2 = rnd_div(2**384 * (-B1), N)

# --- self-checks of the constants against what is transcribed into the asm ---
ASM = {
 'LAMBDA':   [0xDF02967C1B23BD72, 0x122E22EA20816678, 0xA5261C028812645A, 0x5363AD4CC05C30E0],
 'MINUS_B1': [0x6F547FA90ABFE4C3, 0xE4437ED6010E8828, 0, 0],
 'MINUS_B2': [0xD765CDA83DB1562C, 0x8A280AC50774346D, 0xFFFFFFFFFFFFFFFE, 0xFFFFFFFFFFFFFFFF],
 'G1':       [0xE893209A45DBB031, 0x3DAA8A1471E8CA7F, 0xE86C90E49284EB15, 0x3086D221A7D46BCD],
 'G2':       [0x1571B4AE8AC47F71, 0x221208AC9DF506C6, 0x6F547FA90ABFE4C4, 0xE4437ED6010E8828],
}
def limbs(v): return [(v >> (64*i)) & (2**64-1) for i in range(4)]
def selfcheck():
    assert pow(LAMBDA, 3, N) == 1 and (LAMBDA*LAMBDA + LAMBDA + 1) % N == 0, "lambda is not a primitive cube root of unity"
    assert A1*B2 - B1*A2 == N, "basis determinant != n"
    assert (A1 + LAMBDA*B1) % N == 0 and (A2 + LAMBDA*B2) % N == 0, "basis vectors are not in the lattice"
    for name, val in (('LAMBDA',LAMBDA),('MINUS_B1',MINUS_B1),('MINUS_B2',MINUS_B2),('G1',G1),('G2',G2)):
        assert limbs(val) == ASM[name], "%s transcription mismatch: derived %x" % (name, val)

def mul_shift_384(a, b):
    l = a * b
    return ((l >> 384) + ((l >> 383) & 1))     # take high limbs + rounding bit 383

def split(k):
    c1 = mul_shift_384(k, G1)
    c2 = mul_shift_384(k, G2)
    c1 = (c1 * MINUS_B1) % N
    c2 = (c2 * MINUS_B2) % N
    r2 = (c1 + c2) % N
    r1 = (k - r2 * LAMBDA) % N
    assert (r1 + LAMBDA * r2) % N == k
    return r1, r2

def edges():
    e = [0, 1, N-1, N-2, 2**128, 2**128-1, 2**255, N >> 1, LAMBDA, N - LAMBDA,
         (LAMBDA * 3) % N, (LAMBDA * (2**127)) % N,        # r1 == 0 candidates
         7, 2**127,                                       # r2 == 0 candidates
         (LAMBDA * 2 + 5) % N, N - 2**128, 2**129 - 1, 2**200 + 12345]
    return e

def h(v): return '%064x' % v

def gen(n, seed):
    selfcheck()
    rng = random.Random(seed)
    ks = edges() + [rng.randrange(N) for _ in range(n)]
    print("/* GENERATED by validation/glv_split_oracle.py gen %d %d -- do not edit. */" % (n, seed))
    print("/* k, r1, r2 as 4 LE u64 limbs each; r1 + LAMBDA*r2 == k (mod n). */")
    print("#define GLV_SPLIT_NVEC %d" % len(ks))
    print("static const unsigned long long glv_split_vec[GLV_SPLIT_NVEC][12] = {")
    for k in ks:
        r1, r2 = split(k)
        row = limbs(k) + limbs(r1) + limbs(r2)
        print("  {" + ",".join("0x%016xULL" % x for x in row) + "},")
    print("};")

def check():
    selfcheck()
    n = bad = 0
    for line in sys.stdin:
        parts = line.split()
        if len(parts) != 3: continue
        k, r1, r2 = (int(p, 16) for p in parts)
        e1, e2 = split(k)
        n += 1
        if (r1, r2) != (e1, e2):
            bad += 1
            if bad <= 5:
                print("MISMATCH k=%s\n  asm r1=%s r2=%s\n  py  r1=%s r2=%s" % (h(k), h(r1), h(r2), h(e1), h(e2)))
    print("glv split oracle: %d cases, %d mismatches -> %s" % (n, bad, "OK" if bad == 0 else "FAIL"))
    sys.exit(1 if bad or n == 0 else 0)

if __name__ == '__main__':
    if len(sys.argv) >= 2 and sys.argv[1] == 'gen':
        gen(int(sys.argv[2]), int(sys.argv[3]))
    elif len(sys.argv) >= 2 and sys.argv[1] == 'check':
        check()
    else:
        print(__doc__); sys.exit(2)
