/* tls_bitcoin_interp.c -- thread-local scratch for bitcoin_interp.S (generated by
 * adapt_armport.py; the x86 module used .tbss, the arm-port used
 * ELF TLS.  Mach-O TLV is accessed from the asm through the
 * C getters below (cross-object @TLVPPAGE from hand-written
 * asm does not get the TLV fixup kind -- see OSX_ROADMAP). */
__thread unsigned char interp_tmp[528];
__thread unsigned char bool_buf[8];
__thread unsigned char interp_err[8];
__thread unsigned char interp_slice[32];
__thread unsigned char cms_keyrefs[1024];
__thread unsigned char cms_sigrefs[1024];
__thread unsigned char cms_scstrip0[10008];
__thread unsigned char cms_scstrip1[10008];
__thread unsigned char cms_needle[1300];

void *tls_get__interp_tmp(void) { return interp_tmp; }
void *tls_get__bool_buf(void) { return bool_buf; }
void *tls_get__interp_err(void) { return interp_err; }
void *tls_get__interp_slice(void) { return interp_slice; }
void *tls_get__cms_keyrefs(void) { return cms_keyrefs; }
void *tls_get__cms_sigrefs(void) { return cms_sigrefs; }
void *tls_get__cms_scstrip0(void) { return cms_scstrip0; }
void *tls_get__cms_scstrip1(void) { return cms_scstrip1; }
void *tls_get__cms_needle(void) { return cms_needle; }
