/* tls_bitcoin_scriptcodec.c -- thread-local scratch for bitcoin_scriptcodec.S (generated by
 * adapt_armport.py; the x86 module used .tbss, the arm-port used
 * ELF TLS.  Mach-O TLV is accessed from the asm through the
 * C getters below (cross-object @TLVPPAGE from hand-written
 * asm does not get the TLV fixup kind -- see OSX_ROADMAP). */
__thread unsigned char scriptnum_buf[16];
__thread unsigned char snum_overflow[8];
__thread unsigned char elem_tmp0[528];
__thread unsigned char elem_tmp1[528];
__thread unsigned char elem_tmp2[528];
__thread unsigned char elem_tmp3[528];
__thread unsigned char vfexec[0];
__thread unsigned char vfexec_sp[8];
__thread unsigned char vfexec_ff[8];
__thread unsigned char hnd_base[8];
__thread unsigned char hnd_dirty[8];
__thread unsigned char hnd_tab[4000];

void *tls_get__scriptnum_buf(void) { return scriptnum_buf; }
void *tls_get__snum_overflow(void) { return snum_overflow; }
void *tls_get__elem_tmp0(void) { return elem_tmp0; }
void *tls_get__elem_tmp1(void) { return elem_tmp1; }
void *tls_get__elem_tmp2(void) { return elem_tmp2; }
void *tls_get__elem_tmp3(void) { return elem_tmp3; }
void *tls_get__vfexec(void) { return vfexec; }
void *tls_get__vfexec_sp(void) { return vfexec_sp; }
void *tls_get__vfexec_ff(void) { return vfexec_ff; }
void *tls_get__hnd_base(void) { return hnd_base; }
void *tls_get__hnd_dirty(void) { return hnd_dirty; }
void *tls_get__hnd_tab(void) { return hnd_tab; }
