#!/usr/bin/env python3
"""Emit asm/tests/cmpct_expected.h: the byte-exact BIP152 cmpctblock that Core
would build for block1.raw with a chosen nonce, computed with the reference
(core-faithful) machinery. test_bip152 compares cmpctblock_build() output
byte-for-byte against this.
"""
import struct, sys
sys.path.insert(0,'/storage/bitcoinmachinecode/validation')
from bip152_ref import shortid_for

def varint(d,o):
    b=d[o]
    if b<0xfd: return b,o+1
    if b==0xfd: return struct.unpack('<H',d[o+1:o+3])[0],o+3
    if b==0xfe: return struct.unpack('<I',d[o+1:o+5])[0],o+5
    return struct.unpack('<Q',d[o+1:o+9])[0],o+9

def tx_size(d,o):
    pos=o; struct.unpack('<I',d[pos:pos+4])[0]; pos+=4
    segwit = d[pos]==0 and d[pos+1]==1
    if segwit: pos+=2
    nin,pos=varint(d,pos)
    for _ in range(nin):
        pos+=36; sl,pos=varint(d,pos); pos+=sl+4
    nout,pos=varint(d,pos)
    for _ in range(nout):
        pos+=8; sl,pos=varint(d,pos); pos+=sl
    if segwit:
        for _ in range(nin):
            nw,pos=varint(d,pos)
            for _ in range(nw):
                wl,pos=varint(d,pos); pos+=wl
    pos+=4
    return pos-o

def block_txs(raw):
    ntx=raw[80]; pos=81; out=[]
    for _ in range(ntx):
        s=tx_size(raw,pos); out.append(raw[pos:pos+s]); pos+=s
    return out

raw=open('/tmp/corecmpt/block1.raw','rb').read()
nonce=0x123456789abcdef1
txs=block_txs(raw)
hdr=raw[0:80]
out=hdr+struct.pack('<Q',nonce)
# shorttxids for txs 1..end
out+=bytes([len(txs)-1])
import hashlib
for t in txs[1:]:
    wtxid=hashlib.sha256(hashlib.sha256(t).digest()).digest()  # wtxid (internal order)
    sid=shortid_for(hdr,nonce,wtxid)
    out+=struct.pack('<Q',sid)[:6]
# prefilled: count=1, index0 varint, coinbase tx
out+=b'\x01\x00'+txs[0]
assert len(out)< 200000

def carr(b,name):
    s='/* %s: %d bytes (reference cmpctblock for block1.raw, nonce=%#x) */\n'%(name,len(b),nonce)
    s+='static const unsigned char %s[%d] = {\n'%(name,len(b))
    for i in range(0,len(b),16):
        s+='  '+', '.join('0x%02x'%x for x in b[i:i+16])+',\n'
    s+='};\n'
    return s

h= '/* Auto-generated by validation/gen_cmpct_expected.py. DO NOT EDIT. */\n\n'
h+=carr(out,'CMPCT_EXPECTED')
h+= '#define CMPCT_EXPECTED_NONCE 0x%016xULL\n'%nonce
h+= '#define CMPCT_EXPECTED_LEN %d\n'%len(out)
open('/storage/bitcoinmachinecode/asm/tests/cmpct_expected.h','w').write(h)
print("wrote cmpct_expected.h len=%d"%len(out))
