#!/usr/bin/env python3
"""Generate C test vectors for script_flags_for_block, re-deriving expected
values independently from the same Core source (not from the .inc the
implementation itself was generated from) so the test isn't just checking
the generator against itself."""
import re, os

SRC = "/storage/bitcoin-core-source/src/kernel/chainparams.cpp"
main = re.search(r"class CMainParams : public CChainParams \{.*?\n\};", open(SRC).read(), re.S).group(0)

def height(field):
    return int(re.search(r"consensus\.%s\s*=\s*(\d+)" % field, main).group(1))

BIP65 = height("BIP65Height")
BIP66 = height("BIP66Height")
CSV = height("CSVHeight")
SEGWIT = height("SegwitHeight")

exc = re.findall(
    r'script_flag_exceptions\.emplace\(\s*//\s*(\w+) exception\s*\n\s*uint256\{"([0-9a-f]{64})"\}',
    main)
BIP16_HASH = next(h for l, h in exc if l == "BIP16")
TAPROOT_HASH = next(h for l, h in exc if l == "Taproot")

BASE = (1 << 0) | (1 << 11) | (1 << 17)  # P2SH | WITNESS | TAPROOT

def flags_at(height, hash_hex=None):
    # Matches Core's GetBlockScriptFlags exactly: the exception override (if
    # any) replaces the BASE bits, but the height-gated bits are ORed in
    # AFTERWARD, unconditionally -- an exception block still gets DERSIG/
    # CLTV/CSV/NULLDUMMY if its height qualifies. Getting this wrong here
    # would make an exception-hash test vector's "expected" value wrong in
    # exactly the way that silently validates a buggy implementation.
    if hash_hex == BIP16_HASH:
        f = 0
    elif hash_hex == TAPROOT_HASH:
        f = (1 << 0) | (1 << 11)
    else:
        f = BASE
    if height >= BIP66: f |= (1 << 2)
    if height >= BIP65: f |= (1 << 9)
    if height >= CSV:   f |= (1 << 10)
    if height >= SEGWIT: f |= (1 << 4)
    return f

ARBITRARY_HASH = "11" * 32  # any non-exception hash

CASES = []
def add(name, height, hash_hex, expect):
    CASES.append((name, height, hash_hex, expect))

# boundary tests, h-1 vs h, for each of the 4 buried deployments
for label, h in [("dersig", BIP66), ("cltv", BIP65), ("csv", CSV), ("segwit", SEGWIT)]:
    add(f"{label}-before", h - 1, ARBITRARY_HASH, flags_at(h - 1))
    add(f"{label}-at", h, ARBITRARY_HASH, flags_at(h))

# a height with none of the 4 active (way before BIP66, the earliest)
add("height-0-none-active", 0, ARBITRARY_HASH, flags_at(0))
# a height with all 4 active (well past segwit)
add("height-600000-all-active", 600000, ARBITRARY_HASH, flags_at(600000))

# exception hash tests. One at a height BEFORE any buried deployment (so the
# override is the whole story) and one AFTER all of them (so the test also
# proves the height-gated bits still get ORed in on top of the override).
add("bip16-exception-hash-overrides-early", 200000, BIP16_HASH, flags_at(200000, BIP16_HASH))
add("taproot-exception-hash-overrides-late", 700000, TAPROOT_HASH, flags_at(700000, TAPROOT_HASH))
# a hash that differs from the exception by a single bit must NOT match
mutated = BIP16_HASH[:-1] + ("0" if BIP16_HASH[-1] != "0" else "1")
add("near-miss-hash-does-not-match-exception", 200000, mutated, flags_at(200000))

out_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'asm', 'tests', 'flags_vec.h')
with open(out_path, 'w') as f:
    f.write('/* AUTO-GENERATED by validation/gen_script_flags_vectors.py -- DO NOT EDIT.\n')
    f.write(' * Test vectors for script_flags_for_block, re-derived independently from\n')
    f.write(' * Core chainparams.cpp (not from the .inc the implementation itself reads,\n')
    f.write(' * so this is not just checking the generator against itself). FV_HASH is\n')
    f.write(' * Core DISPLAY-order hex; the C test reverses it to this codebase\'s raw\n')
    f.write(' * block_hash byte order before calling. */\n')
    f.write('#ifndef FLAGS_VEC_H\n#define FLAGS_VEC_H\n\n')
    f.write('static const char* FV_NAME[] = {\n')
    for c in CASES: f.write('  "%s",\n' % c[0])
    f.write('};\n\nstatic const unsigned long long FV_HEIGHT[] = {\n  ')
    f.write(', '.join(str(c[1]) for c in CASES))
    f.write('\n};\n\nstatic const char* FV_HASH[] = {\n')
    for c in CASES: f.write('  "%s",\n' % c[2])
    f.write('};\n\nstatic const unsigned long long FV_EXPECT[] = {\n  ')
    f.write(', '.join(str(c[3]) for c in CASES))
    f.write('\n};\n\nstatic const unsigned FV_COUNT = %d;\n\n#endif\n' % len(CASES))
print('wrote %d cases to %s' % (len(CASES), out_path))
for c in CASES:
    print('  %-40s h=%-8d hash=%s.. expect=0x%x' % (c[0], c[1], c[2][:8], c[3]))
