#!/usr/bin/env python3
"""Turn Core's official BIP324 reverse-map vectors into a C header.

Unlike the forward map, these vectors pin the EXACT t for each of the eight
branches, and pin an empty result where a branch has no solution. Producing
some other valid encoding is not good enough: the branch order and the signs
have to match libsecp256k1 exactly, or a peer decodes a different key.
"""
import csv, os, sys
SRC = "/storage/bitcoin-core-source/test/functional/test_framework/crypto/xswiftec_inv_test_vectors.csv"
here = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
src = sys.argv[1] if len(sys.argv) > 1 else (SRC if os.path.exists(SRC) else os.path.join(here, "asm/tests/data_xswiftec_inv.csv"))
rows = list(csv.DictReader(open(src, newline="")))
o = ['/* GENERATED by validation/gen_xswiftec_inv_vectors.py -- do not edit.',
     ' * Source: Core test/functional/test_framework/crypto/xswiftec_inv_test_vectors.csv',
     ' * (the official BIP324 reverse-map vectors). An empty t means that case has',
     ' * NO solution and the implementation must refuse it -- half the value of',
     ' * these vectors is in the refusals. */',
     '#ifndef XSWIFTEC_INV_VECTORS_H', '#define XSWIFTEC_INV_VECTORS_H', '',
     'typedef struct { const char* u; const char* x; const char* t[8]; const char* comment; } xswiftec_inv_vec_t;', '',
     'static const xswiftec_inv_vec_t XSINV_VEC[] = {']
for r in rows:
    ts = ', '.join('"%s"' % (r['case%d_t' % c] or '') for c in range(8))
    o.append('  { "%s", "%s", { %s }, "%s" },' % (r['u'], r['x'], ts, r['comment'].replace('"', '\\"')))
o += ['};', '#define XSINV_NVEC ((int)(sizeof(XSINV_VEC)/sizeof(XSINV_VEC[0])))', '', '#endif', '']
open(os.path.join(here, "asm/tests/xswiftec_inv_vectors.h"), "w").write('\n'.join(o))
print("wrote %d vectors" % len(rows))
