#!/usr/bin/env python3
"""Build the authoritative BIP152 test vector header for the ASM tests.

Processes every captured Core cmpctblock (captured over loopback from the real
node), verifies the reference short-id computation against Core's on-wire short
IDs (must all MATCH), and emits a C header `siphash/bip152_vectors.h` with the
exact (header80 bytes, nonce, wtxid bytes, expected 6-byte short-id) tuples the
ASM test uses.
"""
import struct, sys, hashlib, subprocess, json, glob
sys.path.insert(0, '/storage/bitcoinmachinecode/validation')
from bip152_ref import shortid_for

def varint(data, off):
    b=data[off]
    if b<0xfd: return b, off+1
    if b==0xfd: return struct.unpack('<H',data[off+1:off+3])[0], off+3
    if b==0xfe: return struct.unpack('<I',data[off+1:off+5])[0], off+5
    return struct.unpack('<Q',data[off+1:off+9])[0], off+9

def parse(data):
    hdr80=data[0:80]; nonce=struct.unpack('<Q',data[80:88])[0]; off=88
    nshort,off=varint(data,off); shortids=[]
    for _ in range(nshort):
        shortids.append(int.from_bytes(data[off:off+6],'little')); off+=6
    nprefill,off=varint(data,off)
    return hdr80, nonce, shortids, nprefill

RPC=['/storage/bitcoin-core-source/build/bin/bitcoin-cli','-datadir=/tmp/corecmpt','-rpcuser=u','-rpcpassword=p']
def cli(*a):
    return subprocess.run(RPC+[str(x) for x in a],capture_output=True,text=True).stdout

files = glob.glob('/tmp/corecmpt/cmpct_*.bin')
vecs=[]
allok=True
for f in sorted(files):
    data=open(f,'rb').read()
    hdr80,nonce,shortids,nprefill = parse(data)
    hsh=hashlib.sha256(hashlib.sha256(hdr80).digest()).digest()
    bh=hsh[::-1].hex()
    blk=json.loads(cli('getblock',bh,2))
    txs=blk['tx'][1:]  # skip coinbase (prefilled)
    ok=(len(shortids)==len(txs))
    if not ok:
        print("SIZE MISMATCH in %s: %d shortids vs %d non-coinbase"%(f,len(shortids),len(txs)))
    for i,tx in enumerate(txs):
        wtxid=bytes.fromhex(tx['hash'])[::-1]  # wire order
        sid=shortid_for(hdr80,nonce,wtxid)
        if sid!=shortids[i]:
            ok=False; allok=False
            print("  SHORTID MISMATCH %s[%d]: wire=%#014x ref=%#014x"%(f,i,shortids[i],sid))
    if ok:
        # one vector per non-coinbase tx: hdr80, nonce, wtxid(wire), expected shortid(6LE)
        for i,tx in enumerate(txs):
            wtxid=bytes.fromhex(tx['hash'])[::-1]
            vecs.append((hdr80,nonce,wtxid,shortids[i]))
        print("%s: %d txs, %d shorttxids, offset=%d -> MATCH %s"%(f,len(txs),len(shortids), 88, 'OK' if ok else 'FAIL'))
print("\nTotal verified shortid vectors:", len(vecs), "allOK:", allok)
if not allok:
    sys.exit(1)

# --- emit C header ---
def cbytes(name, b, per=16):
    lines=[]
    for i in range(0,len(b),per):
        lines.append('    '+', '.join('0x%02x'%x for x in b[i:i+per])+',')
    return '/* %s: %d bytes */\nunsigned char %s[%d] = {\n%s\n};\n'%(name,len(b),name,len(b),'\n'.join(lines))

out='/* Auto-generated by validation/gen_bip152_vectors.py from cmpctblock messages\n'
out+=' * captured LIVE from Bitcoin Core (v31.99) over loopback. Every short-id\n'
out+=' * below is what Core actually put on the wire for that tx, cross-checked\n'
out+=' * against an independent reference. DO NOT EDIT BY HAND. */\n\n'
out+='#define BIP152_NVEC %d\n'%len(vecs)
out+='static const unsigned char BIP152_HDR[%d][80] = {\n'%len(vecs)
prev=None
for (h,nonce,w,s) in vecs:
    out+=cbytes('b'+str(len(out)%100), h, 16)+'\n'
out+='};\n'
# simpler: emit a flat table instead
out='/* Auto-generated by validation/gen_bip152_vectors.py. DO NOT EDIT. */\n\n'
out+='#define BIP152_NVEC %d\n'%len(vecs)
out+='typedef struct { unsigned char hdr[80]; unsigned long long nonce; unsigned char wtxid[32]; unsigned char shortid[6]; } BIP152Vec;\n'
out+='static const BIP152Vec BIP152_VECS[BIP152_NVEC] = {\n'
for (h,nonce,w,s) in vecs:
    def arr(b):
        return '{'+', '.join('0x%02x'%x for x in b)+'}'
    out+='  { %s, 0x%016xULL, %s, %s },\n'%(arr(h),nonce,arr(w),arr(struct.pack('<Q',s)[:6]))
out+= '};\n'
open('/storage/bitcoinmachinecode/asm/tests/bip152_vectors.h','w').write(out)
print("wrote asm/tests/bip152_vectors.h (%d bytes)"%len(out))
