#!/usr/bin/env python3
"""Signet witness-commitment vectors, taken from REAL signet blocks.

The expectations are not this project's own code restated: the solution and
the stripped script are recomputed here from the raw scriptPubKey using an
independent implementation of Core's FetchAndClearCommitmentSection, so a
shared misunderstanding of the format would have to occur twice, in two
languages, to pass unnoticed.

Usage: gen_signet_vectors.py <datadir> [rpcport] [count]
"""
import json, os, subprocess, sys

HDR = bytes([0xec, 0xc7, 0xda, 0xa2])
CLI = "/storage/bitcoin-core-source/build/bin/bitcoin-cli"

def rpc(datadir, *args):
    out = subprocess.run([CLI, f"-datadir={datadir}", *args],
                         capture_output=True, text=True, timeout=60)
    if out.returncode != 0:
        raise RuntimeError(out.stderr.strip())
    return out.stdout.strip()

def ops(s):
    """Walk a script, yielding (whole_opcode_bytes, pushed_data_or_None)."""
    i = 0
    while i < len(s):
        op = s[i]; start = i; i += 1
        if op <= 75:                       n = op
        elif op == 0x4c:                   n = s[i]; i += 1
        elif op == 0x4d:                   n = int.from_bytes(s[i:i+2], 'little'); i += 2
        elif op == 0x4e:                   n = int.from_bytes(s[i:i+4], 'little'); i += 4
        else:
            yield s[start:i], None
            continue
        data = s[i:i+n]; i += n
        yield s[start:i], data

def minimal_push(d):
    n = len(d)
    if n < 76:      return bytes([n]) + d
    if n <= 0xff:   return bytes([0x4c, n]) + d
    if n <= 0xffff: return bytes([0x4d]) + n.to_bytes(2, 'little') + d
    return bytes([0x4e]) + n.to_bytes(4, 'little') + d

def split(spk):
    """Core's FetchAndClearCommitmentSection, independently."""
    out, sol, found = b"", None, False
    for raw, data in ops(spk):
        if data is not None and len(data) > 0:
            if not found and len(data) > len(HDR) and data[:len(HDR)] == HDR:
                sol = data[len(HDR):]
                data = data[:len(HDR)]
                found = True
            out += minimal_push(data)
        else:
            out += raw
    return (sol, out) if found else (None, spk)

def main():
    datadir = sys.argv[1]
    count = int(sys.argv[2]) if len(sys.argv) > 2 else 8
    tip = int(rpc(datadir, "getblockcount"))
    rows = []
    step = max(1, tip // (count + 1))
    for h in range(step, tip, step):
        if len(rows) >= count: break
        bh = rpc(datadir, "getblockhash", str(h))
        blk = json.loads(rpc(datadir, "getblock", bh, "2"))
        cb = blk["tx"][0]
        for o in cb["vout"]:
            spk = bytes.fromhex(o["scriptPubKey"]["hex"])
            if len(spk) >= 38 and spk[:6] == bytes.fromhex("6a24aa21a9ed"):
                sol, stripped = split(spk)
                if sol is None: continue
                rows.append((h, spk.hex(), sol.hex(), stripped.hex()))
                break
    if not rows:
        sys.exit("no signet commitments found -- is the node synced?")
    here = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    o = ['/* GENERATED by validation/gen_signet_vectors.py -- do not edit.',
         ' * Real signet coinbase witness commitments; the solution and the stripped',
         ' * script are recomputed by an independent Python implementation of Core\'s',
         ' * FetchAndClearCommitmentSection, not by the C code under test. */',
         '#ifndef SIGNET_VECTORS_H', '#define SIGNET_VECTORS_H', '',
         'typedef struct { int height; const char* spk; const char* solution;',
         '                 const char* stripped; } signet_vec_t;', '',
         'static const signet_vec_t SIGNET_VEC[] = {']
    for h, spk, sol, st in rows:
        o.append('  { %d,\n    "%s",\n    "%s",\n    "%s" },' % (h, spk, sol, st))
    o += ['};', '#define SIGNET_NVEC ((int)(sizeof(SIGNET_VEC)/sizeof(SIGNET_VEC[0])))',
          '', '#endif', '']
    open(os.path.join(here, "asm/tests/signet_vectors.h"), "w").write('\n'.join(o))
    print("wrote %d vectors from real signet blocks (tip %d)" % (len(rows), tip))

main()
