#!/usr/bin/env python3
"""Whole REAL signet blocks, for the block-level BIP325 check.

Layers 1-3 are tested against decomposed inputs. This one is fed a block the
way the node receives it, so it also exercises the parts nothing else does:
locating the commitment among the coinbase's outputs, rebuilding the coinbase
without the solution, and taking every other transaction's txid.

Each vector carries the raw block plus the byte offset and length of every
transaction in it, so the test needs no block parser of its own -- a parser in
the test would be a second implementation, and the point is to test the one in
the node.

Usage: gen_signet_block_vectors.py <datadir>
"""
import json, os, subprocess, sys

CLI = "/storage/bitcoin-core-source/build/bin/bitcoin-cli"

def rpc(d, *a):
    r = subprocess.run([CLI, f"-datadir={d}", *a], capture_output=True,
                       text=True, timeout=120)
    if r.returncode != 0: raise RuntimeError(r.stderr.strip())
    return r.stdout.strip()

class R:
    def __init__(s, b): s.b, s.i = b, 0
    def take(s, n):
        if s.i + n > len(s.b): raise ValueError("truncated")
        s.i += n; return s.b[s.i-n:s.i]
    def u8(s): return s.take(1)[0]
    def u32(s): return int.from_bytes(s.take(4), 'little')
    def cs(s):
        n = s.u8()
        if n == 253: return int.from_bytes(s.take(2), 'little')
        if n == 254: return int.from_bytes(s.take(4), 'little')
        if n == 255: return int.from_bytes(s.take(8), 'little')
        return n
    def var(s): return s.take(s.cs())

def tx_spans(raw):
    """Offsets and lengths of each transaction in a serialised block."""
    r = R(raw); r.take(80)
    ntx = r.cs()
    spans = []
    for _ in range(ntx):
        start = r.i
        r.take(4)                                   # version
        save = r.i
        marker, flag = r.u8(), r.u8()
        has_wit = (marker == 0 and flag != 0)
        if not has_wit: r.i = save
        nin = r.cs()
        for _ in range(nin): r.take(36); r.var(); r.take(4)
        nout = r.cs()
        for _ in range(nout): r.take(8); r.var()
        if has_wit:
            for _ in range(nin):
                for _ in range(r.cs()): r.var()
        r.take(4)                                   # locktime
        spans.append((start, r.i - start))
    if r.i != len(raw): raise ValueError("trailing block bytes")
    return spans

def main():
    d = sys.argv[1]
    info = json.loads(rpc(d, "getblockchaininfo"))
    challenge = info["signet_challenge"]
    # A spread of transaction counts, kept small enough to embed: 1 exercises
    # the degenerate merkle, the odd ones the duplicate-last rule, and the
    # larger ones a coinbase with several outputs to search.
    heights = [170781, 113563, 26315, 220242, 91359, 192726]
    rows = []
    for h in heights:
        raw = bytes.fromhex(rpc(d, "getblock", rpc(d, "getblockhash", str(h)), "0"))
        sp = tx_spans(raw)
        rows.append((h, raw, sp))
    total = sum(len(r[1]) for r in rows)
    print("%d blocks, %d bytes of raw block data, tx counts %s"
          % (len(rows), total, [len(r[2]) for r in rows]))

    here = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
    o = ['/* GENERATED by validation/gen_signet_block_vectors.py -- do not edit.',
         ' *',
         ' * WHOLE real signet blocks, as they come off the wire, with the byte',
         ' * span of every transaction precomputed so the test needs no block',
         ' * parser of its own -- one in the test would be a second',
         ' * implementation of the thing under test. */',
         '#ifndef SIGNET_BLOCK_VECTORS_H', '#define SIGNET_BLOCK_VECTORS_H', '',
         'static const char* SB_CHALLENGE = "%s";' % challenge, '',
         'typedef struct { int height; int ntx; const char* raw;',
         '                 const unsigned* off; const unsigned* len;',
         '} signet_block_vec_t;', '']
    for i, (h, raw, sp) in enumerate(rows):
        o.append('static const unsigned SB_OFF_%d[] = {%s};'
                 % (i, ','.join(str(a) for a, _ in sp)))
        o.append('static const unsigned SB_LEN_%d[] = {%s};'
                 % (i, ','.join(str(b) for _, b in sp)))
    o += ['', 'static const signet_block_vec_t SIGNET_BLOCK_VEC[] = {']
    for i, (h, raw, sp) in enumerate(rows):
        o.append('  { %d, %d,\n    "%s",\n    SB_OFF_%d, SB_LEN_%d },'
                 % (h, len(sp), raw.hex(), i, i))
    o += ['};',
          '#define SIGNET_BLOCK_NVEC ((int)(sizeof(SIGNET_BLOCK_VEC)/sizeof(SIGNET_BLOCK_VEC[0])))',
          '', '#endif', '']
    open(os.path.join(here, "asm/tests/signet_block_vectors.h"), 'w').write('\n'.join(o))
    print("wrote asm/tests/signet_block_vectors.h")

main()
