#!/usr/bin/env python3
"""Derive BIP324 ECDH vectors from Core's OFFICIAL packet test vectors.

The published BIP324 vectors give (our privkey, our ellswift, their ellswift,
role) and the resulting session id, but not the intermediate ECDH secret that
sits between them. So the inputs here are lifted verbatim out of Core's
src/test/bip324_tests.cpp, and the expected secret is computed by Core's own
Python reference (test_framework/crypto/ellswift.py), which is an independent
implementation of the same map -- not a restatement of ours.

That makes these inputs official and the expectations independently derived,
which is the best available short of the BIP publishing the intermediate.
"""
import os, re, sys
CORE = "/storage/bitcoin-core-source"
sys.path.insert(0, os.path.join(CORE, "test/functional"))
from test_framework.crypto.ellswift import ellswift_ecdh_xonly
from test_framework.key import TaggedHash

src = open(os.path.join(CORE, "src/test/bip324_tests.cpp")).read()
# each vector: index, priv, ellswift_ours, ellswift_theirs, initiating, ...
pat = re.compile(r'TestBIP324PacketVector\(\s*(\d+),\s*"([0-9a-f]{64})",\s*'
                 r'"([0-9a-f]{128})",\s*"([0-9a-f]{128})",\s*(true|false),', re.S)
rows = []
for m in pat.finditer(src):
    idx, priv, ours, theirs, initiating = m.groups()
    init = initiating == "true"
    x32 = ellswift_ecdh_xonly(bytes.fromhex(theirs), bytes.fromhex(priv))
    a, b = (ours, theirs) if init else (theirs, ours)
    secret = TaggedHash("bip324_ellswift_xonly_ecdh",
                        bytes.fromhex(a) + bytes.fromhex(b) + x32)
    rows.append((idx, priv, ours, theirs, init, secret.hex()))

# Guard against a partial parse. A regex that quietly matches 5 of 7 vectors
# produces a test that passes while covering less, which is the failure mode
# this project keeps running into. Count the call sites independently.
call_sites = len(re.findall(r'^    TestBIP324PacketVector\(', src, re.M))
if not rows:
    sys.exit("no vectors parsed -- has bip324_tests.cpp changed shape?")
if len(rows) != call_sites:
    sys.exit("parsed %d vectors but bip324_tests.cpp has %d call sites -- "
             "the regex is missing some" % (len(rows), call_sites))

here = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
o = ['/* GENERATED by validation/gen_bip324_ecdh_vectors.py -- do not edit.',
     ' * Inputs are verbatim from Core src/test/bip324_tests.cpp (the official',
     ' * BIP324 packet vectors); the expected secret is computed by Core\'s Python',
     ' * reference, since the published vectors do not print the intermediate. */',
     '#ifndef BIP324_ECDH_VECTORS_H', '#define BIP324_ECDH_VECTORS_H', '',
     'typedef struct { const char* priv; const char* ours; const char* theirs;',
     '                 int initiating; const char* secret; } bip324_ecdh_vec_t;', '',
     'static const bip324_ecdh_vec_t ECDH_VEC[] = {']
for idx, priv, ours, theirs, init, secret in rows:
    o.append('  { "%s",\n    "%s",\n    "%s",\n    %d, "%s" },'
             % (priv, ours, theirs, 1 if init else 0, secret))
o += ['};', '#define ECDH_NVEC ((int)(sizeof(ECDH_VEC)/sizeof(ECDH_VEC[0])))', '', '#endif', '']
open(os.path.join(here, "asm/tests/bip324_ecdh_vectors.h"), "w").write('\n'.join(o))
print("wrote %d ECDH vectors (%d initiating, %d responding)"
      % (len(rows), sum(r[4] for r in rows), sum(not r[4] for r in rows)))
