#!/usr/bin/env python3
"""Extract the official BIP324 packet test vectors from Core into a C header.

These are the end-to-end vectors: our private key, both ellswift encodings,
our role, the packet index, the contents, and the expected session id,
garbage terminators and ciphertext. Passing them means the ECDH, the HKDF key
derivation, the role-to-label mapping, the rekeying and the framing are all
right together -- there is nowhere left for an error to hide.

Long messages give only a ciphertext SUFFIX (out_ciphertext_endswith), because
in_multiply repeats the contents up to megabytes; both forms are carried
through so the test can check whichever the vector supplies.
"""
import os, re, sys
CORE = "/storage/bitcoin-core-source/src/test/bip324_tests.cpp"
src = open(sys.argv[1] if len(sys.argv) > 1 else CORE).read()

S = r'((?:"[0-9a-f]*"\s*)*)'          # possibly-empty run of adjacent literals
pat = re.compile(r'TestBIP324PacketVector\(\s*(\d+),\s*"([0-9a-f]{64})",\s*'
                 r'"([0-9a-f]{128})",\s*"([0-9a-f]{128})",\s*(true|false),\s*'
                 + S + r',\s*(\d+),\s*' + S + r',\s*(true|false),\s*'
                 + S + r',\s*' + S + r',\s*' + S + r',\s*' + S + r',\s*' + S + r'\)', re.S)
def cat(m): return "".join(re.findall(r'"([0-9a-f]*)"', m))

rows = list(pat.finditer(src))
sites = len(re.findall(r'^    TestBIP324PacketVector\(', src, re.M))
if len(rows) != sites:
    sys.exit("parsed %d vectors but there are %d call sites -- regex is missing some"
             % (len(rows), sites))

o = ['/* GENERATED by validation/gen_bip324_packet_vectors.py -- do not edit.',
     ' * Source: Core src/test/bip324_tests.cpp (the official BIP324 packet vectors). */',
     '#ifndef BIP324_PACKET_VECTORS_H', '#define BIP324_PACKET_VECTORS_H', '',
     'typedef struct {', '    unsigned idx;', '    const char* priv;',
     '    const char* ours;', '    const char* theirs;', '    int initiating;',
     '    const char* contents;', '    unsigned multiply;', '    const char* aad;',
     '    int ignore;', '    const char* send_garbage;', '    const char* recv_garbage;',
     '    const char* session_id;', '    const char* ciphertext;',
     '    const char* ciphertext_endswith;', '} bip324_pkt_vec_t;', '',
     'static const bip324_pkt_vec_t PKT_VEC[] = {']
for m in rows:
    (idx, priv, ours, theirs, init, contents, mul, aad, ign,
     sg, rg, sid, ct, cte) = m.groups()
    o.append('  { %s, "%s",\n    "%s",\n    "%s",\n    %d, "%s", %s, "%s", %d,\n'
             '    "%s", "%s",\n    "%s",\n    "%s",\n    "%s" },'
             % (idx, priv, ours, theirs, 1 if init == "true" else 0, cat(contents), mul,
                cat(aad), 1 if ign == "true" else 0, cat(sg), cat(rg), cat(sid),
                cat(ct), cat(cte)))
o += ['};', '#define PKT_NVEC ((int)(sizeof(PKT_VEC)/sizeof(PKT_VEC[0])))', '', '#endif', '']
here = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
open(os.path.join(here, "asm/tests/bip324_packet_vectors.h"), "w").write('\n'.join(o))
print("wrote %d packet vectors" % len(rows))
