#!/usr/bin/env python3
"""gen_bip30_consts.py -- generate daemon/bip30_consts.h from Bitcoin Core's
own source. DO NOT hand-transcribe these values.

Same discipline as validation/gen_script_flags.py, and for the same reason:
the two BIP30-grandfathered blocks are identified by HASH, not by height
alone, and a transcription slip in a 64-hex-digit constant is both easy to
make and invisible to every test that does not happen to replay height
91,842.

What it extracts, and from where:

  src/validation.cpp
    IsBIP30Repeat()          -> the two (height, hash) pairs where Core SKIPS
                                the BIP30 check (the LATER duplicate blocks)
    BIP34_IMPLIES_BIP30_LIMIT-> the height at which Core resumes checking

  src/kernel/chainparams.cpp (CMainParams)
    consensus.BIP34Height    -> above this, Core stops checking...
    consensus.BIP34Hash      -> ...but only if the ancestor there really is
                                this block

BYTE ORDER: Core writes these as uint256 display hex (big-endian, the order
`getblockhash` prints). This codebase's block_hash() emits the raw internal
little-endian bytes. The emitted constants are therefore REVERSED from Core's
string, exactly as asm/script_flags_consts.inc's SFC_EXC_*_HASH are -- see
bitcoin_script_flags.asm's header for the empirical verification of that
convention against the real mainnet genesis hash.
"""
import re, sys, os

VAL   = "/storage/bitcoin-core-source/src/validation.cpp"
PARAM = "/storage/bitcoin-core-source/src/kernel/chainparams.cpp"
OUT   = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                     "..", "asm", "daemon", "bip30_consts.h")

def die(m): sys.exit("gen_bip30_consts: " + m)

val = open(VAL).read()

# ---- IsBIP30Repeat: the two grandfathered blocks -------------------------
# NB: the body cannot be delimited with a non-greedy `\{(.*?)\}` -- the
# uint256{"..."} initialisers contain braces of their own and the match stops
# inside the first one. Take a fixed window from the function start instead.
i = val.find("bool IsBIP30Repeat")
if i < 0: die("could not find IsBIP30Repeat in " + VAL)
body = val[i:i+900]
pairs = re.findall(r"nHeight\s*==\s*(\d+)\s*&&\s*block_index\.GetBlockHash\(\)\s*==\s*uint256\{\"([0-9a-fA-F]{64})\"\}",
                   body)
if len(pairs) != 2:
    die("expected exactly 2 BIP30-repeat blocks, found %d" % len(pairs))

# ---- BIP34_IMPLIES_BIP30_LIMIT ------------------------------------------
m = re.search(r"BIP34_IMPLIES_BIP30_LIMIT\s*=\s*(\d+)", val)
if not m: die("could not find BIP34_IMPLIES_BIP30_LIMIT in " + VAL)
limit = int(m.group(1))

# ---- CMainParams BIP34Height / BIP34Hash --------------------------------
src = open(PARAM).read()
cm = re.search(r"class CMainParams : public CChainParams \{.*?\n\};", src, re.S)
if not cm: die("could not find CMainParams in " + PARAM)
main = cm.group(0)
m = re.search(r"consensus\.BIP34Height\s*=\s*(\d+)", main)
if not m: die("could not find consensus.BIP34Height")
bip34h = int(m.group(1))
m = re.search(r"consensus\.BIP34Hash\s*=\s*uint256\{\"([0-9a-fA-F]{64})\"\}", main)
if not m: die("could not find consensus.BIP34Hash")
bip34hash = m.group(1)

def c_bytes(display_hex):
    """Core display hex (big-endian) -> internal little-endian C initialiser."""
    b = bytes.fromhex(display_hex)[::-1]
    return ",".join("0x%02x" % x for x in b)

L = []
L.append("/* GENERATED by validation/gen_bip30_consts.py -- DO NOT EDIT.")
L.append(" * Bitcoin Core src/validation.cpp (IsBIP30Repeat,")
L.append(" * BIP34_IMPLIES_BIP30_LIMIT) + src/kernel/chainparams.cpp (CMainParams).")
L.append(" * Re-run after a Core upgrade.")
L.append(" *")
L.append(" * Hashes are in this codebase's INTERNAL byte order (block_hash's raw")
L.append(" * output), i.e. reversed from Core's display hex. See")
L.append(" * bitcoin_script_flags.asm's header for why. */")
L.append("#ifndef BMC_BIP30_CONSTS_H")
L.append("#define BMC_BIP30_CONSTS_H")
L.append("")
L.append("/* Blocks where Core SKIPS the BIP30 check: the two mainnet duplicate")
L.append(" * coinbases that overwrite an earlier, identical coinbase. */")
for i, (h, hh) in enumerate(pairs):
    L.append("/* Core display hex: %s */" % hh)
    L.append("#define BIP30_REPEAT%d_HEIGHT %s" % (i, h))
    L.append("#define BIP30_REPEAT%d_HASH { %s }" % (i, c_bytes(hh)))
L.append("")
L.append("/* Above BIP34Height, Core stops the BIP30 database check -- but only")
L.append(" * when the ancestor AT that height really is this block. */")
L.append("#define BIP30_BIP34_HEIGHT %d" % bip34h)
L.append("/* Core display hex: %s */" % bip34hash)
L.append("#define BIP30_BIP34_HASH { %s }" % c_bytes(bip34hash))
L.append("")
L.append("/* ...and resumes checking unconditionally from here. */")
L.append("#define BIP30_IMPLIES_LIMIT %d" % limit)
L.append("")
L.append("#endif /* BMC_BIP30_CONSTS_H */")

open(OUT, "w").write("\n".join(L) + "\n")
print("wrote %s" % os.path.normpath(OUT))
print("  repeat blocks : %s" % ", ".join("%s" % h for h, _ in pairs))
print("  BIP34Height   : %d" % bip34h)
print("  resume limit  : %d" % limit)
