#!/usr/bin/env python3
"""Generate secp256k1 field square-root vectors from Python's own big-int
arithmetic, independently of asm/crypto_fe_sqrt.c's addition chain.

p = 2^256 - 2^32 - 977 is 3 mod 4, so a root (when one exists) is
a^((p+1)/4) mod p. Whether one exists is decided by squaring it back, the
same test the C does -- but reached here through pow(), not through a
hand-built chain, so a wrong repeat count in that chain shows up as a
mismatch rather than as agreement.

Writes asm/tests/fe_sqrt_vectors.h.
"""
P = 2**256 - 2**32 - 977

def sqrt_or_none(a):
    if a == 0:
        return 0
    r = pow(a, (P + 1) // 4, P)
    return r if (r * r) % P == a else None

def main():
    import random
    random.seed(20260829)          # reproducible
    vals = []
    # structured: small integers, values near p, powers of two
    vals += [0, 1, 2, 3, 4, 5, 7, 9, 16]
    vals += [P - 1, P - 2, P - 3, P - 977, (P - 1) // 2]
    vals += [2**k % P for k in (1, 8, 31, 32, 64, 128, 255)]
    # and random ones, so both residues and non-residues appear
    vals += [random.randrange(0, P) for _ in range(40)]

    rows = []
    for a in vals:
        r = sqrt_or_none(a)
        if r is None:
            rows.append((a, 0, 0, 0))
        else:
            rows.append((a, 1, r, (P - r) % P if r else 0))

    with open('asm/tests/fe_sqrt_vectors.h', 'w') as f:
        f.write("/* GENERATED by validation/gen_fe_sqrt_vectors.py -- do not edit.\n"
                " * Square roots in the secp256k1 field, from Python's pow(), so the C\n"
                " * addition chain is checked against different arithmetic rather than\n"
                " * against itself. Both roots are listed: a^((p+1)/4) may return either,\n"
                " * and which one is not something a caller should depend on. */\n")
        f.write("#ifndef BMC_FE_SQRT_VECTORS_H\n#define BMC_FE_SQRT_VECTORS_H\n")
        f.write("typedef struct { const char* a; int is_square; const char* root; const char* root_neg; } fe_sqrt_vec;\n")
        f.write("static const fe_sqrt_vec FE_SQRT_VEC[] = {\n")
        for a, sq, r, rn in rows:
            f.write('  {"%064x", %d, "%064x", "%064x"},\n' % (a, sq, r, rn))
        f.write("};\n")
        f.write("#define FE_SQRT_NVEC ((int)(sizeof FE_SQRT_VEC / sizeof FE_SQRT_VEC[0]))\n")
        f.write("#endif\n")
    nsq = sum(1 for _, s, _, _ in rows if s)
    print(f"wrote {len(rows)} vectors: {nsq} squares, {len(rows)-nsq} non-squares")

if __name__ == '__main__':
    main()
