#!/usr/bin/env python3
"""gen_blockfilter_vectors.py -- freeze Core's OWN basic block filters as vectors.

STO-14 (audit 2026-09-03) changed how block_filter.c de-duplicates its element
set: on the byte-wise ELEMENT, as Core's GCSFilter does, rather than on the
64-bit SipHash. The two agree unless two DISTINCT scripts in one block collide
on 64 bits -- about 2^-40 per block -- so the change cannot be demonstrated by
constructing the collision case.

What CAN be demonstrated, and is what "in consensus with Core" actually means
here, is that our filter is byte-identical to Core's over a wide span of real
blocks. This pulls Core's `getblockfilter` output directly and freezes it, so
the comparison is against Core's bytes rather than against our own.

Heights are chosen to span the eras that stress different parts of the builder:
pre-segwit P2PKH/P2SH, the segwit transition, taproot, and modern high-output
blocks. Run against the oracle:

    python3 validation/gen_blockfilter_vectors.py > asm/tests/bfilter_vec.h
"""
import json, subprocess, sys, os

CONF = "/storage/core-oracle/bitcoin.conf"
DATADIR = "/storage/core-oracle"
CLI = "/storage/bitcoin-core-source/build-zmq/bin/bitcoin-cli"

HEIGHTS = [
    1,          # the very first spendable coinbase
    170,        # the first ever P2PK-to-P2PK spend
    100_000,    # early, tiny blocks
    250_000,    # P2SH era
    481_824,    # segwit activation
    500_000,
    600_000,
    700_038,    # already a KAT in test_block_filter.c -- overlap is deliberate
    709_632,    # taproot activation
    800_000,
    900_000,
]

def cli(*args):
    out = subprocess.run([CLI, f"-conf={CONF}", f"-datadir={DATADIR}", *args],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"bitcoin-cli {' '.join(args)} failed: {out.stderr.strip()}")
    return out.stdout.strip()

def main():
    tip = int(cli("getblockcount"))
    rows = []
    for h in HEIGHTS:
        if h > tip:
            print(f"// skipped height {h}: above the oracle tip {tip}", file=sys.stderr)
            continue
        bh = cli("getblockhash", str(h))
        f = json.loads(cli("getblockfilter", bh, "basic"))
        rows.append((h, bh, f["filter"], f["header"]))
        print(f"  height {h}: {len(f['filter'])//2} filter bytes", file=sys.stderr)

    print("/* bfilter_vec.h -- GENERATED by validation/gen_blockfilter_vectors.py")
    print(" * from Bitcoin Core's own `getblockfilter <hash> basic`, against the")
    print(" * oracle node. Do not hand-edit: regenerate.")
    print(" *")
    print(" * These are CORE'S BYTES, not ours re-frozen. They are what makes")
    print(" * \"byte-identical to Core\" a checked claim rather than an assertion,")
    print(" * and they are the vectors STO-14 asked for -- the element-set")
    print(" * de-duplication change is not observable on any single block, so")
    print(" * breadth across eras is the evidence that stands in for it. */")
    print("typedef struct { long height; const char* blockhash;")
    print("                 const char* filter_hex; const char* header_hex; } bfilter_vec_t;")
    print("static const bfilter_vec_t BFILTER_VEC[] = {")
    for h, bh, fh, hd in rows:
        print(f'  {{ {h}, "{bh}",\n    "{fh}",\n    "{hd}" }},')
    print("};")
    print(f"#define BFILTER_VEC_N {len(rows)}")

if __name__ == "__main__":
    main()
