#!/usr/bin/env python3
"""Extract Core's FSChaCha20 / FSChaCha20Poly1305 vectors into a C header.

These are Core's own unit-test vectors (src/test/crypto_tests.cpp), which is
the only published source for them -- BIP324 itself specifies the rekeying
scheme but does not print intermediate vectors. They matter because they
exercise the two things a rewrite gets wrong: the partial-block carry in the
length cipher, and the rekey boundary (msg_idx 500 and 60000 are both far
past the 224-packet interval).
"""
import os, re, sys
CORE = "/storage/bitcoin-core-source/src/test/crypto_tests.cpp"
src = open(sys.argv[1] if len(sys.argv) > 1 else CORE).read()

def strcat(m):
    """C adjacent-string-literal concatenation -> one string."""
    return "".join(re.findall(r'"([0-9a-fA-F]*)"', m))

fs = re.findall(r'TestFSChaCha20\(\s*((?:"[0-9a-f]*"\s*)+),\s*"([0-9a-f]+)",\s*(\d+),\s*((?:"[0-9a-f]*"\s*)+)\)', src)
aead = re.findall(r'TestFSChaCha20Poly1305\(\s*((?:"[0-9a-f]*"\s*)+),\s*((?:"[0-9a-f]*"\s*)+),\s*"([0-9a-f]+)",\s*(\d+),\s*((?:"[0-9a-f]*"\s*)+)\)', src)

n_fs = len(re.findall(r'    TestFSChaCha20\(', src))
n_ae = len(re.findall(r'    TestFSChaCha20Poly1305\(', src))
if len(fs) != n_fs:   sys.exit("parsed %d of %d FSChaCha20 vectors" % (len(fs), n_fs))
if len(aead) != n_ae: sys.exit("parsed %d of %d AEAD vectors" % (len(aead), n_ae))

o = ['/* GENERATED by validation/gen_bip324_fs_vectors.py -- do not edit.',
     ' * Source: Core src/test/crypto_tests.cpp. */',
     '#ifndef BIP324_FS_VECTORS_H', '#define BIP324_FS_VECTORS_H', '',
     'typedef struct { const char* plain; const char* key; unsigned interval;',
     '                 const char* cipher_after_rotation; } fs20_vec_t;', '',
     'static const fs20_vec_t FS20_VEC[] = {']
for plain, key, interval, out in fs:
    o.append('  { "%s", "%s", %s, "%s" },' % (strcat(plain), key, interval, strcat(out)))
o += ['};', '#define FS20_NVEC ((int)(sizeof(FS20_VEC)/sizeof(FS20_VEC[0])))', '',
      'typedef struct { const char* plain; const char* aad; const char* key;',
      '                 unsigned long long msg_idx; const char* cipher; } fsaead_vec_t;', '',
      'static const fsaead_vec_t FSAEAD_VEC[] = {']
for plain, aad, key, idx, cipher in aead:
    o.append('  { "%s",\n    "%s",\n    "%s", %sULL,\n    "%s" },'
             % (strcat(plain), strcat(aad), key, idx, strcat(cipher)))
o += ['};', '#define FSAEAD_NVEC ((int)(sizeof(FSAEAD_VEC)/sizeof(FSAEAD_VEC[0])))', '', '#endif', '']
here = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
open(os.path.join(here, "asm/tests/bip324_fs_vectors.h"), "w").write('\n'.join(o))
print("wrote %d FSChaCha20 and %d FSChaCha20Poly1305 vectors" % (len(fs), len(aead)))
