#!/usr/bin/env python3
"""Base58Check vectors from Python's own big integers -- an implementation
independent of bitcoin_addr.asm's limb division. Payloads: every length 0..78,
with 0..5 leading zero bytes, plus all-zero and all-0xff payloads and the
32-byte input of Core's Base58CheckEncode benchmark. Writes
tests/base58_vectors.h."""
import hashlib, random, sys
ALPHA = "123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz"
def b58check(payload: bytes) -> str:
    data = payload + hashlib.sha256(hashlib.sha256(payload).digest()).digest()[:4]
    n = int.from_bytes(data, "big"); out = ""
    while n: n, r = divmod(n, 58); out = ALPHA[r] + out
    lz = len(data) - len(data.lstrip(b"\0"))
    return "1" * lz + out
random.seed(0x58)
vecs = []
for ln in range(0, 79):
    for lz in (0, 1, 2, 5):
        if lz > ln: continue
        p = bytes(lz) + bytes(random.getrandbits(8) for _ in range(ln - lz))
        vecs.append(p)
for ln in (1, 5, 20, 21, 32, 78):
    vecs.append(bytes(ln)); vecs.append(b"\xff" * ln)
vecs.append(bytes([17,79,8,99,150,189,208,162,22,23,203,163,36,58,147,227,139,2,215,100,91,38,11,141,253,40,117,21,16,90,200,24]))
out = sys.argv[1] if len(sys.argv) > 1 else "tests/base58_vectors.h"
with open(out, "w") as f:
    f.write("/* generated by validation/gen_base58_vectors.py -- Base58Check from Python's big integers */\n")
    f.write("static const struct { const char* payload_hex; const char* want; } BASE58_VEC[] = {\n")
    for p in vecs: f.write('    { "%s", "%s" },\n' % (p.hex(), b58check(p)))
    f.write("};\n#define BASE58_NVEC (sizeof BASE58_VEC / sizeof BASE58_VEC[0])\n")
print(len(vecs), "vectors ->", out)
