#!/usr/bin/env python3
"""Emit asm/tests/block_vec.h: the raw serialized block captured from Core, with
the expected tx boundaries (offset + length for each index) so the ASM
block_txcount / block_tx_at helpers can be verified byte-exact against a real
Core block.
"""
import struct, hashlib, sys
sys.path.insert(0,'/storage/bitcoinmachinecode/validation')

def varint(d,o):
    b=d[o]
    if b<0xfd: return b,o+1
    if b==0xfd: return struct.unpack('<H',d[o+1:o+3])[0],o+3
    if b==0xfe: return struct.unpack('<I',d[o+1:o+5])[0],o+5
    return struct.unpack('<Q',d[o+1:o+9])[0],o+9

def tx_size(d,o):
    """Return the total serialized length (incl witness) of the tx starting at o."""
    pos=o
    version=struct.unpack('<I',d[pos:pos+4])[0]; pos+=4
    segwit=False
    if d[pos]==0x00 and d[pos+1]==0x01:
        segwit=True; pos+=2
    nin,pos=varint(d,pos)
    for _ in range(nin):
        pos+=36                       # prevout(32)+index(4)
        slen,pos=varint(d,pos)
        pos+=slen
        pos+=4                        # sequence
    nout,pos=varint(d,pos)
    for _ in range(nout):
        pos+=8                        # value
        slen,pos=varint(d,pos)
        pos+=slen
    if segwit:
        for _ in range(nin):
            nw,pos=varint(d,pos)
            for _ in range(nw):
                wl,pos=varint(d,pos)
                pos+=wl
    pos+=4                            # locktime
    return pos-o

raw=open('/tmp/corecmpt/block1.raw','rb').read()
ntx=raw[80]
offsets=[0]  # placeholder
pos=81
lens=[]
for _ in range(ntx):
    s=tx_size(raw,pos)
    lens.append(s)
    pos+=s
assert pos==len(raw), (pos,len(raw))
bh=hashlib.sha256(hashlib.sha256(raw[:80]).digest()).digest()[::-1].hex()
print("blockhash",bh,"ntx",ntx,"lens",lens,"total",sum(lens),"consistent",sum(lens)+81==len(raw))

def carr(b,name):
    out='/* %s: %d bytes (real Core block %s) */\n'%(name,len(b),bh)
    out+='static const unsigned char %s[%d] = {\n'%(name,len(b))
    for i in range(0,len(b),16):
        out+='  '+', '.join('0x%02x'%x for x in b[i:i+16])+',\n'
    out+='};\n'
    return out

out='/* Auto-generated by validation/gen_block_vec.py from a real Core regtest block.\n'
out+='   Block hash: %s. DO NOT EDIT BY HAND. */\n\n'%bh
out+=carr(raw,'BLOCK_RAW')
out+='#define BLOCK_NTX %d\n'%ntx
out+='static const int BLOCK_TX_LEN[BLOCK_NTX] = {%s};\n'%(', '.join(map(str,lens)))
open('/storage/bitcoinmachinecode/asm/tests/block_vec.h','w').write(out)
print("wrote asm/tests/block_vec.h")
