#!/usr/bin/env python3
"""Emit the MuHash3072 Fermat-inverse exponent (p-2) as a C byte array.

p = 2^3072 - 1103717 (Core's MuHash3072 modulus, src/crypto/muhash.h
MAX_PRIME_DIFF -- the same constant bitcoin_muhash.asm reduces by). The
denominator's modular inverse is den^(p-2) mod p; the exponent is emitted
little-endian to match the module's limb order. Generated, never
hand-typed (ENGINEERING_RULES.md 1).
"""
P = (1 << 3072) - 1103717
E = (P - 2).to_bytes(384, "little")
print("/* GENERATED by validation/gen_muhash_inv_consts.py -- do not edit. */")
print("/* (p-2) for p = 2^3072 - 1103717, little-endian, 384 bytes. */")
print("static const unsigned char MUHASH_P_MINUS_2[384] = {")
for i in range(0, 384, 16):
    print("    " + ", ".join(f"0x{b:02x}" for b in E[i:i+16]) + ",")
print("};")
