#!/usr/bin/env python3
"""gen_sighash_vectors.py -- emit asm/tests/sighash_vec.h from Bitcoin Core's
own official legacy SignatureHash test fixture
(/storage/bitcoin-core-source/src/test/data/sighash.json), 500 vectors of
(raw_tx, scriptCode, input_index, hashType, expected_hash).

The expected hash in the fixture is displayed in the reversed (txid-style)
byte order; this generator reverses it back to the raw sha256d byte order
this codebase's sighash functions use directly (verified empirically: see
worklog -- computing the preimage by hand and comparing both orders against
one fixture row settled this before any asm was written).

hashType is a signed 32-bit value in the fixture (used to exercise the full
bit-pattern space of SignatureHash's own masking logic, not just realistic
single-byte signature suffixes) -- emitted here as the exact 32-bit pattern.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = '/storage/bitcoin-core-source/src/test/data/sighash.json'
OUT = os.path.join(HERE, '..', 'asm', 'tests', 'sighash_vec.h')

def main():
    d = json.load(open(SRC))
    rows = d[1:]  # first entry is the header-comment row
    with open(OUT, 'w') as f:
        f.write('/* AUTO-GENERATED by validation/gen_sighash_vectors.py from\n')
        f.write(' * Bitcoin Core src/test/data/sighash.json -- DO NOT EDIT.\n')
        f.write(' * Fields: raw_tx hex, scriptCode hex, input_index, hashType (int32),\n')
        f.write(' * expected sighash hex (already reversed to raw byte order). */\n')
        f.write('#ifndef SIGHASH_VEC_H\n#define SIGHASH_VEC_H\n\n')
        f.write('static const char* SH_TX[] = {\n')
        for row in rows:
            f.write('  "%s",\n' % row[0])
        f.write('};\n\n')
        f.write('static const char* SH_SCRIPT[] = {\n')
        for row in rows:
            f.write('  "%s",\n' % row[1])
        f.write('};\n\n')
        f.write('static const unsigned SH_NIN[] = {\n  ')
        f.write(', '.join(str(row[2]) for row in rows))
        f.write('\n};\n\n')
        f.write('static const int SH_HTYPE[] = {\n  ')
        f.write(', '.join(str(row[3]) for row in rows))
        f.write('\n};\n\n')
        f.write('static const char* SH_EXPECT[] = {\n')
        for row in rows:
            raw_order = bytes.fromhex(row[4])[::-1].hex()
            f.write('  "%s",\n' % raw_order)
        f.write('};\n\n')
        f.write('static const unsigned SH_COUNT = %d;\n\n' % len(rows))
        f.write('#endif\n')
    print('wrote %d vectors to %s' % (len(rows), OUT))

if __name__ == '__main__':
    main()
