#!/usr/bin/env python3
"""Emit bitcoin_interp.asm's SCRIPT_ERR_* defines from Core's script_error.h.

The asm interpreter is the AUTHORITATIVE consensus implementation, so it must
report Core's own ScriptError values directly rather than have a C layer
translate them. Hand-transcribing an enum whose members are implicitly
numbered is exactly how the wrong values got asserted here once already, so
the mapping is generated, never typed.

Re-run after a Core upgrade; a name that disappears from Core is reported
rather than silently kept.
"""
import re, sys

HDR = "/storage/bitcoin-core-source/src/script/script_error.h"
ASM = "/storage/bmc-scriptverify/asm/bitcoin_interp.asm"

# --- parse Core's enum: implicit numbering, comments and blank lines ignored
body = open(HDR).read()
m = re.search(r"typedef enum ScriptError_t\s*\{(.*?)\}", body, re.S)
if not m: sys.exit("could not find ScriptError_t enum in " + HDR)
body = re.sub(r"/\*.*?\*/", "", m.group(1), flags=re.S)
body = re.sub(r"//.*", "", body)

core, nxt = {}, 0
for tok in body.split(","):
    tok = tok.strip()
    if not tok: continue
    if "=" in tok:
        name, val = tok.split("=", 1)
        name = name.strip(); nxt = int(val.strip(), 0)
    else:
        name = tok
    if not re.fullmatch(r"SCRIPT_ERR_[A-Z0-9_]+", name):
        sys.exit("unexpected enumerator: %r" % tok)
    core[name] = nxt
    nxt += 1
print("parsed %d Core ScriptError values" % len(core))

# --- read the names the asm currently defines, preserving order
asm = open(ASM).read()
# NOTE: the block this script writes is COLUMN-PADDED, so the pattern must
# tolerate runs of whitespace. It originally required a single space, which
# meant a second run matched only the longest (unpadded) name, spliced a
# one-line block over the range, and destroyed 23 of the 24 defines. A
# generator that cannot re-read its own output is a destructive tool.
defs = re.findall(r"^%define (SCRIPT_ERR_[A-Z0-9_]+)[ \t]+(\d+)[ \t]*$", asm, re.M)
if not defs: sys.exit("no SCRIPT_ERR defines found in " + ASM)
EXPECT_MIN = 20
if len(defs) < EXPECT_MIN:
    sys.exit("only %d defines parsed (expected >=%d) -- refusing to rewrite %s, "
             "this is what a bad pattern looks like" % (len(defs), EXPECT_MIN, ASM))

missing, lines, changed = [], [], 0
for name, old in defs:
    if name not in core:
        missing.append(name); continue
    new = core[name]
    if int(old) != new: changed += 1
    lines.append((name, int(old), new))

if missing:
    sys.exit("asm defines names Core does not have: %s" % ", ".join(missing))

width = max(len(n) for n, _, _ in lines)
out = ["%%define %-*s %d" % (width, n, v) for n, _, v in lines]

print("\n%-*s  old -> new" % (width, "name"))
for n, o, v in lines:
    print("%-*s  %3d -> %3d%s" % (width, n, o, v, "   CHANGED" if o != v else ""))
print("\n%d of %d values change" % (changed, len(lines)))

# --- emit the C header too, so tests and C wrappers cannot drift either.
#     The tapscript test carried its own hand-written enum with the pre-Core
#     values; when the asm was corrected it reported 12 failures that were all
#     the TEST being stale. One generated source removes that failure mode.
CHDR = "/storage/bmc-scriptverify/asm/script_error_codes.h"
h = ["/* GENERATED by validation/gen_script_error_defines.py -- DO NOT EDIT.",
     " * Bitcoin Core ScriptError values, read from Core's own script_error.h.",
     " * The asm interpreter (bitcoin_interp.asm) is the authoritative consensus",
     " * implementation and emits these values directly; this header exists so C",
     " * tests and wrappers compare against the same numbers rather than a",
     " * hand-copied enum. Re-run the generator after a Core upgrade. */",
     "#ifndef SCRIPT_ERROR_CODES_H", "#define SCRIPT_ERROR_CODES_H", ""]
cw = max(len(n) for n in core)
for n, v in sorted(core.items(), key=lambda kv: kv[1]):
    h.append("#define %-*s %d" % (cw, n, v))
h += ["", "#endif", ""]
open(CHDR, "w").write("\n".join(h))
print("wrote", CHDR, "with", len(core), "values")

# --- splice the new block in, in place
start = asm.index("%define SCRIPT_ERR_OK")
end   = asm.index("\n", asm.rindex("%define SCRIPT_ERR_"))
open(ASM, "w").write(asm[:start] + "\n".join(out) + asm[end:])
print("rewrote the define block in", ASM)

# --- self-check: re-read and re-parse. If this script cannot recover its own
#     output, it must not be trusted to run a second time.
again = re.findall(r"^%define (SCRIPT_ERR_[A-Z0-9_]+)[ \t]+(\d+)[ \t]*$",
                   open(ASM).read(), re.M)
got = {n: int(v) for n, v in again}
want = {n: v for n, _, v in lines}
if got != want:
    sys.exit("SELF-CHECK FAILED: re-parsed %d defines, expected %d; "
             "the output is not readable by this script's own pattern"
             % (len(got), len(want)))
print("self-check ok: %d defines re-parse to the intended values" % len(got))
